### ISSUE TITLE
readline failed to build on OS X 10.5.9

### ISSUE THREAD

**Issue by bkmoore** [mistydemeo/tigerbrew#1019]
➜  ~ HOMEBREW_MAKE_JOBS=1 VERBOSE=1 brew install readline
==> Downloading https://ftpmirror.gnu.org/readline/readline-8.2.tar.gz
Already downloaded: /Users/brian/Library/Caches/Homebrew/readline-8.2.tar.gz
==> Verifying readline-8.2.tar.gz checksum
/usr/bin/tar xzf /Users/brian/Library/Caches/Homebrew/readline-8.2.tar.gz
==> ./configure --prefix=/usr/local/Cellar/readline/8.2 --enable-multibyte
checking build system type... powerpc-apple-darwin9.8.0
checking host system type... powerpc-apple-darwin9.8.0

Beginning configuration for readline-8.2 for powerpc-apple-darwin9.8.0

checking whether make sets $(MAKE)... yes
checking for gcc... gcc-4.2
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether gcc-4.2 accepts -g... yes
checking for gcc-4.2 option to enable C11 features... unsupported
checking for gcc-4.2 option to enable C99 features... -std=gnu99
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking for wchar.h... yes
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking whether _XOPEN_SOURCE should be defined... no
checking how to run the C preprocessor... gcc-4.2 -std=gnu99 -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking whether gcc-4.2 -std=gnu99 needs -traditional... no
checking for a BSD-compatible install... /usr/bin/install -c
checking for ar... ar
checking for ranlib... ranlib
checking for an ANSI C-conforming const... yes
checking for inline... inline
checking whether char is unsigned... no
checking for working volatile... yes
checking for size_t... yes
checking for ssize_t... yes
checking whether stat file-mode macros are broken... no
checking for dirent.h that defines DIR... yes
checking for library containing opendir... none required
checking for fcntl... yes
checking for gettimeofday... yes
checking for kill... yes
checking for lstat... yes
checking for pselect... yes
checking for readlink... yes
checking for select... yes
checking for setitimer... yes
checking for fnmatch... yes
checking for memmove... yes
checking for putenv... yes
checking for setenv... yes
checking for setlocale... yes
checking for strcasecmp... yes
checking for strpbrk... yes
checking for sysconf... yes
checking for tcgetattr... yes
checking for vsnprintf... yes
checking for isascii... yes
checking for isxdigit... yes
checking for getpwent... yes
checking for getpwnam... yes
checking for getpwuid... yes
checking for uid_t in sys/types.h... yes
checking for working chown... yes
checking for working strcoll... yes
checking for fcntl.h... yes
checking for unistd.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for varargs.h... no
checking for stdarg.h... yes
checking for stdbool.h... yes
checking for string.h... (cached) yes
checking for strings.h... (cached) yes
checking for limits.h... yes
checking for locale.h... yes
checking for pwd.h... yes
checking for memory.h... yes
checking for termcap.h... yes
checking for termios.h... yes
checking for termio.h... no
checking for sys/ioctl.h... yes
checking for sys/pte.h... no
checking for sys/stream.h... no
checking for sys/select.h... yes
checking for sys/time.h... yes
checking for sys/file.h... yes
checking for sys/ptem.h... no
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking for type of signal functions... posix
checking if signal handlers must be reinstalled when invoked... no
checking for presence of POSIX-style sigsetjmp/siglongjmp... present
checking for lstat... yes
checking whether or not strcoll and strcmp differ... no
checking whether getpw functions are declared in pwd.h... yes
checking whether termios.h defines TIOCGWINSZ... yes
checking for inttypes.h... (cached) yes
checking for sig_atomic_t in signal.h... yes
checking for TIOCSTAT in sys/ioctl.h... yes
checking for FIONREAD in sys/ioctl.h... yes
checking for speed_t in sys/types.h... no
checking for struct winsize in sys/ioctl.h and termios.h... sys/ioctl.h
checking for struct dirent.d_ino... checking for struct dirent.d_ino... yes
yes
checking for struct dirent.d_fileno... checking for struct dirent.d_fileno... yes
yes
checking for struct timeval in sys/time.h and time.h... yes
checking for libaudit.h... no
checking for gcc-4.2 -std=gnu99 options needed to detect all undeclared functions... none needed
checking whether AUDIT_USER_TTY is declared... no
checking for tgetent... no
checking for tgetent in -ltermcap... yes
checking which library has the termcap functions... using libtermcap
checking for nl_langinfo and CODESET... yes
checking for wctype.h... yes
checking for wchar.h... (cached) yes
checking for langinfo.h... yes
checking for mbstr.h... no
checking for mbrlen... yes
checking for mbscasecmp... no
checking for mbscmp... no
checking for mbsnrtowcs... yes
checking for mbsrtowcs... yes
checking for mbschr... no
checking for wcrtomb... yes
checking for wcscoll... yes
checking for wcsdup... no
checking for wcwidth... yes
checking for wctype... yes
checking for wcswidth... yes
checking whether mbrtowc and mbstate_t are properly declared... yes
checking for iswlower... yes
checking for iswupper... yes
checking for towlower... yes
checking for towupper... yes
checking for iswctype... yes
checking for wchar_t in wchar.h... yes
checking for wctype_t in wctype.h... yes
checking for wint_t in wctype.h... yes
checking for wcwidth broken with unicode combining characters... yes
checking size of wchar_t... 4
checking configuration for building shared libraries... supported
configure: creating ./config.status
config.status: creating Makefile
config.status: creating doc/Makefile
config.status: creating examples/Makefile
config.status: creating shlib/Makefile
config.status: creating readline.pc
config.status: creating history.pc
config.status: creating config.h
config.status: executing stamp-h commands
==> make install
/bin/sh ./support/mkinstalldirs /usr/local/Cellar/readline/8.2/include \
		/usr/local/Cellar/readline/8.2/include/readline /usr/local/Cellar/readline/8.2/lib \
		/usr/local/Cellar/readline/8.2/share/info /usr/local/Cellar/readline/8.2/share/man/man3 /usr/local/Cellar/readline/8.2/share/doc/readline \
		/usr/local/Cellar/readline/8.2/lib/pkgconfig
mkdir -p -- /usr/local/Cellar/readline/8.2/include /usr/local/Cellar/readline/8.2/include/readline /usr/local/Cellar/readline/8.2/lib /usr/local/Cellar/readline/8.2/share/info /usr/local/Cellar/readline/8.2/share/man/man3 /usr/local/Cellar/readline/8.2/share/doc/readline /usr/local/Cellar/readline/8.2/lib/pkgconfig
rm -f readline.o
gcc-4.2 -std=gnu99 -c  -DHAVE_CONFIG_H   -I. -I.  -DRL_LIBRARY_VERSION='"8.2"' -DBRACKETED_PASTE_DEFAULT=1 -g -O2 -Wno-parentheses -Wno-format-security -Wno-tautological-constant-out-of-range-compare readline.c
cc1: error: unrecognized command line option "-Wno-tautological-constant-out-of-range-compare"
make: *** [readline.o] Error 1
==> Formula
Path: /usr/local/Library/Formula/readline.rb
==> Configuration
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/mistydemeo/tigerbrew.git
HEAD: 64096125f59f119d3e36d836b2c95493fc9b1934
Last commit: 9 days ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://ia904500.us.archive.org/24/items/tigerbrew
CPU: dual-core 64-bit g5
OS X: 10.5.9-Power Macintosh
Curl: /usr/local/Library/Homebrew/vendor/portable-curl/current/bin/curl
Xcode: 3.1.4
CLT: N/A
GCC-4.0: build 5493
GCC-4.2: build 5577
LLVM-GCC: build 2064
Clang: N/A
X11: 2.1.6 => /usr/X11
System Ruby: 2.3.3-222 => /usr/local/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.15/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/bin/ruby
Java: 1.5.0_30-b03
==> ENV
HOMEBREW_CC: gcc-4.2
HOMEBREW_CXX: g++-4.2
MAKEFLAGS: -j1
CMAKE_PREFIX_PATH: /usr/local
CMAKE_INCLUDE_PATH: /usr/include/libxml2:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Library/ENV/pkgconfig/10.5
HOMEBREW_MAKE_JOBS: 1
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Library/ENV/4.3:/usr/bin:/bin:/usr/sbin:/sbin

Error: readline 8.2 did not build
Logs:
     /Users/brian/Library/Logs/Homebrew/readline/01.configure
     /Users/brian/Library/Logs/Homebrew/readline/01.configure.cc
     /Users/brian/Library/Logs/Homebrew/readline/02.make
     /Users/brian/Library/Logs/Homebrew/readline/02.make.cc
     /Users/brian/Library/Logs/Homebrew/readline/config.log

/usr/local/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/net/http.rb:933:in `connect_nonblock': Failed to connect to: https://api.github.com/search/issues?q=readline+repo:mistydemeo/tigerbrew+in:title+state:open&per_page=100 (GitHub::Error)
SSL_connect returned=1 errno=0 state=error: certificate verify failed
	from /usr/local/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/net/http.rb:933:in `connect'
	from /usr/local/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
	from /usr/local/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/net/http.rb:852:in `start'
	from /usr/local/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/open-uri.rb:319:in `open_http'
	from /usr/local/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/open-uri.rb:737:in `buffer_open'
	from /usr/local/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/open-uri.rb:212:in `block in open_loop'
	from /usr/local/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/open-uri.rb:210:in `catch'
	from /usr/local/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/open-uri.rb:210:in `open_loop'
	from /usr/local/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/open-uri.rb:151:in `open_uri'
	from /usr/local/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/open-uri.rb:717:in `open'
	from /usr/local/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/open-uri.rb:31:in `open'
	from /usr/local/Library/Homebrew/utils.rb:435:in `open'
	from /usr/local/Library/Homebrew/utils.rb:465:in `issues_matching'
	from /usr/local/Library/Homebrew/utils.rb:497:in `issues_for_formula'
	from /usr/local/Library/Homebrew/exceptions.rb:209:in `fetch_issues'
	from /usr/local/Library/Homebrew/exceptions.rb:205:in `issues'
	from /usr/local/Library/Homebrew/exceptions.rb:248:in `dump'
	from /usr/local/Library/brew.rb:170:in `rescue in <main>'
	from /usr/local/Library/brew.rb:61:in `<main>'

➜  readline cat 02.make
2023-11-22 19:06:04 -0800

make
install

/bin/sh ./support/mkinstalldirs /usr/local/Cellar/readline/8.2/include \
		/usr/local/Cellar/readline/8.2/include/readline /usr/local/Cellar/readline/8.2/lib \
		/usr/local/Cellar/readline/8.2/share/info /usr/local/Cellar/readline/8.2/share/man/man3 /usr/local/Cellar/readline/8.2/share/doc/readline \
		/usr/local/Cellar/readline/8.2/lib/pkgconfig
mkdir -p -- /usr/local/Cellar/readline/8.2/include /usr/local/Cellar/readline/8.2/include/readline /usr/local/Cellar/readline/8.2/lib /usr/local/Cellar/readline/8.2/share/info /usr/local/Cellar/readline/8.2/share/man/man3 /usr/local/Cellar/readline/8.2/share/doc/readline /usr/local/Cellar/readline/8.2/lib/pkgconfig
rm -f readline.o
gcc-4.2 -std=gnu99 -c  -DHAVE_CONFIG_H   -I. -I.  -DRL_LIBRARY_VERSION='"8.2"' -DBRACKETED_PASTE_DEFAULT=1 -g -O2 -Wno-parentheses -Wno-format-security -Wno-tautological-constant-out-of-range-compare readline.c
cc1: error: unrecognized command line option "-Wno-tautological-constant-out-of-range-compare"
make: *** [readline.o] Error 1

HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/mistydemeo/tigerbrew.git
HEAD: 64096125f59f119d3e36d836b2c95493fc9b1934
Last commit: 9 days ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://ia904500.us.archive.org/24/items/tigerbrew
CPU: dual-core 64-bit g5
OS X: 10.5.9-Power Macintosh
Curl: /usr/local/Library/Homebrew/vendor/portable-curl/current/bin/curl
Xcode: 3.1.4
CLT: N/A
GCC-4.0: build 5493
GCC-4.2: build 5577
LLVM-GCC: build 2064
Clang: N/A
X11: 2.1.6 => /usr/X11
System Ruby: 2.3.3-222 => /usr/local/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Perl: /usr/bin/perl
Python: /usr/bin/python => /System/Library/Frameworks/Python.framework/Versions/2.5/Resources/Python.app/Contents/MacOS/Python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/bin/ruby
Java: 1.5.0_30-b03

HOMEBREW_CC: gcc-4.2
HOMEBREW_CXX: g++-4.2
MAKEFLAGS: -j1
CMAKE_PREFIX_PATH: /usr/local
CMAKE_INCLUDE_PATH: /usr/include/libxml2:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Library/ENV/pkgconfig/10.5
HOMEBREW_MAKE_JOBS: 1
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Library/ENV/4.3:/usr/bin:/bin:/usr/sbin:/sbin

➜  readline brew doctor
Please note that these warnings are just used to help the Tigerbrew maintainers
with debugging if you file an issue. If everything you use Tigerbrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Some installed formula are missing dependencies.
You should `brew install` the missing dependencies:

    brew install readline

Run `brew missing` for more details.

**Comment by mistydemeo** [comment]
I've pushed a fix that should deal with this - mind giving it a try?

**Comment by bkmoore** [comment]
Brew was able to build readline successfully on my system after your change. Thank you for the help.

Sincerely,

Brian Moore
***@***.***

**Comment by mistydemeo** [comment]
No problem!
