### ISSUE TITLE
XZ fails upon initial Tigerbrew install.

### ISSUE THREAD

**Issue by kpmgeek** [mistydemeo/tigerbrew#1111]
XZ fails to install upon an inital setup of Tigerbrew. Both mirrors appear to be nonfunctional.

**Comment by kpmgeek** [comment]
https://github.com/mistydemeo/tigerbrew/pull/1077 This is resolved by this patch after bypassing its SHA256.

**Comment by mistydemeo** [comment]
Should be fixed now; sorry for the delay!
