### ISSUE TITLE
Perl fails to compile, Tiger PPC G3

### ISSUE THREAD

**Issue by kpmgeek** [mistydemeo/tigerbrew#1115]
Perl fails to compile upon initial config.

`` ==> make
Last 15 lines from /Users/kpmgeek/Library/Logs/Homebrew/perl/02.make:
DYLD_LIBRARY_PATH=/private/tmp/perl20240403-18186-cc0jpz/perl-5.38.2 ./miniperl -Ilib configpm
written lib/Config.pod
updated lib/Config.pm
updated lib/Config_heavy.pl
DYLD_LIBRARY_PATH=/private/tmp/perl20240403-18186-cc0jpz/perl-5.38.2 ./miniperl -Ilib make_ext.pl cpan/Archive-Tar/pm_to_blib    MAKE="make" LIBPERL_A=libperl.dylib
Generating a Unix-style Makefile
Writing Makefile for Archive::Tar
DYLD_LIBRARY_PATH=/private/tmp/perl20240403-18186-cc0jpz/perl-5.38.2 ./miniperl -Ilib make_ext.pl dist/Attribute-Handlers/pm_to_blib    MAKE="make" LIBPERL_A=libperl.dylib
Generating a Unix-style Makefile
Writing Makefile for Attribute::Handlers
DYLD_LIBRARY_PATH=/private/tmp/perl20240403-18186-cc0jpz/perl-5.38.2 ./miniperl -Ilib make_ext.pl cpan/AutoLoader/pm_to_blib    MAKE="make" LIBPERL_A=libperl.dylib
miniperl(29324) malloc: *** error for object 0x1004410: pointer being reallocated was not allocated
miniperl(29324) malloc: *** set a breakpoint in szone_error to debug
Out of memory!
make: *** [cpan/AutoLoader/pm_to_blib] Bus error``

**Comment by mistydemeo** [comment]
Hmm, looks like it ran out of RAM! What computer are you using? What's your CPU and RAM?

**Comment by kpmgeek** [comment]
500mhz G3 and 1gig of ram.

**Comment by sevan** [comment]
Unable to reproduce.

![perl-on-g3-ibook](https://github.com/mistydemeo/tigerbrew/assets/150520/526c626c-a0ff-4649-8105-de2942a5f37f)

**Comment by mistydemeo** [comment]
How much free RAM do both of you have when you start the build? @kpmgeek, can you send me the full logs from `~/Library/Logs/Homebrew/perl`?

**Comment by sevan** [comment]
Machine sites at around 482MB on a fresh boot.

**Comment by kpmgeek** [comment]
I do have Xcode 2.5 installed.  Will give another go from a cold boot and then upload logs.

**Comment by kpmgeek** [comment]
On a cold boot with just top open in terminal.app im at around 630mb free.

**Comment by kpmgeek** [comment]
It compiled on a fresh boot. So I guess this can be closed.

**Comment by mistydemeo** [comment]
Glad it worked! Not surprised this build eats up a ton of RAM.
