### ISSUE TITLE
nmap failed to build on 10.5.9

### ISSUE THREAD

**Issue by noe** [mistydemeo/tigerbrew#1118]
Information in the following gist, as described in the [troubleshooting guide](https://github.com/mistydemeo/tigerbrew/wiki/troubleshooting):

https://gist.github.com/noe/0f2028161b0d7f206ab6ed186d0830a6

**Comment by sevan** [comment]
[You need a newer compiler](https://github.com/mistydemeo/tigerbrew/blob/ab4b3a4304c988862a9f3705319466ed272e8a69/Library/Formula/nmap.rb#L33). I built it on Tiger with GCC 5, but if you want a quick build turn around of the compiler itself you might want to attempt with GCC 4.8 or 9.

**Comment by noe** [comment]
I confirm that it works with gcc-6 (`brew install --cc=gcc-6 nmap`)
