### ISSUE TITLE
Packages with dependence on XQuartz?

### ISSUE THREAD

**Issue by edevaldo** [mistydemeo/tigerbrew#1133]
I'm running tigerbrew on a fresh install of OS 10.4.11. If I. try to install some packages like python3 or tcl-tk, that fail with a dependence on XQuartz. I remember being able to install some of those packages years ago. But I do not remember doing anything special.

XCode 2.5 is installed with X docs and SDK.

Any suggestions?

**Comment by sevan** [comment]
I installed the X11 package from my Tiger install disk & made sure all updates were installed. As long as `/Applications/Utilities/X11.app` and `/usr/X11R6` are available on your system, it should work.

**Comment by edevaldo** [comment]
Thanks a lot. I though I had installed it when Xcode installed the X11 SDK and Docs. Problem solved!
