### ISSUE TITLE
`brew test openssh` undefined method `free_port`

### ISSUE THREAD

**Issue by gsteemso** [mistydemeo/tigerbrew#1140]
Attempting to test `openssh` fails, because it attempts to set a variable to the result of this nonexistent method.

A full-text search shows that the name appears nowhere in Tigerbrew, and I can find no mention of it in Ruby documentation.  It looks to me like somebody’s personal-use utility routine that they forgot to copy-and-paste into the formula.

It does sound like a useful routine to have, but I can’t fill in the blank (so to speak) because I have no idea what it should look like.

**Comment by sevan** [comment]
I missed this importing the formula. Have a look upstream in Homebrew, that's where the formula was sourced from. You should find the implementation of `free_port` there.

**Comment by gsteemso** [comment]
ah, cheers :¬)

**Comment by gsteemso** [comment]
Further discussion of this can and is taking place in the associated pull request.  Marking this "closed".
