### ISSUE TITLE
Mplayer fails to build on Tiger

### ISSUE THREAD

**Issue by ppcluddite** [mistydemeo/tigerbrew#195]
Full gist is here:

https://gist.github.com/ppcluddite/b808ec13181ad900ae56

Here's the relevant make error:

==> /usr/local/Cellar/make/4.0/bin/make
help/help_create.sh help/help_mp-en.h UTF-8
/usr/local/bin/gcc-4.2 -MD -MP -Wundef  -Wstrict-prototypes -Wmissing-prototypes -Wdisabled-optimization -Wno-pointer-sign -Wdeclaration-after-statement -std=gnu99  -Os -w -pipe -mcpu=7450 -faltivec -mmacosx-version-min=10.4 -faltivec -fno-tree-vectorize -maltivec -mabi=altivec -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -Ilibdvdread4 -falign-loops=16 -shared-libgcc -mdynamic-no-pic -I. -Iffmpeg  -I/usr/local/opt/fontconfig/include -I/usr/local/opt/freetype/include -I/usr/local/opt/libpng/include -I/usr/local/opt/make/include  -I/usr/X11R6/include -I/usr/local/Cellar/freetype/2.5.3_1/include/freetype2 -c -o command.o command.c
In file included from sub/font_load.h:25,
                 from command.c:41:
/usr/X11R6/include/ft2build.h:55:38: error: freetype/config/ftheader.h: No such file or directory
In file included from command.c:41:
sub/font_load.h:26:10: error: #include expects "FILENAME" or <FILENAME>
In file included from command.c:41:
sub/font_load.h:60: error: expected specifier-qualifier-list before 'FT_Face'
Makefile:775: recipe for target 'command.o' failed
make: *** [command.o] Error 1

**Comment by mistydemeo** [comment]
Presuming fixed.
