### ISSUE TITLE
curl-ca-bundle fails to install (10.4/G4)

### ISSUE THREAD

**Issue by dcwar** [mistydemeo/tigerbrew#285]
Last one for the evening, I promise. :)

Attempting to upgrade curl-ca-bundle, curl seems to give this error:
"curl: (77) error setting certificate verify locations:
  CAfile: /usr/local/share/ca-bundle.crt
  CApath: none"

Console output:
https://gist.github.com/dcwar/a3f61bddf1117f1d2f26

Thank you!

**Comment by mistydemeo** [comment]
Hmm, I see what's happening here...

I recently switched the Homebrew `curl` method to use Tigerbrew's curl where possible, which allows it to use the newer certs. However, that leads to this issue: when trying to upgrade curl-ca-bundle, the old copy is already gone - hence the certificate verification failure.

**Comment by mistydemeo** [comment]
May be fixed - can you retry?

**Comment by dcwar** [comment]
Success!! Thank you!

**Comment by mistydemeo** [comment]
Great!
