### ISSUE TITLE
Fun with mutt and cyrus-sasl

### ISSUE THREAD

**Issue by chdiza** [mistydemeo/tigerbrew#288]
Hi Misty,

I think I've uncovered a hidden problem with mutt on Tiger PPC.  It has to do with `cyrus-sasl`.

On Tiger, mutt requires `cyrus-sasl`.  Because of this, I wrote a `cyrus-sasl` formula that's carried now in Tigerbrew.

In December, you added a `keg-only` to `cyrus-sasl`.

Today I have found that when `cyrus-sasl` is `keg-only`, mutt will build but not run.  It gives the dyld missing error, complaining that it expects libsasl to be located in `/usr/local/lib`.

I think this is a flaw in mutt's sasl detection code.  The reason is that even outside Tigerbrew (I have never brewed mutt myself), mutt seems to unoverridably believe that cyrus-sasl should be waiting in `/usr/local/lib`.  By this I mean that if one passes `--with-sasl=blah-blah`, then it doesn't matter what "blah-blah" is---mutt will believe that it should expect libsasl to live in `/usr/local/lib`.

Outside of Tigerbrew, I can pass the `--with-sasl=/usr/local/opt/cyrus-sasl flag`, or the `--with-sasl=/usr/local/cellar/cyrus-sasl/2.1.22` flag, and if cyrus-sasl is not brew-linked, mutt will fail to run because it expects libsasl in /usr/local/lib.

In fact, I first noticed this outside of the Tigerbrew context, and then looked to see whether the problem affects Tigerbrewed mutt as well, and it does.

I have only discovered this now because I have always had `cyrus-sasl` linked in the past (my custom formula for it has never been keg-only).  This means mutt's semi-hardcoded expectations always happened to be met.

If this is reproducible on your end, I think cyrus-sasl needs to not be `keg-only` on Tiger until a fix comes along (or else we need to put caveats in `mutt` and `cyrus-sasl` saying that if you need cyrus-sasl for mutt on Tiger you must `brew link --force` it).

I looked at mutt's `configure` script, but I am not very good at understanding those things.  Nothing jumped out at me as being the issue.  If you can reproduce the problem, I'll report the issue to the mutt devs.

**Comment by mistydemeo** [comment]
Can you try reinstalling both mutt and cyrus-sasl? I could exhibit the same problem with a pre-existing copy of cyrus-sasl, but after reinstalling both it works for me.

**Comment by chdiza** [comment]
It may be a while before I have an uninterrupted stretch on my Tiger box, but I'll try again.

I tried deleting and reinstalling both cyrus-sasl and mutt a bunch of times before I reported the bug, but I'll try it anyway in case I was forgetting to do something then that should've been obvious.

**Comment by chdiza** [comment]
Well, I retried it with cyrus-sasl unlinked.  I *think* it's working.  I don't get the missing dylib flameout, but strangely, doing `otool -L /usr/local/bin/mutt` tells me it's linked to:
````
/usr/local/lib/libsasl2.2.dylib
````
which I thought was impossible, since cyrus-sasl is unlinked.  I even checked `/usr/local/lib`; nothing by that name lives there!

This makes me wonder whether mutt has *actually* picked up cyrus-sasl, or merely falsely believes that it has.

**Comment by chdiza** [comment]
I'm going to close this, because---alas!---my trusty Powerbook G4, that twelve-inch, twelve-year-old aluminium warrior, has gone not-so-gently into that good night.  The power supply system crapped out.  That was my only PPC box, so unfortunately I no longer have the ability to test anything or use anything involving Tigerbrew.

Many thanks, @mistydemeo, for Tigerbrew.  I got a lot more good use out of that machine thanks to you.
