### ISSUE TITLE
tigerbrew doesn't seem to work on a PowerBook G4 (10.5.8)

### ISSUE THREAD

**Issue by uwehermann** [mistydemeo/tigerbrew#290]
After a fresh OS install, then install of Xcode 2.5 from developer.apple.com:

```
PowerBook-G4:~ user$ ruby -e "$(curl -fsSkL raw.github.com/mistydemeo/tigerbrew/go/install)"
==> This script will install:
/usr/local/bin/brew
/usr/local/Library/...
/usr/local/share/man/man1/brew.1

Press ENTER to continue or any other key to abort
==> /usr/bin/sudo /bin/mkdir /usr/local
==> /usr/bin/sudo /bin/chmod g+rwx /usr/local
==> /usr/bin/sudo /usr/bin/chgrp admin /usr/local
==> Downloading and Installing Homebrew...
Warning: Now install Xcode: https://developer.apple.com/xcode/
==> Installation successful!
You should run `brew doctor' *before* you install anything.
Now type: brew help
PowerBook-G4:~ user$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Git could not be found in your PATH.
Tigerbrew uses Git for several internal functions, and some formulae use Git
checkouts instead of stable tarballs. You may want to install Git:
  brew install git

Warning: The directory Xcode is reportedly installed to doesn't exist:
  /Xcode2.5/Applications/Xcode.app/Contents/Developer
You may need to `xcode-select` the proper path if you have moved Xcode.

Warning: Your Xcode is configured with an invalid path.
You should change it to the correct path:
  sudo xcode-select -switch /Xcode2.5/Applications/Xcode.app
PowerBook-G4:~ user$ brew install git
==> Installing dependencies for git: openssl, pkg-config, curl-ca-bundle, curl
==> Installing git dependency: openssl
==> Downloading https://ia902307.us.archive.org/31/items/tigerbrew/openssl-1.0.1j.leopard_altivec.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/openssl-1.0.1j.leopard_altivec.bottle.tar.gz
==> Pouring openssl-1.0.1j.leopard_altivec.bottle.tar.gz
Error: undefined method `atomic_write' for nil:NilClass
Warning: Bottle installation failed: building from source.
Error: No such file or directory - /usr/bin/xcode-select
```

Xcode is installed in its default location /Xcode2.5 (not /Developer). There is no xcode-select tool anywhere, doesn't seem to exist in Xcode 2.5.

Any further tigerbrew commands are probably going to fail due to git not being installed.

More info:

```
PowerBook-G4:~ user$ brew --config
HOMEBREW_VERSION: 0.9.5
ORIGIN: (none)
HEAD: (none)
Last commit: never
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: single-core 32-bit g4e
OS X: 10.5.8-Power Macintosh
Xcode: dunno => /Xcode2.5/Applications/Xcode.app/Contents/Developer
Clang: N/A
X11: 2.1.6 => /usr/X11
System Ruby: 1.8.6-369
Perl: /usr/bin/perl
Python: /usr/bin/python => /System/Library/Frameworks/Python.framework/Versions/2.5/bin/python2.5
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/bin/ruby
```

Any idea how to proceed? Thanks!

**Comment by mistydemeo** [comment]
Hm, I haven't seen Xcode 2.5 at that location before!

Does `xcodebuild` work? What's the output of `xcodebuild --version`?

**Comment by mistydemeo** [comment]
I'll remove the `xcode-select` messages - you're right that `xcode-select` was introduced in Xcode 3.0.

**Comment by mistydemeo** [comment]
It's a bug that Tigerbrew is attempting to look inside `Xcode.app` at that location - that only works for Xcode 4.3 or later. Do you have a `/Developer` dir on your system, side from the `Xcode.app` bundle?

**Comment by uwehermann** [comment]
```
PowerBook-G4:Xcode2.5 user$ /Xcode2.5/usr/bin/xcodebuild -version
#Component versions: DevToolsCore-798.0; DevToolsSupport-794.0
```
(Note: --version doesn't exist, -version does)

There's no /Developer, no. 

```
PowerBook-G4:~ user$ find /Xcode2.5 -iname "*Xcode.app*"
/Xcode2.5/Applications/Xcode.app
```

**Comment by mistydemeo** [comment]
Are the developer tools like `xcodebuild` also in `/usr`, or just at the path within `/Xcode2.5`?

**Comment by uwehermann** [comment]
Only in /Xcode2.5:

```
PowerBook-G4:bin user$ find / -name "*otool*" 2>/dev/null
/Library/Receipts/DeveloperTools.pkg/Contents/Resources/CoexUtils/otool.py
/System/Library/Frameworks/DiscRecording.framework/Versions/A/Resources/draudiotool
/usr/local/Library/Formula/xdotool.rb
/Volumes/Xcode Tools/Packages/Packages/DeveloperTools.pkg/Contents/Resources/CoexUtils/otool.py
/Xcode2.5/usr/bin/otool
/Xcode2.5/usr/bin/otool64
/Xcode2.5/usr/share/man/man1/otool.1
/Xcode2.5/usr/share/man/man1/otool64.1
PowerBook-G4:bin user$ find / -name "*xcodebuild*" 2>/dev/null
/Xcode2.5/usr/bin/xcodebuild
/Xcode2.5/usr/share/man/man1/xcodebuild.1
```

**Comment by mistydemeo** [comment]
Sorry for the delay in replying.

So, a couple of things:

1) Is there a reason you're using Xcode 2.5? The most recent release of Xcode for Leopard is 3.1.4. Xcode 2.5 for Leopard may well work, but I recommend users use the most recent Xcode for their OS unless there's a specific need for an older version.
2) Regarding the developer tools - Tigerbrew expects the "command line support" package in Xcode to be installed, both the command line tools package and the headers and libraries package. You can install that by rerunning the Xcode installer and picking the appropriate option. These packages are what install the developer tools in `/usr/bin`, as well as headers in `/usr/include` and system framework headers. Are you able to install it?

**Comment by uwehermann** [comment]
OK, I feel a bit stupid now. I got the PowerBook G4 from ebay recently and it was supposed to come with Mac OS X Tiger; it also did come with a 10.4.2 install CD (Tiger). However, apparently what's on the laptop right now is Leopard though (10.5.8) so I may try a more recent Xcode indeed.

But this is a bug nonetheless I think, since Xcode 2.5 is the latest version available for Mac OS X Tiger, right? And the name "tigerbrew" suggests Tiger should be supported(?)

I can't seem to download anything else from developer.apple.com that may have command-line tools, and I also don't see any settings the Xcode 2.5 itself to let me download more stuff. I assume the extra download is only available in later versions of XCode (i.e. not available for Tiger)?

**Comment by mistydemeo** [comment]
> But this is a bug nonetheless I think, since Xcode 2.5 is the latest version available for Mac OS X Tiger, right? And the name "tigerbrew" suggests Tiger should be supported(?)

Tiger is supported, yes! One of my two main Tigerbrew machines is running OS X 10.4.11 with Xcode 2.5; it's a fully supported configuration.

Regarding the command-line tools, it's one of the options that's on by default when Xcode is installed. It's a part of the main installer; not a separate download. I haven't tried installing Xcode 2.5 on Leopard, but you should be able to just rerun the installer and make sure that that option is enabled, which will ensure that the extra packages get installed.

**Comment by uwehermann** [comment]
OK, installed Xcode 3.1.4 now. I wasn't able to find any option to make Xcode 2.5 usable on Leopard. According to the PDF in the installer .dmg it'll install into /Developer on Tiger, and into /Xcode2.5 on Leopard (intentionally). No xcode-select available in 2.5, it's only in e.g. 3.1.4.

After installing 3.1.4, tigerbrew seems to work fine now. I guess it may not be worth trying to make Xcode 2.5 usable for tigerbrew on Leopard since 3.1.4 is available there; Xcode 2.5 seems to / should work fine if installed on Tiger, so I guess this bug can be closed after a small documentation update to mention that 2.5 is not usable on Leopard (but works fine on Tiger).

**Comment by chdiza** [comment]
It already is in the docs, on the Troubleshooting page, under "1) Check for common issues":

> Check that you have the latest Xcode available for your OS. That's 2.5 for Tiger, 3.1.4 for Leopard.

**Comment by miniupnp** [comment]
so I guess this bug can be closed :)
