### ISSUE TITLE
brew returns Compile Error after latest update (10.4/G4)

### ISSUE THREAD

**Issue by dcwar** [mistydemeo/tigerbrew#291]
Thanks for the latest update! Perhaps you're already aware of this, but it seems that brew is now reporting a Compile Error. The gist below has the console output for 'brew outdated' and 'brew doctor,' after the update. (They are identical.)

https://gist.github.com/dcwar/74bca33ba93964a888dd

I hope that helps!

**Comment by mistydemeo** [comment]
Thanks! The fix for this was accidentally removed in the last merge; reincorporated.

**Comment by dcwar** [comment]
Cool! Unfortunately brew is now giving me the following error when I try to install any package:

Error: You must `brew install openssl` to compute sha256 hashes on Tiger

I can't seem to upgrade / install openssl as a result....
