### ISSUE TITLE
Brew / OpenSSL error (10.4/G4)

### ISSUE THREAD

**Issue by dcwar** [mistydemeo/tigerbrew#292]
To follow up on issue #291, brew now gives the following error when I try to install any package:

Error: You must brew install openssl to compute sha256 hashes on Tiger

Example Gist: 
https://gist.github.com/dcwar/7f7bfcff217a7a6602d4#file-gistfile1-txt

I can't seem to upgrade / install openssl - or any other package - as a result.. (It goes without saying, but OpenSSL is currently installed.)

**Comment by mistydemeo** [comment]
Sorry about that - fixed!

**Comment by dcwar** [comment]
Yay! Thank you!
