### ISSUE TITLE
NoMethodError when building bottles

### ISSUE THREAD

**Issue by mistydemeo** [mistydemeo/tigerbrew#294]
When building a bottle, the call to `#post_install_defined?` will fail with a `NoMethodError` when attempting to call `#owner` on a `Method` object. This method was introduced in Ruby 1.8.7.

This was introduced in Homebrew/homebrew@bc27b183.

**Comment by jacknagel** [comment]
I think it can be implemented as

```rb
self.class.public_instance_methods(false).map(&:to_s).include?("post_install")
```

At some point the `_methods` methods started returning symbols rather than strings. I'm not sure what version, but you may not need the `map(&:to_s)` depending on what you want to support.

**Comment by mistydemeo** [comment]
Thanks! Used that.
