### ISSUE TITLE
libtool will not build without m4 (10.4/G4)

### ISSUE THREAD

**Issue by dcwar** [mistydemeo/tigerbrew#295]
Libtool requires m4, which seems to have been removed from Tigerbrew. (While I still have 1.4.17 from before Tigerbrew's architecture changed a few months back, brew no longer seems to recognize it.) 

Without libtool, we cannot build imagemagick.

Console output:
https://gist.github.com/dcwar/8e9bea52bf67d56701d4

Config.log:
https://gist.github.com/dcwar/52ddbe43df0009e9eede

**Comment by mistydemeo** [comment]
Good catch, thanks!

Tigerbrew uses the `homebrew/dupes/m4` formula when appropriate, and it looks like libtool will need this. I'll confirm on my tigerbox tonight, then add the dependency if necessary.

**Comment by mistydemeo** [comment]
Pushed a fix - this should be resolved now.

**Comment by dcwar** [comment]
Awesome, thank you!
