### ISSUE TITLE
gstreamer requires Tigerbrew flex (10.4/G4)

### ISSUE THREAD

**Issue by dcwar** [mistydemeo/tigerbrew#296]
Adding depends_on "flex" to the formula allows this to build successfully.

(If you can recommend a tutorial on using git, I'd be happy to submit these myself in future... last time I accidentally borked my entire install.)

**Comment by mistydemeo** [comment]
There's a [contributing guide](https://github.com/mistydemeo/tigerbrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-%28and-get-it-merged%29.md) in the documentation. If it's not clear enough, or you need more starter tutorial info, just let me know and I'd be glad to help!

**Comment by dcwar** [comment]
Took a moment, but I figured it out - thanks! Pull request added.

**Comment by dcwar** [comment]
Awesome, didn't know that existed! Took a moment, but I figured it out - thanks! Pull request added.
