### ISSUE TITLE
Can no longer brew a custom formula on Tiger PPC

### ISSUE THREAD

**Issue by chdiza** [mistydemeo/tigerbrew#298]
After the latest git pull, when I do `brew install -d myformula.rb`, I now get:
````
Error: wrong argument type Class (expected Module)
Please report this bug:
    https://github.com/mistydemeo/tigerbrew/wiki/troubleshooting
/usr/lib/ruby/1.8/irb/input-method.rb:87:in `include'
/usr/lib/ruby/1.8/irb/input-method.rb:87
/usr/lib/ruby/1.8/irb.rb:20:in `require'
/usr/lib/ruby/1.8/irb.rb:20
/usr/local/Library/Homebrew/debrew/irb.rb:1:in `require'
/usr/local/Library/Homebrew/debrew/irb.rb:1
/usr/local/Library/Homebrew/debrew.rb:2:in `require'
/usr/local/Library/Homebrew/debrew.rb:2
/usr/local/Library/Homebrew/formula_installer.rb:13:in `require'
/usr/local/Library/Homebrew/formula_installer.rb:13
/usr/local/Library/Homebrew/cmd/install.rb:5:in `require'
/usr/local/Library/Homebrew/cmd/install.rb:5
/usr/local/Library/brew.rb:53:in `require'
/usr/local/Library/brew.rb:53:in `require?'
/usr/local/Library/brew.rb:112
````

I've never seen this one before.

**Comment by mistydemeo** [comment]
Is `readline` one of the dependencies of your formula?

**Comment by chdiza** [comment]
No, no readline.  When I get home I can post the custom formula if you like (it's for `msmtp`).

That formula has worked since Jan 2013.  The only think that looks even remotely non-standard about it is that I declare an option.

**Comment by chdiza** [comment]
Did a bit of troubleshooting, and things are weird.

First, if I make my custom msmtp formula just be identical to the official one, I get the exact same error I reported above.

If I move my custom formula from where it lives (~/.brewstuff/formula/msmtp.rb) to `~/` and try to install, it works just fine (whether or not it exactly apes the offical formula).

So it appears there's something going on with paths rather than the particular differences between my custom formula and the official one.

Stranger still: It seems to be ONLY msmtp that has this issue.  I was able to brew other custom formulas, EVEN when they reside ~/.brewstuff/formula.

I thought maybe it had to do with me `cd`ing to that dir via some symlinks (even though that had never been a problem before).  So I did it the long way, without symlinks, and that had zero effect on anything.

**Comment by chdiza** [comment]
I may---may---have found the problem.  My custom formulas in the aforementioned folder include a custom `readline` formula.  I found that when I renamed that formula to `chdiza-readline` (and did the same inside the formula), I haven't had this issue again.

I don't know why the above errors would've been thrown just by having a readline formula *sitting* in that dir (I wasn't brewing it, or anything that pulls it in, when I got those errors).  Also, this is TigerPPC specific.

I've been brewing some stuff on my freshly reinstalled Tiger, and I can confirm that without the renaming of the readline formula, the above error was still being emitted.

**Comment by mistydemeo** [comment]
Do you mind posting your custom formula and the custom readline formula?

**Comment by chdiza** [comment]
Custom msmtp formula: https://gist.github.com/chdiza/837d838519566715c436

(Note that after my earlier note, and especially after my fresh Tiger install, what happened with my custom msmtp formula was happening with *all* the ones I tried before giving up).

Custom readline formula (sans renaming): https://gist.github.com/chdiza/73bf840a5e69b3466190

**Comment by chdiza** [comment]
Not sure I can reproduce this anymore.  I'm away from my Tiger/Leo dual-boot beast for a while.  I'll re-open this if I see it again.

**Comment by mistydemeo** [comment]
Thanks!
