### ISSUE TITLE
Circular dependency: Need openssl to install pkg-utils and makedepend to install openssl.

### ISSUE THREAD

**Issue by tntc** [mistydemeo/tigerbrew#299]
Fresh install of home-brew, stuck with a circular dependency-type problem.

Brew doctor says I should install git.

"Warning: Git could not be found in your PATH.
Tigerbrew uses Git for several internal functions, and some formulae use Git
checkouts instead of stable tarballs. You may want to install Git:
  brew install git"

Git requires openssl.
openssl required pkg-utils and makedepend.
pkg-utils requires openssl.

The error I'm getting is this:
Error: You must `brew install openssl` to compute sha256 hashes on Tiger

**Comment by mistydemeo** [comment]
Thanks, I've updated `pkg-config` so this won't happen again!

Since you can't `brew update` yet, you can install the fixed version via URL:

```
brew install https://raw.githubusercontent.com/mistydemeo/tigerbrew/master/Library/Formula/pkg-config.rb
```

**Comment by tntc** [comment]
Muchos Gracias! My PowerMac10,1 is back up and running thanks to you!

**Comment by mistydemeo** [comment]
Great, glad to hear it!
