### ISSUE TITLE
openssl install loop

### ISSUE THREAD

**Issue by LoneStarMac** [mistydemeo/tigerbrew#306]
copied from duplicate ticket under wrong package (https://github.com/Homebrew/homebrew/issues/36816):

When I try to install any formula, I get the error
`You must brew install openssl to compute sha256 hashes on Tiger`

When I try to `brew install openssl` I get the same error.

I followed the advice in issue #108 and executed mistydemeo's workaround formula, and that installed openssl 1.0.1 just fine since re-executing that code tells me it's already installed. I also installed the certs as instructed by brew following mistydemeo's openssl formula.

I  executed `brew uninstall openssl`, and it successfully removed openssl 1.0.1, but `brew install openssl` is still failing because I don't have openssl installed. :)

Is there a way to skip computation of hashes on openssl installation, just so it will install?

GIST here: https://gist.github.com/LoneStarMac/afab8d02f2e2940fa207#file-gistfile1-txt

**Comment by chdiza** [comment]
Did you try `brew install openssl` in Tigerbrew?  Or are you still using Homebrew?  This should not happen in Tigerbrew.

**Comment by LoneStarMac** [comment]
In pretty sure it's tiger brew, how can I tell? Of its homebrew, how can I
switch over?

**Comment by dcwar** [comment]
If you try 'brew config', for the ORIGIN, Tigerbrew returns "https://github.com/mistydemeo/tigerbrew.git".

**Comment by LoneStarMac** [comment]
I wiped out my installation and re-started from scratch, thinking something I did along the way caused this mess. Unfortunately I wiped out my install before I saw your post, @dcwar .

Interestingly enough, my clean Tigerbrew install returns ` ORIGIN: (none)`, yet almost everything builds just fine on it.

I guess we chalk his one up to a mess on my machine, not an issue with the code.

**Comment by mistydemeo** [comment]
> Interestingly enough, my clean Tigerbrew install returns ORIGIN: (none), yet almost everything builds just fine on it.

This just means that you'd never run `brew update`, so there was no information available as to what revision you were running.

There was a window of time in which OpenSSL used an sha256 hash due to an oversight on my part when merging changes; it's possible you had installed Tigerbrew in that window. Sorry for the inconvenience! Glad you're okay now though.
