### ISSUE TITLE
Xcode version detection on TigerPPC just broke, and it breaks other stuff

### ISSUE THREAD

**Issue by chdiza** [mistydemeo/tigerbrew#308]
Sometime within the last week, Xcode version detection broke on Tiger PPC and now the symptoms are really bad.

First, to show that it's broken, `brew irb` followed by `puts MacOS::Xcode.version` gives `dunno`.

Now for the symptoms.  I'm suddenly seeing the following from `brew doctor` on Tiger PPC:
````
Warning: You have leftover files from an older version of Xcode.
You should delete them using:
  /Developer/Library/uninstall-developer-folder
````
I have no such leftover files, and /Developer is the proper place for XCode 2.5.

`doctor` is also telling me that I need to link `libtool`, but `libtool` is keg-only on Tiger.

I am getting the following mysterious output when trying to brew a custom formula.  Everything looks like it's going to plan, the software builds, and then right at the make-install step, this happens:

````
Error: No such file or directory - /usr/sbin/pkgutil
/usr/local/Library/Homebrew/utils/popen.rb:20:in `exec'
/usr/local/Library/Homebrew/utils/popen.rb:20:in `popen'
/usr/local/Library/Homebrew/utils/popen.rb:11:in `popen'
/usr/local/Library/Homebrew/utils/popen.rb:11:in `popen'
/usr/local/Library/Homebrew/utils/popen.rb:3:in `popen_read'
/usr/local/Library/Homebrew/os/mac.rb:257:in `pkgutil_info'
/usr/local/Library/Homebrew/os/mac.rb:256:in `fetch'
/usr/local/Library/Homebrew/os/mac.rb:256:in `pkgutil_info'
/usr/local/Library/Homebrew/os/mac/xcode.rb:205:in `detect_version'
/usr/local/Library/Homebrew/os/mac/xcode.rb:201:in `find'
/usr/local/Library/Homebrew/os/mac/xcode.rb:201:in `each'
/usr/local/Library/Homebrew/os/mac/xcode.rb:201:in `find'
/usr/local/Library/Homebrew/os/mac/xcode.rb:201:in `detect_version'
/usr/local/Library/Homebrew/os/mac/xcode.rb:166:in `installed?'
/usr/local/Library/Homebrew/os/mac/xcode.rb:33:in `without_clt?'
/usr/local/Library/Homebrew/extend/ENV/std.rb:66:in `setup_build_environment'
/usr/local/Library/Homebrew/extend/ENV.rb:23:in `with_build_environment'
/usr/local/Library/Homebrew/requirement.rb:172:in `yielder'
/usr/local/Library/Homebrew/requirement.rb:52:in `satisfied?'
/usr/local/Library/Homebrew/build.rb:58:in `expand_reqs'
/usr/local/Library/Homebrew/build.rb:52:in `prune?'
/usr/local/Library/Homebrew/requirement.rb:205:in `catch'
/usr/local/Library/Homebrew/requirement.rb:205:in `prune?'
/usr/local/Library/Homebrew/requirement.rb:193:in `expand'
/usr/local/Library/Homebrew/requirement.rb:192:in `each'
/usr/lib/ruby/1.8/set.rb:189:in `each_key'
/usr/lib/ruby/1.8/set.rb:189:in `each'
/usr/local/Library/Homebrew/dependencies.rb:68:in `each'
/usr/local/Library/Homebrew/requirement.rb:192:in `expand'
/usr/local/Library/Homebrew/requirement.rb:191:in `each'
/usr/local/Library/Homebrew/requirement.rb:191:in `expand'
/usr/local/Library/Homebrew/formula.rb:571:in `recursive_requirements'
/usr/local/Library/Homebrew/build.rb:52:in `expand_reqs'
/usr/local/Library/Homebrew/build.rb:26:in `initialize'
/usr/local/Library/Homebrew/build.rb:184:in `new'
/usr/local/Library/Homebrew/build.rb:184
Kernel.exit
````
And no keg gets installed.

A grep for `pkgutil` seems to indicate that it's getting called because Tigerbrew seems to believe Xcode is >= than 3.0.

As for what happened to break Xcode version detection, I have no idea; but not more than a week ago (two, tops), I was able to brew lots of things here on Tiger PPC.

**Comment by chdiza** [comment]
I'm trying to find the commit that caused this; none of them look, from their descriptions, like they could be the cause.

But these symptoms started today, and all I did was `brew up`!

I tried cloning the repo afresh, just in case something got corrupted here, but no dice.

**Comment by chdiza** [comment]
I'm now having hard drive problems.  It might all be due to a dying drive.  I'll check back in once that situation is fixed.

**Comment by chdiza** [comment]
I'm going to close this for the time being, as I had to wipe my drive and install Tiger from scratch.

**Comment by chdiza** [comment]
It seems this was a hard drive problem.  Sorry for the noise.

**Comment by mistydemeo** [comment]
No worries! Sorry for your hard drive. :(
