### ISSUE TITLE
mktmpdir is missing on Ruby 1.8.6

### ISSUE THREAD

**Issue by mimato** [mistydemeo/tigerbrew#313]
I'm attempting to do a brew install git on my system, and getting an error that Dir.mktmpdir is an undefined method. 

Output: 
==> Installing dependencies for git: xz, pkg-config, makedepend, openssl, curl-ca-bundle, curl
==> Installing git dependency: xz
==> Downloading https://fossies.org/linux/misc/xz-5.2.1.tar.gz
Already downloaded: /Library/Caches/Homebrew/xz-5.2.1.tar.gz
Error: undefined method `mktmpdir' for Dir:Class
Please report this bug:
    https://github.com/mistydemeo/tigerbrew/wiki/troubleshooting
/usr/local/Library/Homebrew/extend/fileutils.rb:11:in `mktemp'
/usr/local/Library/Homebrew/resource.rb:88:in `unpack'
/usr/local/Library/Homebrew/resource.rb:81:in `stage'
/usr/local/Library/Homebrew/formula.rb:775:in `stage'
/usr/local/Library/Homebrew/formula.rb:406:in `brew'
/usr/local/Library/Homebrew/build.rb:114:in `install'
/usr/local/Library/Homebrew/build.rb:186

In investigating, it looks like the system Ruby on 10.5 (1.8.6-369) doesn't include this method on Dir. I guess maybe it needs to be monkeypatched in like it is for 1.8.2 on 10.4?

brew --config output:

HOMEBREW_VERSION: 0.9.5
ORIGIN: (none)
HEAD: (none)
Last commit: never
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: single-core 64-bit g5
OS X: 10.5.8-Power Macintosh
Xcode: 3.1.4
CLT: N/A
GCC-4.0: build 5493
GCC-4.2: build 5577
LLVM-GCC: build 2064
Clang: N/A
X11: 2.1.6 => /usr/X11
System Ruby: 1.8.6-369
Perl: /usr/bin/perl
Python: /usr/bin/python => /System/Library/Frameworks/Python.framework/Versions/2.5/bin/python2.5
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/bin/ruby
Java: 1.5.0_30

**Comment by mistydemeo** [comment]
Good catch, thank you! I'll move the monkeypatch into a place that gets loaded on Leopard too.

**Comment by chdiza** [comment]
This is causing the brewing of `curl` to fail on Leo PPC too.

**Comment by chdiza** [comment]
I think it's actually causing everything to fail on Leo PPC.  I can't brew `ruby` either, because of the same error.

**Comment by galgot** [comment]
I have the same exact problem :

 Eldon-Tyrell:~ galgot$ brew install git
==> Installing dependencies for git: xz, pkg-config, makedepend, openssl, curl-ca-bundle, curl
==> Installing git dependency: xz
==> Downloading https://fossies.org/linux/misc/xz-5.2.1.tar.gz
Already downloaded: /Library/Caches/Homebrew/xz-5.2.1.tar.gz
Error: undefined method `mktmpdir' for Dir:Class
Please report this bug:
    https://github.com/mistydemeo/tigerbrew/wiki/troubleshooting
/usr/local/Library/Homebrew/extend/fileutils.rb:11:in `mktemp'
/usr/local/Library/Homebrew/resource.rb:88:in `unpack'
/usr/local/Library/Homebrew/resource.rb:81:in `stage'
/usr/local/Library/Homebrew/formula.rb:775:in `stage'
/usr/local/Library/Homebrew/formula.rb:406:in `brew'
/usr/local/Library/Homebrew/build.rb:114:in `install'
/usr/local/Library/Homebrew/build.rb:186
Eldon-Tyrell:~ galgot$

Is there a way to fix that ? Please.

**Comment by mistydemeo** [comment]
Sorry about the delays - this should be fixed now.

**Comment by galgot** [comment]
Hi Mistydemeo, thanks.
Now after installing TigerBrew, I have this :
David-Locke:~ galgot$ brew doctor
/usr/local/Library/Homebrew/extend/dir.rb:1: Dir is not a module (TypeError)
	from /usr/local/Library/Homebrew/global.rb:2:in `require'
	from /usr/local/Library/Homebrew/global.rb:2
	from /usr/local/Library/brew.rb:16:in `require'
	from /usr/local/Library/brew.rb:16

I get this with any commands, brew update or brew install git...

Any ideas ?

**Comment by mistydemeo** [comment]
And this is why I should test before pushing :sweat_smile: Fixed

**Comment by mistydemeo** [comment]
If you can't run `brew update`, you can do this:

```
cd /usr/local
git pull origin master
```

**Comment by galgot** [comment]
Mmm, now get this when I brew install git :
David-Locke:Documents galgot$ brew install git
==> Installing dependencies for git: xz, pkg-config, makedepend, openssl, curl-ca-bundle, curl
==> Installing git dependency: xz
==> Downloading https://fossies.org/linux/misc/xz-5.2.1.tar.gz
Already downloaded: /Library/Caches/Homebrew/xz-5.2.1.tar.gz
==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/xz/5.2.1
==> make install
	from /usr/local/Library/ENV/3.1.4/gcc-4.2:320
make[3]: *** [liblzma_la-tuklib_physmem.lo] Error 1
make[2]: *** [install-recursive] Error 1
make[1]: *** [install-recursive] Error 1
make: *** [install-recursive] Error 1

Note , I try on two machines running 10.5.8 Leo. On one it's a fresh OS, XTools and Tigerbrew install.
I get same result on both.
Anyway... will go to sleep now ;) cheers

**Comment by mistydemeo** [comment]
Hmmm, now this looks unrelated. Can you provide the logs from `~/Library/Logs/Homebrew/xz`?

**Comment by galgot** [comment]
![xz zip](https://cloud.githubusercontent.com/assets/12213521/7447199/5fd802aa-f1f2-11e4-9b74-f5aa18923f62.png)
Here. Save link as "xz.zip". It's the content of ~/Library/Logs/Homebrew/xz .

**Comment by mistydemeo** [comment]
Aha, looks like the `cc` script in use in superenv uses a method Ruby 1.8.6 doesn't have:

```
/usr/local/Library/ENV/3.1.4/gcc-4.2:189:in `keep?': undefined method `start_with?' for #<String:0x78f14> (NoMethodError)
```

**Comment by mistydemeo** [comment]
Should be fixed, can you retry?

**Comment by galgot** [comment]
Ok , Git install worked on both machines this time. It's brew updating right now, working ok.
Many thanks for this "live" fixing :)
Cheers

**Comment by mistydemeo** [comment]
Great!
