### ISSUE TITLE
Brew / OpenSSL upgrade issue (10.4/G4)

### ISSUE THREAD

**Issue by dcwar** [mistydemeo/tigerbrew#314]
Thanks for the latest set of package upgrades!! I just updated today and....

It seems that brew can not directly install the latest version of OpenSSL (1.0.2a-1). When trying to upgrade OpenSSL to 1.0.2a-1 from 1.0.2, brew will report that 1.0.2 is already installed. However, formulae for other packages (like curl) will gladly install 1.0.2a-1.

I'm not sure why this is doing this, but it definitely doesn't seem like normal behavior.

Console output:
https://gist.github.com/dcwar/ca82afa53a4cbf3f99bd

**Comment by mistydemeo** [comment]
I think this *may* have been fixed by a4a5acefc74ab4c8f13a8c14f6316ec781101fce. There was a misdetection due to the `a` in the name - Tigerbrew incorrectly thinks it's an alpha and considers it older than "1.0.2".

**Comment by dcwar** [comment]
Thank you!! I will keep an eye out just in case on future packages.
