### ISSUE TITLE
gobject-introspection 1.44 does not build (10.4/G4)

### ISSUE THREAD

**Issue by dcwar** [mistydemeo/tigerbrew#315]
gobject-introspection build fails after make is invoked with the following error:
"Makefile:3408: *** Need to define GLib_2_0_gir_LIBS or GLib_2_0_gir_PROGRAM.  Stop."

Googling turned up this MacPorts ticket - do you suspect it may be related?
https://trac.macports.org/ticket/32358 

01 Configure
https://gist.github.com/dcwar/e6bad801f3fb2c3f2b1d
02 Make
https://gist.github.com/dcwar/491a8c0e8cd463f88957
03 Config.log
https://gist.github.com/dcwar/401cc13aaf42d4d877a9

**Comment by mistydemeo** [comment]
Fixed, thanks for the report!

**Comment by dcwar** [comment]
Thank you!!
