### ISSUE TITLE
ruby is unbrewable on PPC

### ISSUE THREAD

**Issue by chdiza** [mistydemeo/tigerbrew#318]
Ruby 2.2.1 and 2.2.2 refuse to brew on TigerPPC.  It doens't make a difference whether I use stdenv or superenv, or whether I use the official formula or a custom one.

No matter what, I get this:
```
compiling newline.c
compiling ./missing/setproctitle.c
compiling ./missing/alloca.c
compiling dmyext.c
compiling dmyenc.c
linking miniruby
/usr/bin/ld: Undefined symbols:
_fgetattrlist
collect2: ld returned 1 exit status
make: *** [miniruby] Error 1
^C/usr/local/Library/Homebrew/utils/popen.rb:16:in `read'
````
Occasionally the error message is ever so slightly different, e.g., if I try adding a `depends_on "ld64"`, but it's the same thing: `ld` can't find some symbols.[1]

Ruby 2.2.0 has no such problem.

[1] If I add an ld64 dep, I get this:
```
compiling newline.c
compiling ./missing/setproctitle.c
compiling ./missing/alloca.c
compiling dmyext.c
compiling dmyenc.c
linking miniruby
Undefined symbols:
  "_fgetattrlist", referenced from:
      _dir_each in dir.o
      _glob_helper in dir.o
ld: symbol(s) not found
collect2: ld returned 1 exit status
make: *** [miniruby] Error 1
```

**Comment by chdiza** [comment]
I changed the issue title because I just confirmed the same error on LeoPPC.

**Comment by dcwar** [comment]
Have the same issue with ruby 2.2.1 on 10.4/G4

**Comment by mistydemeo** [comment]
Looks like this issue: https://bugs.ruby-lang.org/issues/11054

The `fgetattrlist` function was first introduced in OS X 10.6. Seems there's a patch for this in that issue though!

**Comment by mistydemeo** [comment]
Here's the specific revision that fixed it: http://svn.ruby-lang.org/cgi-bin/viewvc.cgi?view=revision&revision=50218

**Comment by chdiza** [comment]
I'll test this when I get a chance.  Thanks @mistydemeo for digging up the solution.

**Comment by chdiza** [comment]
I cherry picked the patches from the cited commit and put them into the formula, and also bumped it to ruby 2.2.2.

**Comment by chdiza** [comment]
These exact symtpoms have returned on Ruby 2.3, which I tried to build on Tiger PPC last night. :(
