### ISSUE TITLE
icu4c fails to install OSX Server 10.4.11

### ISSUE THREAD

**Issue by roadtechy** [mistydemeo/tigerbrew#325]
Hello,

Here is the error I receive along with system info:

/usr/local/bin/g++-4.2 -Os  -pipe -mcpu=7400 -faltivec -mmacosx-version-min=10.4 -W -Wall -pedantic -Wpointer-arith -Wwrite-strings -Wno-long-long   -L/usr/local/opt/ld64/lib -L/usr/local/lib -F/usr/local/Frameworks -Wl,-headerpad_max_install_names -B/usr/local/Cellar/ld64/97.17/bin/  -o ../../bin/uconv uconv.o uwmsg.o -L../../lib -licui18n -L../../lib -licuuc -L../../stubdata -licudata -lpthread -lm   uconvmsg/libuconvmsg.a
powerpc-apple-darwin8-g++-4.2.1: uconvmsg/libuconvmsg.a: No such file or directory
make[2]: **\* [../../bin/uconv] Error 1
make[1]: **\* [all-recursive] Error 2
make: **\* [all-recursive] Error 2
shell-init: could not get current directory: getcwd: cannot access parent directories: No such file or directory
Error: No such file or directory - /usr/sbin/pkgutil

brew config
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/mistydemeo/tigerbrew.git
HEAD: 20108d4c8f3b410a6dbebf9ec0fffd4f4dbf4de9
Last commit: 17 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: single-core 32-bit g4
OS X: 10.4.11-Power Macintosh
Xcode: 2.5
CLT: N/A
GCC-4.0: build 5370
GCC-4.2: build 5553
Clang: N/A
X11: N/A
System Ruby: 1.8.2 => /usr/bin/ruby
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby
Java: N/A

brew --env
CC: /usr/local/bin/gcc-4.2 => /usr/local/Cellar/apple-gcc42/4.2.1-5553/bin/gcc-4.2
CXX: /usr/local/bin/g++-4.2 => /usr/local/Cellar/apple-gcc42/4.2.1-5553/bin/g++-4.2
OBJC: /usr/local/bin/gcc-4.2
OBJCXX: /usr/local/bin/g++-4.2
CFLAGS: -Os -w -pipe -mcpu=7400 -faltivec -mmacosx-version-min=10.4
CXXFLAGS: -Os -w -pipe -mcpu=7400 -faltivec -mmacosx-version-min=10.4
CPPFLAGS: -F/usr/local/Frameworks
LDFLAGS: -L/usr/local/lib -F/usr/local/Frameworks -Wl,-headerpad_max_install_names
MAKEFLAGS: -j1
CMAKE_FRAMEWORK_PATH: /usr/local/Frameworks
MACOSX_DEPLOYMENT_TARGET: 10.4
PKG_CONFIG_LIBDIR: /usr/local/lib/pkgconfig:/usr/local/Library/ENV/pkgconfig/10.4:/usr/lib/pkgconfig
PATH: /usr/local/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/Library/ENV/scm
CPATH: /usr/local/include

brew doctor
Your system is ready to brew.

Thanks,
Cevin

**Comment by mistydemeo** [comment]
Could you provide the full set of logs from `~/Library/Logs/Homebrew/icu4c`? Thanks!

**Comment by roadtechy** [comment]
Hello,

It appears Brew is not logging.  I have searched the machine and found no logs in other locations either.

Thanks,
Cevin

**Comment by roadtechy** [comment]
This install was attempted around 2:00 am PDT today.

**Comment by roadtechy** [comment]
Found it

Sat May 02 11:03:54 PDT 2015

./configure
--prefix=/usr/local/Cellar/icu4c/55.1
--disable-samples
--disable-tests
--enable-static

checking for ICU version numbers... release 55.1, library 55.1, unicode version 7.0
checking build system type... powerpc-apple-darwin8.11.0
checking host system type... powerpc-apple-darwin8.11.0
checking whether to build debug libraries... no
checking whether to build release libraries... yes
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether /usr/local/bin/gcc-4.2 accepts -g... yes
checking for /usr/local/bin/gcc-4.2 option to accept ISO C89... none needed
checking whether we are using the GNU C++ compiler... yes
checking whether /usr/local/bin/g++-4.2 accepts -g... yes
checking for pkg-config... /usr/local/bin/pkg-config
checking pkg-config is at least version 0.20... yes
checking for ICULEHB... no
checking how to run the C preprocessor... /usr/local/bin/gcc-4.2 -E
checking for a BSD-compatible install... /usr/bin/install -c
checking for gmake... no
checking for gnumake... /usr/bin/gnumake
checking for doxygen... no
checking checking for executable suffix... 
checking whether strict compiling is on... yes
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking size of void *... 4
checking whether runnable 64 bit binaries are built by default... no
checking which Makefile fragment to use for powerpc-apple-darwin8.11.0... mh-darwin
checking for floor in -lm... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking whether to enable auto cleanup of libraries... no
checking whether to enable draft APIs... yes
checking for ranlib... ranlib
checking for ar... ar
checking whether to enable renaming of symbols... yes
checking whether to enable function and data tracing... no
checking elf.h usability... no
checking elf.h presence... no
checking for elf.h... no
checking whether to enable dynamic loading of plugins... yes
checking dlfcn.h usability... yes
checking dlfcn.h presence... yes
checking for dlfcn.h... yes
checking for library containing dlopen... none required
checking for dlopen... yes
checking for gettimeofday... yes
checking if we have a C++ compiler... Good
checking if we have a C++11 compiler... no
checking if #include <string> works... yes
checking if #include <atomic> works... no
checking for pthread_attr_init in -lpthread... yes
checking for mmap... yes
checking for genccode assembly... 
checking for inttypes.h... (cached) yes
checking dirent.h usability... yes
checking dirent.h presence... yes
checking for dirent.h... yes
checking whether byte ordering is bigendian... yes
checking for nl_langinfo... yes
checking for nl_langinfo's argument to obtain the codeset... CODESET
checking for namespace support... yes
checking for properly overriding new and delete... yes
checking for placement new and delete... yes
checking for popen... yes
checking for tzset... yes
checking for tzname... yes
checking for timezone... no
checking for __timezone... no
checking for _timezone... no
checking for int8_t... yes
checking for uint8_t... yes
checking for int16_t... yes
checking for uint16_t... yes
checking for int32_t... yes
checking for uint32_t... yes
checking for int64_t... yes
checking for uint64_t... yes
checking wchar.h usability... yes
checking wchar.h presence... yes
checking for wchar.h... yes
checking for library containing wcscpy... none required
checking size of wchar_t... 4
checking for UTF-16 string literal support... unknown
checking for a library suffix to use... none
CPPFLAGS=-I/usr/local/opt/ld64/include -F/usr/local/Frameworks $(THREADSCPPFLAGS)  -DU_HAVE_ATOMIC=0 -DU_HAVE_TIMEZONE=0 
CFLAGS=-Os  -pipe -mcpu=7400 -faltivec -mmacosx-version-min=10.4 -std=c99 -Wall -pedantic -Wshadow -Wpointer-arith -Wmissing-prototypes -Wwrite-strings $(THREADSCFLAGS) 
CXXFLAGS=-Os  -pipe -mcpu=7400 -faltivec -mmacosx-version-min=10.4 -W -Wall -pedantic -Wpointer-arith -Wwrite-strings -Wno-long-long $(THREADSCXXFLAGS) 
configure: creating ./config.status
config.status: creating icudefs.mk
config.status: creating Makefile
config.status: creating data/pkgdataMakefile
config.status: creating config/Makefile.inc
config.status: creating config/icu.pc
config.status: creating config/pkgdataMakefile
config.status: creating data/Makefile
config.status: creating stubdata/Makefile
config.status: creating common/Makefile
config.status: creating i18n/Makefile
config.status: creating layout/Makefile
config.status: creating layoutex/Makefile
config.status: creating io/Makefile
config.status: creating extra/Makefile
config.status: creating extra/uconv/Makefile
config.status: creating extra/uconv/pkgdataMakefile
config.status: creating extra/scrptrun/Makefile
config.status: creating tools/Makefile
config.status: creating tools/ctestfw/Makefile
config.status: creating tools/toolutil/Makefile
config.status: creating tools/makeconv/Makefile
config.status: creating tools/genrb/Makefile
config.status: creating tools/genccode/Makefile
config.status: creating tools/gencmn/Makefile
config.status: creating tools/gencnval/Makefile
config.status: creating tools/gendict/Makefile
config.status: creating tools/gentest/Makefile
config.status: creating tools/gennorm2/Makefile
config.status: creating tools/genbrk/Makefile
config.status: creating tools/gensprep/Makefile
config.status: creating tools/icuinfo/Makefile
config.status: creating tools/icupkg/Makefile
config.status: creating tools/icuswap/Makefile
config.status: creating tools/pkgdata/Makefile
config.status: creating tools/tzcode/Makefile
config.status: creating tools/gencfu/Makefile
config.status: creating test/Makefile
config.status: creating test/compat/Makefile
config.status: creating test/testdata/Makefile
config.status: creating test/testdata/pkgdataMakefile
config.status: creating test/hdrtst/Makefile
config.status: creating test/intltest/Makefile
config.status: creating test/cintltst/Makefile
config.status: creating test/iotest/Makefile
config.status: creating test/letest/Makefile
config.status: creating test/perf/Makefile
config.status: creating test/perf/collationperf/Makefile
config.status: creating test/perf/collperf/Makefile
config.status: creating test/perf/collperf2/Makefile
config.status: creating test/perf/dicttrieperf/Makefile
config.status: creating test/perf/ubrkperf/Makefile
config.status: creating test/perf/charperf/Makefile
config.status: creating test/perf/convperf/Makefile
config.status: creating test/perf/normperf/Makefile
config.status: creating test/perf/DateFmtPerf/Makefile
config.status: creating test/perf/howExpensiveIs/Makefile
config.status: creating test/perf/strsrchperf/Makefile
config.status: creating test/perf/unisetperf/Makefile
config.status: creating test/perf/usetperf/Makefile
config.status: creating test/perf/ustrperf/Makefile
config.status: creating test/perf/utfperf/Makefile
config.status: creating test/perf/utrie2perf/Makefile
config.status: creating test/perf/leperf/Makefile
config.status: creating samples/Makefile
config.status: creating samples/date/Makefile
config.status: creating samples/cal/Makefile
config.status: creating samples/layout/Makefile

ICU for C/C++ 55.1 is ready to be built.
=== Important Notes: ===
Data Packaging: library
 This means: ICU data will be linked with ICU. A static data library will be built.  A shared data library will be built. 
 To locate data: ICU will use the linked data library. If linked with the stub library located in stubdata/, the application can use udata_setCommonData() or set a data path to override.
Building ICU: Use a GNU make such as /usr/bin/gnumake to build ICU.
checking the version of "/usr/bin/gnumake"... 3.80 (we wanted at least 3.80)
ok




Sat May 02 11:03:54 PDT 2015

./configure
--prefix=/usr/local/Cellar/icu4c/55.1
--disable-samples
--disable-tests
--enable-static

checking for ICU version numbers... release 55.1, library 55.1, unicode version 7.0
checking build system type... powerpc-apple-darwin8.11.0
checking host system type... powerpc-apple-darwin8.11.0
checking whether to build debug libraries... no
checking whether to build release libraries... yes
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether /usr/local/bin/gcc-4.2 accepts -g... yes
checking for /usr/local/bin/gcc-4.2 option to accept ISO C89... none needed
checking whether we are using the GNU C++ compiler... yes
checking whether /usr/local/bin/g++-4.2 accepts -g... yes
checking for pkg-config... /usr/local/bin/pkg-config
checking pkg-config is at least version 0.20... yes
checking for ICULEHB... no
checking how to run the C preprocessor... /usr/local/bin/gcc-4.2 -E
checking for a BSD-compatible install... /usr/bin/install -c
checking for gmake... no
checking for gnumake... /usr/bin/gnumake
checking for doxygen... no
checking checking for executable suffix... 
checking whether strict compiling is on... yes
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking size of void *... 4
checking whether runnable 64 bit binaries are built by default... no
checking which Makefile fragment to use for powerpc-apple-darwin8.11.0... mh-darwin
checking for floor in -lm... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking whether to enable auto cleanup of libraries... no
checking whether to enable draft APIs... yes
checking for ranlib... ranlib
checking for ar... ar
checking whether to enable renaming of symbols... yes
checking whether to enable function and data tracing... no
checking elf.h usability... no
checking elf.h presence... no
checking for elf.h... no
checking whether to enable dynamic loading of plugins... yes
checking dlfcn.h usability... yes
checking dlfcn.h presence... yes
checking for dlfcn.h... yes
checking for library containing dlopen... none required
checking for dlopen... yes
checking for gettimeofday... yes
checking if we have a C++ compiler... Good
checking if we have a C++11 compiler... no
checking if #include <string> works... yes
checking if #include <atomic> works... no
checking for pthread_attr_init in -lpthread... yes
checking for mmap... yes
checking for genccode assembly... 
checking for inttypes.h... (cached) yes
checking dirent.h usability... yes
checking dirent.h presence... yes
checking for dirent.h... yes
checking whether byte ordering is bigendian... yes
checking for nl_langinfo... yes
checking for nl_langinfo's argument to obtain the codeset... CODESET
checking for namespace support... yes
checking for properly overriding new and delete... yes
checking for placement new and delete... yes
checking for popen... yes
checking for tzset... yes
checking for tzname... yes
checking for timezone... no
checking for __timezone... no
checking for _timezone... no
checking for int8_t... yes
checking for uint8_t... yes
checking for int16_t... yes
checking for uint16_t... yes
checking for int32_t... yes
checking for uint32_t... yes
checking for int64_t... yes
checking for uint64_t... yes
checking wchar.h usability... yes
checking wchar.h presence... yes
checking for wchar.h... yes
checking for library containing wcscpy... none required
checking size of wchar_t... 4
checking for UTF-16 string literal support... unknown
checking for a library suffix to use... none
CPPFLAGS=-I/usr/local/opt/ld64/include -F/usr/local/Frameworks $(THREADSCPPFLAGS)  -DU_HAVE_ATOMIC=0 -DU_HAVE_TIMEZONE=0 
CFLAGS=-Os  -pipe -mcpu=7400 -faltivec -mmacosx-version-min=10.4 -std=c99 -Wall -pedantic -Wshadow -Wpointer-arith -Wmissing-prototypes -Wwrite-strings $(THREADSCFLAGS) 
CXXFLAGS=-Os  -pipe -mcpu=7400 -faltivec -mmacosx-version-min=10.4 -W -Wall -pedantic -Wpointer-arith -Wwrite-strings -Wno-long-long $(THREADSCXXFLAGS) 
configure: creating ./config.status
config.status: creating icudefs.mk
config.status: creating Makefile
config.status: creating data/pkgdataMakefile
config.status: creating config/Makefile.inc
config.status: creating config/icu.pc
config.status: creating config/pkgdataMakefile
config.status: creating data/Makefile
config.status: creating stubdata/Makefile
config.status: creating common/Makefile
config.status: creating i18n/Makefile
config.status: creating layout/Makefile
config.status: creating layoutex/Makefile
config.status: creating io/Makefile
config.status: creating extra/Makefile
config.status: creating extra/uconv/Makefile
config.status: creating extra/uconv/pkgdataMakefile
config.status: creating extra/scrptrun/Makefile
config.status: creating tools/Makefile
config.status: creating tools/ctestfw/Makefile
config.status: creating tools/toolutil/Makefile
config.status: creating tools/makeconv/Makefile
config.status: creating tools/genrb/Makefile
config.status: creating tools/genccode/Makefile
config.status: creating tools/gencmn/Makefile
config.status: creating tools/gencnval/Makefile
config.status: creating tools/gendict/Makefile
config.status: creating tools/gentest/Makefile
config.status: creating tools/gennorm2/Makefile
config.status: creating tools/genbrk/Makefile
config.status: creating tools/gensprep/Makefile
config.status: creating tools/icuinfo/Makefile
config.status: creating tools/icupkg/Makefile
config.status: creating tools/icuswap/Makefile
config.status: creating tools/pkgdata/Makefile
config.status: creating tools/tzcode/Makefile
config.status: creating tools/gencfu/Makefile
config.status: creating test/Makefile
config.status: creating test/compat/Makefile
config.status: creating test/testdata/Makefile
config.status: creating test/testdata/pkgdataMakefile
config.status: creating test/hdrtst/Makefile
config.status: creating test/intltest/Makefile
config.status: creating test/cintltst/Makefile
config.status: creating test/iotest/Makefile
config.status: creating test/letest/Makefile
config.status: creating test/perf/Makefile
config.status: creating test/perf/collationperf/Makefile
config.status: creating test/perf/collperf/Makefile
config.status: creating test/perf/collperf2/Makefile
config.status: creating test/perf/dicttrieperf/Makefile
config.status: creating test/perf/ubrkperf/Makefile
config.status: creating test/perf/charperf/Makefile
config.status: creating test/perf/convperf/Makefile
config.status: creating test/perf/normperf/Makefile
config.status: creating test/perf/DateFmtPerf/Makefile
config.status: creating test/perf/howExpensiveIs/Makefile
config.status: creating test/perf/strsrchperf/Makefile
config.status: creating test/perf/unisetperf/Makefile
config.status: creating test/perf/usetperf/Makefile
config.status: creating test/perf/ustrperf/Makefile
config.status: creating test/perf/utfperf/Makefile
config.status: creating test/perf/utrie2perf/Makefile
config.status: creating test/perf/leperf/Makefile
config.status: creating samples/Makefile
config.status: creating samples/date/Makefile
config.status: creating samples/cal/Makefile
config.status: creating samples/layout/Makefile

ICU for C/C++ 55.1 is ready to be built.
=== Important Notes: ===
Data Packaging: library
 This means: ICU data will be linked with ICU. A static data library will be built.  A shared data library will be built. 
 To locate data: ICU will use the linked data library. If linked with the stub library located in stubdata/, the application can use udata_setCommonData() or set a data path to override.
Building ICU: Use a GNU make such as /usr/bin/gnumake to build ICU.
checking the version of "/usr/bin/gnumake"... 3.80 (we wanted at least 3.80)
ok

**Comment by mistydemeo** [comment]
I'm giving this a shot on the desktop version of 10.4.11 to see if I can repro.

**Comment by mistydemeo** [comment]
It's failing on some ASM:

```
Error creating with assembly code. Failed command:
Error generating assembly code for data.
pkgdata: /usr/local/bin/gcc-4.2 -DU_ATTRIBUTE_DEPRECATED= -I/usr/local/opt/cctools/include -I/usr/local/opt/ld64/include -F/usr/local/Frameworks   -DU_HAVE_ATOMIC=0 -DU_HAVE_TIMEZONE=0  -Os  -pipe -mcpu=7400 -faltivec -mmacosx-version-min=10.4 -std=c99 -Wall -pedantic -Wshadow -Wpointer-arith -Wmissing-prototypes -Wwrite-strings   -fno-common -c -I../common -I../common  -dynamic -o ./out/tmp/icudt55b_dat.o ./out/tmp/icudt55b_dat.S
DYLD_LIBRARY_PATH=../stubdata:../tools/ctestfw:../lib:$DYLD_LIBRARY_PATH  ../bin/pkgdata -O ../data/icupkg.inc -q -c -s /private/tmp/icu4c20150505-7656-1hwub8e/icu/source/data/out/build/icudt55b -d ../lib -e icudt55  -T ./out/tmp -p icudt55b -m dll -r 55.1 -L icudata ./out/tmp/icudata.lst
./out/tmp/icudt55b_dat.S:7:Unknown pseudo-op: .balign
./out/tmp/icudt55b_dat.S:7:Rest of line ignored. 1st junk character valued 49 (1).
```

**Comment by mistydemeo** [comment]
icu4c does build on Leopard, so PPC shouldn't be a problem.

**Comment by kde35** [comment]
I confirm this on my ibook G3 ppc running MacOS 10.4.11

**Comment by bigc80** [comment]
Confirm. 10.4.11, G5. So I cannot build mpd
