### ISSUE TITLE
Caskroom/cask/xquartz failed to compile on 10.5

### ISSUE THREAD

**Issue by mfrasca** [mistydemeo/tigerbrew#328]
MacBook-140:~ user$ brew install Caskroom/cask/xquartz
    ==> Installing brew-cask from caskroom/homebrew-cask
    ==> Installing brew-cask dependency: ruby
    ==> Downloading http://cache.ruby-lang.org/pub/ruby/2.2/ruby-2.2.2.tar.bz2
    Already downloaded: /Library/Caches/Homebrew/ruby-2.2.2.tar.bz2
    ==> Patching
    patching file dir.c
    Hunk #2 succeeded at 704 (offset -5 lines).
    Hunk #3 succeeded at 1649 (offset -62 lines).
    ==> ./configure --prefix=/usr/local/Cellar/ruby/2.2.2 --enable-shared --disable-silent-rules --with-sitedir=/usr/local/lib/ruby/site_ruby --with-vendordir=/usr/local/lib/
    ==> make
    compiling bignum.c
    cc: installation problem, cannot exec '/usr/local/Library/ENV/3.1.4/i686-apple-darwin9-gcc-4.0.1': No such file or directory
    dtrace: failed to compile script probes.d: Preprocessor failed to process input program
    make: *** [probes.h] Error 1
    make: *** Waiting for unfinished jobs....

my workaround:

    cd /usr/local/Library/ENV/3.1.4/
    sudo ln -s cc i686-apple-darwin9-gcc-4.0.1

**Comment by mistydemeo** [comment]
Fixed, thanks for the report!
