### ISSUE TITLE
Caskroom/cask/xquartz failed to compile on 10.5

### ISSUE THREAD

**Issue by mfrasca** [mistydemeo/tigerbrew#329]
MacBook-140:3.1.4 user$ brew doctor
    Your system is ready to brew.
    MacBook-140:3.1.4 user$ brew install Caskroom/cask/xquartz
    ==> brew cask install Caskroom/cask/xquartz
    ==> Downloading https://xquartz.macosforge.org/downloads/SL/XQuartz-2.7.7.dmg
    Already downloaded: /Library/Caches/Homebrew/xquartz-2.7.7.dmg
    ==> Running installer for xquartz; your password may be necessary.
    ==> Package installers may write to any location; options such as --appdir are ignored.
    ==> usage: sudo [-HPSb] [-p prompt] [-u username|#uid]
    ==>             { -e file [...] | -i | -s | <command> }
    ==> sudo: illegal option `-E'
    ==> usage: sudo -K | -L | -V | -h | -k | -l | -v
    Error: Command failed to execute!
    
    ==> Failed command:
    ["/usr/bin/sudo", "-E", "--", "/usr/sbin/installer", "-pkg", "#<Pathname:/opt/homebrew-cask/Caskroom/xquartz/2.7.7/XQuartz.pkg>", "-target", "/"]
    
    ==> Output of failed command:
    usage: sudo [-HPSb] [-p prompt] [-u username|#uid]
                { -e file [...] | -i | -s | <command> }
    
    
    ==> Exit status of failed command:
    #<Process::Status: pid 41261 exit 1>
    MacBook-140:3.1.4 user$

**Comment by mistydemeo** [comment]
It looks like this is an issue with cask, not Tigerbrew. Cask uses the `-E` argument to `sudo`, but that option doesn't appear to be supported in the version of sudo shipped by OS X 10.5. Could you report this [there](https://github.com/caskroom/homebrew-cask), please? Thanks!
