### ISSUE TITLE
Can't install git on PPC Tiger due to ld64

### ISSUE THREAD

**Issue by morgant** [mistydemeo/tigerbrew#330]
Attempting to install `git` on a 400MHz G3 PowerBook G3 "Pismo" running Mac OS X 10.4.11 Tiger w/Xcode 2.5 installed due to missing `ld64` dependency. It suggests installing `gcc`, but that also fails due to missing `ld64`:

    host:~ user$ brew install git
    ==> Installing dependencies for git: ld64, cctools, expat, makedepend, op
    ==> Installing git dependency: ld64
    Error: ld64 cannot be built with any available compilers.
    To install this formula, you may need to:
      brew install gcc
    host:~ user$ brew install gcc
    ==> Installing dependencies for gcc: ld64, cctools
    ==> Installing gcc dependency: ld64
    Error: ld64 cannot be built with any available compilers.
    To install this formula, you may need to:
      brew install gcc

`PATH` is `/usr/local/bin:/usr/local/sbin:/bin:/sbin:/usr/bin:/usr/sbin`.

**Comment by chdiza** [comment]
Did you try `brew install ld64`?

**Comment by mistydemeo** [comment]
Could you try:

`brew install apple-gcc42`, then `brew install ld64`

**Comment by mistydemeo** [comment]
I should either improve the messaging here, or make `apple-gcc42` a dependency of ld64 so this doesn't happen. Sorry :(

Ideally I should also fix my ability to provide prebuilt G3 binaries...

**Comment by mistydemeo** [comment]
Ping

**Comment by morgant** [comment]
My apologies for the late response. `brew install apple-gcc42` is allowing `ld64` to download and attempt to build under Mac OS X 10.4. I'm running into a bus error while compiling `ld64`, but I'm still investigating and that's a separate issue.

I'd lean toward making `apple-gcc42` a dependency, unless an equivalent is available when a newer version of Xcode is installed under Mac OS X 10.5. If the latter is the case, an improved error message would be sufficient.

**Comment by boudinfl** [comment]
Same issue here with an ibook g3 clamshell under 10.4.11. Solved by installing apple-gcc42.

**Comment by morgant** [comment]
I had missed Issue #207 when I created this issue.

**Comment by mistydemeo** [comment]
Updated the message, thanks!

**Comment by morgant** [comment]
Excellent! Thank you very much!
