### ISSUE TITLE
'brew info homebrew/versions/gcc5' generates error (10.4/G4)

### ISSUE THREAD

**Issue by dcwar** [mistydemeo/tigerbrew#331]
Just updated to 27de50ed, and 'brew info homebrew/versions/gcc5' errors with:
"Error: undefined method `desc' for Formulary::Formulae::Gcc5:Class"

Console output:
https://gist.github.com/dcwar/d27c47623f5ea9489ab4

**Comment by mistydemeo** [comment]
I haven't updated Tigerbrew since a major new feature was added to Homebrew. I'll get updates merged in soon!

**Comment by mistydemeo** [comment]
This should be fixed now. Thanks for the report!

**Comment by dcwar** [comment]
Thank you!
