### ISSUE TITLE
SFML failed to build on 10.5 Intel

### ISSUE THREAD

**Issue by alexey-lysiuk** [mistydemeo/tigerbrew#337]
https://gist.github.com/alexey-lysiuk/5a723ed9ff52e6d4c4b7

SFML 2.3 (and 2.2 too) doesn't support OS X prior to 10.7 Lion.
Version 2.1 should support 10.5 Leopard, but because of #336 I unable to verify this.
10.4 Tiger isn't supported by SFML 2.x at all.

**Comment by mistydemeo** [comment]
Should be fixed; the formula will now build 2.1 on 10.5 and 10.6, and I've confirmed it works on PPC.
