### ISSUE TITLE
imagemagick 6.9.1-5 fails to build (10.4/G4)

### ISSUE THREAD

**Issue by dcwar** [mistydemeo/tigerbrew#341]
With no other errors, using gcc 4.2 or gcc 5, the build fails with the following error at line 1377:

"/usr/bin/ld: Undefined symbols:
_crc32
_zlibVersion
collect2: ld returned 1 exit status
make[1]: *** [coders/png.la] Error 1
make: *** [install] Error 2"

Any ideas?

make log:
https://gist.github.com/dcwar/60b9970e4f3aa391aaee

**Comment by mistydemeo** [comment]
Sorry for the late reply. Should be fixed now! It needed a newer zlib on Tiger and Leopard.

I've also added binary packages for it.

**Comment by dcwar** [comment]
Awesome. Built from source with Success! Thank you!!

**Comment by mistydemeo** [comment]
Good, glad it works!
