### ISSUE TITLE
'Brew install git' stuck on make (iMac g3 OS 10.4.11)

### ISSUE THREAD

**Issue by EX0R0** [mistydemeo/tigerbrew#344]
Hello,
I'm new to homebrew. I was interested in turning my old iMac g3 into a Pandora jukebox by using PianoBar.

I tried installing git and it got stuck on a line that begins like:
    ==> make CC=/usr/local/bin/gcc-4.2.....

After using the 'brew doctor' command, the only error that shows up is that git is not installed.

Your help is greatly appreciated. 

**Update:** It hangs on the same exact step when I type 'brew install gcc' :(

Thanks!

**Comment by mistydemeo** [comment]
How long has it been stuck for? Git takes about ~25 minutes to build on my 2003 G4 Mac; it wouldn't surprise me if it takes closer to 40-60 minutes on an iMac G3.

What does Activity Monitor say about your CPU use? Does it look like it's still doing something?

**Comment by EX0R0** [comment]
Fast response! Awesome! The activity monitor doesn't look that crazy. It's using about 0.10% cpu consistently. Is there a way for me to check if xCode is setup properly? I have xCode 2.5 installed but I'm not sure if I set it up correctly.

**Comment by mistydemeo** [comment]
What's your `brew --config`? If you `tail` the logs in `~/Library/Logs/Homebrew/git`, is anything changing?

**Comment by EX0R0** [comment]
Here's what's coming up:
![da iMac](http://i58.tinypic.com/14kimj5.jpg)


I'm not too sure how to tail the logs.

**Comment by EX0R0** [comment]
I see a few N/A on the list. I'm not sure if those are necessary.

**Comment by mistydemeo** [comment]
Your config looks fine!

How long was it running when you killed the build?

To tail the logs, open a second terminal window and do `tail -f ~/Library/Logs/Homebrew/git/01.make` while it's building. This will print all of the actual build commands it's doing; you can see if it actually stops at any point when it looks like the build has stalled, or if it's actually still doing stuff.

**Comment by EX0R0** [comment]
I was a bit inpatient when I killed it. Probably less than 30 minutes. Plus I think it went into sleep-mode. I'm trying it again with sleep-mode turned off.

That's odd. When I type the tail command it says "no such file or directory". I also see that in my finder the git folder is not in ~/Library/Logs/Homebrew/ .

**Comment by mistydemeo** [comment]
Another option is to `brew install -v git`, which will print the compiler output to the terminal. You usually don't need to do that, but it can be helpful if you want to make sure it's still doing something.

**Comment by EX0R0** [comment]
Looks like it isn't doing anything. I made sure g++ and gcc actually exist. They do.

![Ughh](http://i59.tinypic.com/11mal9j.jpg)

**Comment by mistydemeo** [comment]
Aha, it's actually building the ld64 formula, not git - that's why you couldn't find the logs. It's a dependency of git's.

Can you leave it for ~10-20 minutes and see if anything has changed?

**Comment by EX0R0** [comment]
Just checked it again. It seems to be repeating that one line over-and-over again slowly.

**Comment by mistydemeo** [comment]
Can you take another photo, and/or post the logs inside `~/Library/Logs/Homebrew/ld64`?

**Comment by EX0R0** [comment]
Ok. I would post the logs, but the web-browser is unbearably slow:) 
![Image of Yaktocat](http://i59.tinypic.com/33m5zk8.jpg)

**Comment by mistydemeo** [comment]
It is compiling different files - this is normal. It doesn't look like it's stalled yet! Keep an eye on it and be patient - depending on how fast your iMac is, you could be in for a long haul here.

**Comment by mistydemeo** [comment]
In the long term, I hope to be able to provide prebuilt binaries for G3 Macs. I had to remove the binaries I previously provided because my build process wasn't able to guarantee that my newer Macs were producing compatible binaries; that will hopefully change.

**Comment by EX0R0** [comment]
Thanks so much for the help! I'll come back here if it gets stuck. The mac is 600mhz, so at least its one of the faster G3s. I haven't checked the RAM but I'm pretty sure its 256mb.

**Comment by mistydemeo** [comment]
Good luck! Let me know how it works out!

**Comment by EX0R0** [comment]
It's been stuck on a line for a while. I might have to leave it overnight to see if it changes.
![image](http://i61.tinypic.com/513vpv.jpg)

**Comment by EX0R0** [comment]
Wow.. After all that another error happened. 

This time it says:

    make: *** [src/other/dyldinfo.o] Error 1
    shell-init could not get current directory: getcwd: cannot access parent directories: No such file or directory
    Error: No such file or directory - /usr/sbin/pkgutil

**Comment by mistydemeo** [comment]
Can you get a copy of the logs in `~/Library/Logs/Homebrew/ld64`?

**Comment by EX0R0** [comment]
(don't pay attention to the fact that their dates are set to the 70s. The clock must've got reset or something)

Here's 01.make:
http://txs.io/Zm6b

And here's 02.make
http://txs.io/an6b

**Comment by mistydemeo** [comment]
Can you try fixing your clock, then do this?

```sh
brew rm cctools-headers dyld-headers libunwind-headers
brew install ld64
```

make specifically warned about clock skew in your logs, and a few headers that are supposed to exist are missing; it's making me wonder if fixing the clock and retrying may work.

**Comment by EX0R0** [comment]
YES!! Thanks so much! It's working perfectly. Even pianobar installed perfectly.

**Comment by mistydemeo** [comment]
Fantastic! Glad to hear it. :D Let me know if you have any other problems!

**Comment by EX0R0** [comment]
This might be a dumb question, but the only reason I really found out about Homebrew was because I was looking for a way to play Pandora on my G3. 
I was wondering where I can find more Homebrew tools and applications. After googling around with terms like "best git apps" and "Best homebrew packages", I didn't really find anything.
