### ISSUE TITLE
Can't install node.js

### ISSUE THREAD

**Issue by antelopeb** [mistydemeo/tigerbrew#346]
Ran brew update, brew doctor, and running brew install node results in a failure. Here's the truncated output, as --debug hangs:
==> Downloading https://nodejs.org/dist/v0.12.4/node-v0.12.4.tar.gz
Already downloaded: /Library/Caches/Homebrew/node-0.12.4.tar.gz
==> ./configure --prefix=/usr/local/Cellar/node/0.12.4 --without-npm --without-ssl2 --without-ssl3
                 'v8_random_seed': 0,
                 'v8_use_snapshot': 'true',
                 'want_separate_host_toolset': 0}}
creating  ./config.gypi
creating  ./config.mk
shell-init: could not get current directory: getcwd: cannot access parent directories: No such file or directory
Error: No such file or directory - /usr/sbin/pkgutil

Output from --debug, ending at hang:
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/node.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/pkg-config.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FromPathLoader): loading /usr/local/Library/Formula/node.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/pkg-config.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/python.rb
==> Downloading https://nodejs.org/dist/v0.12.4/node-v0.12.4.tar.gz
Already downloaded: /Library/Caches/Homebrew/node-0.12.4.tar.gz
==> ./configure --prefix=/usr/local/Cellar/node/0.12.4 --without-npm --without-ssl2 --without-ssl3
                 'v8_random_seed': 0,
                 'v8_use_snapshot': 'true',
                 'want_separate_host_toolset': 0}}
creating  ./config.gypi
creating  ./config.mk

Results from ctrl-c interrupt, and choosing "raise":
Error: Broken pipe
/usr/local/Library/Homebrew/utils.rb:282:in `write'
/usr/local/Library/Homebrew/utils.rb:282:in `puts'
/usr/local/Library/Homebrew/utils.rb:282:in `ignore_interrupts'
/usr/local/Library/Homebrew/utils.rb:281:in `call'
/usr/lib/ruby/1.8/fileutils.rb:712:in `remove_dir'
/usr/lib/ruby/1.8/fileutils.rb:702:in `foreach'
/usr/lib/ruby/1.8/fileutils.rb:702:in `remove_dir'
/usr/lib/ruby/1.8/fileutils.rb:708:in `remove_dir'
/usr/lib/ruby/1.8/fileutils.rb:702:in `foreach'
/usr/lib/ruby/1.8/fileutils.rb:702:in `remove_dir'
/usr/lib/ruby/1.8/fileutils.rb:708:in `remove_dir'
/usr/lib/ruby/1.8/fileutils.rb:702:in `foreach'
/usr/lib/ruby/1.8/fileutils.rb:702:in `remove_dir'
/usr/lib/ruby/1.8/fileutils.rb:708:in `remove_dir'
/usr/lib/ruby/1.8/fileutils.rb:702:in `foreach'
/usr/lib/ruby/1.8/fileutils.rb:702:in `remove_dir'
/usr/lib/ruby/1.8/fileutils.rb:708:in `remove_dir'
/usr/lib/ruby/1.8/fileutils.rb:702:in `foreach'
/usr/lib/ruby/1.8/fileutils.rb:702:in `remove_dir'
/usr/lib/ruby/1.8/fileutils.rb:708:in `remove_dir'
/usr/lib/ruby/1.8/fileutils.rb:702:in `foreach'
/usr/lib/ruby/1.8/fileutils.rb:702:in `remove_dir'
/usr/lib/ruby/1.8/fileutils.rb:663:in `rm_r'
/usr/lib/ruby/1.8/fileutils.rb:655:in `each'
/usr/lib/ruby/1.8/fileutils.rb:655:in `rm_r'
/usr/lib/ruby/1.8/fileutils.rb:679:in `rm_rf'
/usr/local/Library/Homebrew/extend/fileutils.rb:22:in `mktemp'
/usr/local/Library/Homebrew/extend/fileutils.rb:22:in `ignore_interrupts'
/usr/local/Library/Homebrew/extend/fileutils.rb:22:in `mktemp'
/usr/local/Library/Homebrew/resource.rb:88:in `unpack'
/usr/local/Library/Homebrew/resource.rb:81:in `stage'
/usr/local/Library/Homebrew/formula.rb:943:in `stage'
/usr/local/Library/Homebrew/formula.rb:536:in `brew'
/usr/local/Library/Homebrew/build.rb:106:in `install'
/usr/local/Library/Homebrew/build.rb:178

Tried to create the Gist, got this error instead:
Error: undefined method `body=' for #<Net::HTTP::Post POST>
Please report this bug:
    https://github.com/mistydemeo/tigerbrew/wiki/troubleshooting
/usr/local/Library/Homebrew/cmd/gist-logs.rb:108:in `make_request'
/usr/local/Library/Homebrew/cmd/gist-logs.rb:113:in `post'
/usr/local/Library/Homebrew/cmd/gist-logs.rb:72:in `create_gist'
/usr/local/Library/Homebrew/cmd/gist-logs.rb:24:in `gistify_logs'
/usr/local/Library/Homebrew/cmd/gist-logs.rb:140:in `gist_logs'
/usr/local/Library/brew.rb:135:in `send'
/usr/local/Library/brew.rb:135

Brew doctor and brew update were both run.

**Comment by mistydemeo** [comment]
Unfortunately node.js uses V8, which isn't PPC compatible. I'll need to mark node as needing an Intel CPU to build.

**Comment by w-hive** [comment]
Although...

https://github.com/andrewlow/v8ppc
