### ISSUE TITLE
git (2.5.0) upgrade fails with "Error: undefined method `dirname' for nil:NilClass" (10.4/G4)

### ISSUE THREAD

**Issue by dcwar** [mistydemeo/tigerbrew#347]
Thanks so much for the great update!!  Slight issue here - attempting to upgrade git fails early on with the following error:

Error: undefined method `dirname' for nil:NilClass
Please report this bug:
    https://github.com/mistydemeo/tigerbrew/wiki/troubleshooting
/usr/local/Library/Homebrew/formula.rb:768:in `file_modified?'
/usr/local/Library/Homebrew/formula_installer.rb:78:in `pour_bottle?'
/usr/local/Library/Homebrew/formula_installer.rb:159:in `install'
/usr/local/Library/Homebrew/cmd/upgrade.rb:71:in `upgrade_formula'
/usr/local/Library/Homebrew/cmd/upgrade.rb:44:in `upgrade'
/usr/local/Library/Homebrew/cmd/upgrade.rb:44:in `each'
/usr/local/Library/Homebrew/cmd/upgrade.rb:44:in `upgrade'
/usr/local/Library/brew.rb:121:in `send'
/usr/local/Library/brew.rb:121

Console output can be found here: https://gist.github.com/dcwar/b7d03a90727188210322

**Comment by mistydemeo** [comment]
If you still have a git installed, can you `brew update`? This should be fixed as of the latest two commits.

**Comment by dcwar** [comment]
That did it! Thank you!!

**Comment by mistydemeo** [comment]
Great!
