### ISSUE TITLE
enable-ec_nistp-64_gcc_128 is used on PPC

### ISSUE THREAD

**Issue by noloader** [mistydemeo/tigerbrew#351]
openssl.rb has the following:

    def arch_args
    {
      :x86_64 => %w[darwin64-x86_64-cc enable-ec_nistp_64_gcc_128],
      :i386   => %w[darwin-i386-cc],
      :ppc    => %w[darwin-ppc-cc],
      :ppc64  => %w[darwin64-ppc-cc enable-ec_nistp-64_gcc_128]
    }
    end

`enable-ec_nistp-64_gcc_128` should only be set under a few conditions:

 * `__SIZEOF_INT128__` is defined
 * CPU is little endian
 * CPU tolerates unaligned data access

I believe PowerPC's are big endian, so that should *not* be set.

Also see [Compilation and Installation | Configure Options](https://wiki.openssl.org/index.php/Compilation_and_Installation#Configure_Options) on the OpenSSL wiki. Andy Polyakov provided the criteria for `enable-ec_nistp-64_gcc_128` in a private email, and it was transcribed into the wiki page.

**Comment by mistydemeo** [comment]
Thank you! Removed it.

**Comment by noloader** [comment]
> Thank you! Removed it.

No problem. Until two days ago, I thought the only requirement was 64-bit hardware and and an `int128` or `uint128` aligned on a 16-byte boundary.
