### ISSUE TITLE
Requesting go bottle

### ISSUE THREAD

**Issue by w-hive** [mistydemeo/tigerbrew#352]
Apparently PPC is now supported in Go:

https://code.google.com/p/go/issues/detail?id=8654

https://github.com/golang/go/commit/5158147e24a4626d14971fdda38d71db4a975a04

http://grokbase.com/t/gg/golang-nuts/1548n7py08/go-nuts-go-for-powerpc-if-not-how-to-build-gos-packages-with-cross-compiler-gccgo

Do you think a tigerbrew bottle would be possible?

**Comment by mistydemeo** [comment]
Oh wow, interesting! I wonder if it supports darwinppc in addition to linux-powerpc?

The last post you quoted mentions that it's currently PPC64 only. Unfortunately, I don't have any 64-bit PowerPC hardware, so I haven't been building bottles for that architecture. I'd love to given the chance, though.

I wonder if GCC's go compiler supports 32-bit PPC?

**Comment by mistydemeo** [comment]
If so, given how slow GCC is to compile, I wouldn't be opposed to turning go on by default in the PowerPC bottles.

**Comment by mistydemeo** [comment]
Looks like gccgo is still known not to build on Darwin at all, unfortunately: https://github.com/golang/go/issues/463

**Comment by mistydemeo** [comment]
Unfortunately, it looks like Go's ppc64 support is Linux only:

```
$ env GOOS=linux GOARCH=ppc64 go build hello.go
# completes successfully
$ env GOOS=darwin GOARCH=ppc64 go build hello.go
# runtime
2015/09/11 21:42:25 unknown thread-local storage offset for darwin/ppc64
```

Someday, hopefully!
