### ISSUE TITLE
Bind failed to build on 10.4.11 running on a G4 (7400) cube

### ISSUE THREAD

**Issue by jsonnenb** [mistydemeo/tigerbrew#358]
I'm trying to install bind on my G4 cube so it be the local DNS. However, I can't see to get past the configure step. It seems to die with the kerberos features.

Requested files are in this gist:
https://gist.github.com/jsonnenb/2d99bcf4c4d18d3c79d6

**Comment by mistydemeo** [comment]
Looking at Macports's port as a reference, it seems this needs `--with-gssapi=no --with-dlopen=no` on Tiger and `--with-dlopen=no` on Leopard: https://trac.macports.org/browser/trunk/dports/net/bind9/Portfile#L59

Are you able to test if this fixes it? I don't have access to my older Macs right now.

**Comment by jsonnenb** [comment]
In debugging the 10.4.11 build on the G4 cube, I tried building bind on my G4e Mac running Leopard. The Leopard compile on the G4e completed without problems. 

As a side note, brew config can't find Java on the G4 cube. This is not the case on the G4e running Leopard. How should I go about teaching brew where to find the installed version of Java (it's already installed!) on the G4 cube?

**Comment by jsonnenb** [comment]
The G4 cube compiled successfully after adding --with-gssapi=no and --with-dlopen=no options to the install def via brew edit bind. Could you kindly add the logic for the Darwin 8 compile to the official bind.rb file? I'm a long time brew user but new to the git modification part.

**Comment by mistydemeo** [comment]
Fixed, thanks!
