### ISSUE TITLE
curl failing on 10.4.11-i386

### ISSUE THREAD

**Issue by picklefarmer** [mistydemeo/tigerbrew#359]
https://gist.github.com/picklefarmer/916dc234cfa89d7abf61

**Comment by mistydemeo** [comment]
Can you show me your `brew --config`, please?

**Comment by picklefarmer** [comment]
I'll append it to the gist; here it is

HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/mistydemeo/tigerbrew.git
HEAD: 08f16905f4106abfa7fe3641157b11b399e47168
Last commit: 6 days ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://ia902307.us.archive.org/31/items/tigerbrew
CPU: dual-core 32-bit core2
OS X: 10.4.11-i386
Xcode: 2.5
CLT: N/A
GCC-4.0: build 5370
GCC-4.2: build 5553
Clang: N/A
X11: N/A
System Ruby: 1.8.2 => /usr/bin/ruby
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /Users/andymocahey
Java: N/A

**Comment by mistydemeo** [comment]
>  Ruby: /usr/bin/ruby => /Users/andymocahey

Have you made changes to the Ruby in `/usr/bin/ruby`?

**Comment by mistydemeo** [comment]
Does this do anything?

```
$ /usr/local/Library/Homebrew/vendor/sha256 -v
```

**Comment by picklefarmer** [comment]
Bus error

**Comment by mistydemeo** [comment]
Interesting. Can you show me the full output, please?

Sounds like the Intel slice is failing. I don't have an Intel 10.4 machine to test this on myself but I'll try to reproduce.

**Comment by Shalmezad** [comment]
Looking at the error, it's similar to what I'm experiencing. For that last command, Bus error is the full output:

~$/usr/local/Library/Homebrew/vendor/sha256 -v
Bus error

Here's everything for my system, only big difference is I don't have git yet (same issue when trying to install git):
https://gist.github.com/Shalmezad/8ef2e02948b90c10ffc3

Happy to help if you need any more info or have something to test.

**Comment by Shalmezad** [comment]
Found a log file for sha256 after running that command.
Not sure if it'll help you, but the contents can be found here:
https://gist.github.com/Shalmezad/468b9f75d2d5230d8ff1

**Comment by kujo770** [comment]
Came to submit a bug, but then found this issue. Exact same problem trying to brew install anything. This is on a fresh Tiger Intel install. Bus Error trying to execute directly, as above. Also generates a sha256.crash.log file:
Link (dyld) error:

Symbol not found: _read$UNIX2003
  Referenced from: /usr/local/Library/Homebrew/vendor/sha256
  Expected in: /usr/lib/libSystem.B.dylib

**Comment by ranma42** [comment]
I can confirm the issue. I worked around it by rebuilding `sha256` from sources in my environment (again a 10.4 i386). I can provide the binary if needed.
Another (possibly convenient) option would be to ship the source code for `sha256` and build it during the installation.

**Comment by ranma42** [comment]
See #366 for another possible fix.

**Comment by mistydemeo** [comment]
Should be fixed now.
