### ISSUE TITLE
clamav failed to build in Mac OS 10.4.11

### ISSUE THREAD

**Issue by emninger** [mistydemeo/tigerbrew#360]
When i tried to install clamav the installation failed with this error msg:

-----
checking syslog.h usability... yes
checking syslog.h presence... yes
checking for syslog.h... yes
checking pthread.h usability... yes
checking pthread.h presence... yes
checking for pthread.h... yes
checking for C/C++ restrict keyword... __restrict
checking for an ANSI C-conforming const... yes
checking for inline... inline
checking whether byte ordering is bigendian... yes
checking for a supported version of gcc... ok (4.0.1)
checking for gcc bug PR27603... ok, bug not present
checking for gcc bug PR26763-2... ok, bug not present
checking for valid code generation of CLI_ISCONTAINED... ok, bug not present
checking for gcc bug PR28045... configure: error: your compiler has gcc PR28045 bug, use a different compiler, see http://gcc.gnu.org/bugzilla/show_bug.cgi?id=28045
Error: Permission denied - /usr/libexec/java_home
----

brew doctor is ok, git installed.

I went to the site indicated there but it was not clear to me what to do.

Other packages installed fine with brew (e.g. tor)

TIA

**Comment by mistydemeo** [comment]
Looks like this doesn't build with GCC 4.0. GCC 4.2 may be able to handle it?

**Comment by mistydemeo** [comment]
Fixed by marking it as not compiling with GCC 4.0. Thanks for the report!

**Comment by emninger** [comment]
It's a long time i've not been here. Thanks for your patience. It works now ;)
