### ISSUE TITLE
stone-soup failed to install (10.5/G5)

### ISSUE THREAD

**Issue by w-hive** [mistydemeo/tigerbrew#379]
https://gist.github.com/aa138fc3cef33659d490

**Comment by mistydemeo** [comment]
Should be fixed by using a newer sqlite.

**Comment by w-hive** [comment]
Didn't seem to fix it actually :(

https://gist.github.com/9bf3e838e78c22925181

**Comment by mistydemeo** [comment]
Looks like a new error:

```
g++-5: error: unrecognized command line option '-rdynamic'
make: *** [crawl] Error 1
```

**Comment by mistydemeo** [comment]
Should be fixed now!
