### ISSUE TITLE
openexr does not brew

### ISSUE THREAD

**Issue by w-hive** [mistydemeo/tigerbrew#398]
https://gist.github.com/27438e92d57c44915886

**Comment by mistydemeo** [comment]
Looks like there's an issue on 32-bit targets:

```
libtool: compile:  g++-4.2 -DHAVE_CONFIG_H -I. -I../config -D_THREAD_SAFE -I/usr/local/Cellar/ilmbase/2.2.0/include/OpenEXR -I.. -I../config -pipe -g -O2 -c ImfFastHuf.cpp  -fno-common -DPIC -o .libs/ImfFastHuf.o
ImfFastHuf.cpp:110: error: integer constant is too large for ‘long’ type
ImfFastHuf.cpp:355: error: integer constant is too large for ‘long’ type
ImfFastHuf.cpp:365: error: integer constant is too large for ‘long’ type
ImfFastHuf.cpp:420: error: integer constant is too large for ‘long’ type
ImfFastHuf.cpp:430: error: integer constant is too large for ‘long’ type
make[2]: *** [ImfFastHuf.lo] Error 1
make[1]: *** [install] Error 2
make: *** [install-recursive] Error 1
```

Sample line from the code:

```c++
base[i]      = 0xffffffffffffffffL;
```

The type of `base` is `Int64[]`, but the specified type of the literal on the right is wrong given that the `long` type is too small to actually hold this value on a 32-bit system.

Looks like this was [fixed](https://github.com/openexr/openexr/commit/57ecf581d053f5cacf2e8fc3c024490e0bbe536f) [upstream](https://github.com/openexr/openexr/commit/353cbc2e89c582e07796f01bce8f203e84c8ae46) but that hasn't made it into a release yet.

**Comment by mistydemeo** [comment]
Should be fixed now!

**Comment by w-hive** [comment]
Works fine, thanks!
