### ISSUE TITLE
Q: Is 10.6/10.7 support now a part of Tigerbrew?

### ISSUE THREAD

**Issue by w-hive** [mistydemeo/tigerbrew#401]
Just noting the message that appears on two of my systems using regular Homebrew:

Warning: You are using OS X 10.6.
We (and Apple) do not provide support for this old version.
You may encounter build failures or other breakages.

**Comment by mistydemeo** [comment]
I haven't formally taken 10.6/10.7 support into Tigerbrew. They work in Homebrew right now (just with the message about reduced support); not sure what the longterm outcome of this will be.

**Comment by w-hive** [comment]
Thanks for the info :-)
