### ISSUE TITLE
heroku-toolbelt does not install with Ruby 2.2.4 and RVM 1.26.11

### ISSUE THREAD

**Issue by davidmrnustik** [mistydemeo/tigerbrew#403]
Hello,
I have tried to install heroku-toolbelt with tigerbrew, but something went wrong.
I did: `brew update`, `brew install heroku-toolbelt`, but after `heroku`, I got this:
`/usr/local/bin/heroku: /usr/local/Cellar/heroku-toolbelt/3.42.10/libexec/bin/heroku: /usr/local/opt/ruby/bin/ruby: bad interpreter: No such file or directory
/usr/local/bin/heroku: line 2`

I have Powerbook G4 and 10.5.8., XCode Tools 3.1.4. I also use rvm because of rails development. Probably this would be an issue, because `which ruby` tells me I have a ruby here:
`/Users/davidmrnustik/.rvm/rubies/ruby-2.2.4/bin/ruby`

Is there any way to install heroku properly?

Thanks!

**Comment by mistydemeo** [comment]
Should be fixed now; I've merged in changes to that formula that have been made since Tigerbrew was last updated!

**Comment by davidmrnustik** [comment]
Thanks @mistydemeo,
I've tried, but did not let me even install it. I executed `brew update`, `brew doctor` and `brew install heroku-toolbelt` and I got:
```/usr/local/Library/Homebrew/software_spec.rb:72:in instance_eval'```
```/usr/local/Library/Homebrew/software_spec.rb:72:in `bottle'```
```/usr/local/Library/Homebrew/formula.rb:1555:in `bottle'```
```/usr/local/Library/Formula/heroku-toolbelt.rb:8:in `load_formula'```
```/usr/local/Library/Homebrew/formulary.rb:36:in `load_formula_from_path'```
```/usr/local/Library/Homebrew/formulary.rb:85:in `load_file'```
```/usr/local/Library/Homebrew/formulary.rb:76:in `klass'```
```/usr/local/Library/Homebrew/formulary.rb:72:in `get_formula'```
```/usr/local/Library/Homebrew/formulary.rb:207:in `factory'```
```/usr/local/Library/Homebrew/formulary.rb:355:in `find_with_priority'```
```/usr/local/Library/Homebrew/extend/ARGV.rb:20:in `formulae'```
```/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'```
```/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'```
```/usr/local/Library/Homebrew/cmd/install.rb:45:in `install'```
```/usr/local/Library/brew.rb:127:in `send'```
```/usr/local/Library/brew.rb:12```

**Comment by mistydemeo** [comment]
Oh, I believe I see the problem. The updates I merged used a feature Tigerbrew didn't have yet; I've added that now, too.

Sorry about this - don't have access to my PPC Macs, so I'm flying a little blind right now.

**Comment by davidmrnustik** [comment]
Now it lets me download it, but I got some errors after when execute `heroku`.
```heroku-cli: Installing Toolbelt v4... !    Heroku client internal error.```
```!    Search for help at: https://help.heroku.com```
```!    Or report a bug at: https://github.com/heroku/heroku/issues/new```
```   Error:       undefined method `[]' for nil:NilClass (NoMethodError)```
```   Command:     heroku ```
```   Version:     heroku-toolbelt/3.42.22 (powerpc-darwin9.0) ruby/2.2.4```
```   Error ID:    88f72359d05245b5bff6c2709c830ebb```


    More information in /Users/davidmrnustik/.heroku/error.log

This is a log:
```Heroku client internal error.```
```undefined method `[]' for nil:NilClass```
```/usr/local/Cellar/heroku-toolbelt/3.42.22/libexec/lib/heroku/jsplugin.rb:211:in `url'```
```/usr/local/Cellar/heroku-toolbelt/3.42.22/libexec/lib/heroku/jsplugin.rb:135:in `setup'```
```/usr/local/Cellar/heroku-toolbelt/3.42.22/libexec/lib/heroku/cli.rb:24:in `start'```
```/usr/local/Cellar/heroku-toolbelt/3.42.22/libexec/bin/heroku:24:in `<main>'```

**Comment by mistydemeo** [comment]
Looking at the stack trace, it happens here, when attempting to fetch a binary copy of [heroku v4](https://github.com/heroku/heroku-cli), their new tool. Unlike the old version, this is written in go, not ruby; so heroku handles this by checking the OS and architecture, and downloading a binary for that platform:

```ruby
  def self.url
    manifest['builds'][os][arch]['url'] + ".gz"
  end
```

Unfortunately, they only provide amd64 binaries for darwin. Unfortunately it looks like there won't be a way to get this working on PPC. :crying_cat_face:

**Comment by mistydemeo** [comment]
Marked it as requiring x86_64 in 8f5368b5b2e69cb0c76d7c677000d5c035dc2939, but will see if there's an older version of the client I can revery to that still works with their servers.

**Comment by davidmrnustik** [comment]
Thanks @mistydemeo, now the error message after `brew install heroku-toolbelt` is more explicit:

    heroku-toolbelt: This formula requires an x86_64 architecture.
    Error: An unsatisfied requirement failed this build.

Will see, I try to deploy with Windows machine now.
