### ISSUE TITLE
graphviz: formula tries to download unavailable link

### ISSUE THREAD

**Issue by jibe-b** [mistydemeo/tigerbrew#405]
with tigerbrew,

> brew install graphviz

tries to download

> https://dl.bintray.com/homebrew/mirror/libpng-1.6.18.tar.xz

which is no longer available. Istead, https://dl.bintray.com/homebrew/mirror/libpng-1.*7*.18.tar.xz is available

**Comment by jibe-b** [comment]
The second link is wrong, sorry. (and github does not work well on this old mac)

> https://dl.bintray.com/homebrew/mirror/libpng-1.6.19.tar.xz

is available

**Comment by mistydemeo** [comment]
Fixed by updating to 1.6.21. I initially tried updating to 1.6.20, which Homebrew packages, but that was broken on big-endian systems.

**Comment by jibe-b** [comment]
thanks!
