### ISSUE TITLE
brew formula issues (10.4/G4)

### ISSUE THREAD

**Issue by dcwar** [mistydemeo/tigerbrew#407]
`brew outdated` fails, starting with the following error:
"Error: undefined method `apply' for #<Resource:0x121dd94>"

Console output: https://gist.github.com/dcwar/8c58b7e7bedcbbe280e7

I noted this after upgrading Tigerbrew from b76c7e5b to cf946543.

**Comment by dcwar** [comment]
Subsequently noted that `rsync` is un-upgradeable, due to a similar "apply" error.

`brew uses libpng` produces the following errors before proper output:
`Error: Failed to import: /usr/local/Library/Formula/node.rb
unknown version :intel
Error: Failed to import: /usr/local/Library/Taps/homebrew/homebrew-apache/mod_suexec.rb
formulae require at least a URL
Error: Failed to import: /usr/local/Library/Taps/homebrew/homebrew-dupes/rsync.rb
undefined method `apply' for #<Resource:0x8eaed34>`

**Comment by mistydemeo** [comment]
Fixed the node issue, but not rsync yet.

**Comment by mistydemeo** [comment]
Fixed the rsync issue. It was using a new feature I hadn't introduced to Tigerbrew yet.

**Comment by dcwar** [comment]
Thank you so much!!! :D
