### ISSUE TITLE
mplayer fails to brew on g3 (10.4)

### ISSUE THREAD

**Issue by boudinfl** [mistydemeo/tigerbrew#409]
mplayer fails to brew on my ibook g3 with tiger, here is the error message :

florian$ brew install mplayer
==> Installing dependencies for mplayer: homebrew/dupes/make, yasm
==> Installing mplayer dependency: homebrew/dupes/make
==> Downloading http://ftpmirror.gnu.org/make/make-4.1.tar.bz2
==> Downloading from http://mirror0.babylon.network/gnu/make/make-4.1.tar.bz2
###### ################################################################## 100.0%

==> ./configure --prefix=/usr/local/Cellar/make/4.1 --program-prefix=g
==> make install
/usr/local/Cellar/make/4.1: 11 files, 920K, built in 3.7 minutes
==> Installing mplayer dependency: yasm
==> Downloading http://www.tortall.net/projects/yasm/releases/yasm-1.3.0.tar.gz
###### ################################################################## 100.0%

==> ./configure --prefix=/usr/local/Cellar/yasm/1.3.0
==> make install
/usr/local/Cellar/yasm/1.3.0: 44 files, 3.5M, built in 6.5 minutes
==> Installing mplayer
==> Downloading https://www.mplayerhq.hu/MPlayer/releases/MPlayer-1.2.tar.xz
###### ################################################################## 100.0%

==> ./configure --cc=/usr/local/bin/gcc-4.2 --host-cc=/usr/local/bin/gcc-4.2 --disable-cdparanoia --prefix=/usr/local/Cellar/mpla
==> /usr/local/opt/make/bin/gmake
Last 15 lines from /Users/florian/Library/Logs/Homebrew/mplayer/02.gmake:
/usr/local/bin/gcc-4.2 -MMD -MP -Wundef  -Wstrict-prototypes -Wmissing-prototypes -Wdisabled-optimization -Wno-pointer-sign -Wdeclaration-after-statement -std=gnu99  -D_ISOC99_SOURCE -I. -Iffmpeg -Os -w -pipe -mcpu=750 -faltivec -mmacosx-version-min=10.4 -faltivec -fno-tree-vectorize -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -falign-loops=16 -shared-libgcc -mdynamic-no-pic   -I/usr/X11R6/include -DZLIB_CONST -c -o libvo/vo_null.o libvo/vo_null.c
/usr/local/bin/gcc-4.2 -MMD -MP -Wundef  -Wstrict-prototypes -Wmissing-prototypes -Wdisabled-optimization -Wno-pointer-sign -Wdeclaration-after-statement -std=gnu99  -D_ISOC99_SOURCE -I. -Iffmpeg -Os -w -pipe -mcpu=750 -faltivec -mmacosx-version-min=10.4 -faltivec -fno-tree-vectorize -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -falign-loops=16 -shared-libgcc -mdynamic-no-pic   -I/usr/X11R6/include -DZLIB_CONST -c -o sub/spuenc.o sub/spuenc.c
/usr/local/bin/gcc-4.2 -MMD -MP -Wundef  -Wstrict-prototypes -Wmissing-prototypes -Wdisabled-optimization -Wno-pointer-sign -Wdeclaration-after-statement -std=gnu99  -D_ISOC99_SOURCE -I. -Iffmpeg -Os -w -pipe -mcpu=750 -faltivec -mmacosx-version-min=10.4 -faltivec -fno-tree-vectorize -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -falign-loops=16 -shared-libgcc -mdynamic-no-pic   -I/usr/X11R6/include -DZLIB_CONST -c -o input/ar.o input/ar.c
/usr/local/bin/gcc-4.2 -MMD -MP -Wundef  -Wstrict-prototypes -Wmissing-prototypes -Wdisabled-optimization -Wno-pointer-sign -Wdeclaration-after-statement -std=gnu99  -D_ISOC99_SOURCE -I. -Iffmpeg -Os -w -pipe -mcpu=750 -faltivec -mmacosx-version-min=10.4 -faltivec -fno-tree-vectorize -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -falign-loops=16 -shared-libgcc -mdynamic-no-pic   -I/usr/X11R6/include -DZLIB_CONST -c -o libao2/ao_coreaudio.o libao2/ao_coreaudio.c
/usr/local/bin/gcc-4.2 -MMD -MP -Wundef  -Wstrict-prototypes -Wmissing-prototypes -Wdisabled-optimization -Wno-pointer-sign -Wdeclaration-after-statement -std=gnu99  -D_ISOC99_SOURCE -I. -Iffmpeg -Os -w -pipe -mcpu=750 -faltivec -mmacosx-version-min=10.4 -faltivec -fno-tree-vectorize -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -falign-loops=16 -shared-libgcc -mdynamic-no-pic   -I/usr/X11R6/include -DZLIB_CONST -c -o libvo/vo_corevideo.o libvo/vo_corevideo.m
/usr/local/bin/gcc-4.2 -MMD -MP -Wundef  -Wstrict-prototypes -Wmissing-prototypes -Wdisabled-optimization -Wno-pointer-sign -Wdeclaration-after-statement -std=gnu99  -D_ISOC99_SOURCE -I. -Iffmpeg -Os -w -pipe -mcpu=750 -faltivec -mmacosx-version-min=10.4 -faltivec -fno-tree-vectorize -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -falign-loops=16 -shared-libgcc -mdynamic-no-pic   -I/usr/X11R6/include -DZLIB_CONST -c -o libvo/osx_common.o libvo/osx_common.c
/usr/local/bin/gcc-4.2 -MMD -MP -Wundef  -Wstrict-prototypes -Wmissing-prototypes -Wdisabled-optimization -Wno-pointer-sign -Wdeclaration-after-statement -std=gnu99  -D_ISOC99_SOURCE -I. -Iffmpeg -Os -w -pipe -mcpu=750 -faltivec -mmacosx-version-min=10.4 -faltivec -fno-tree-vectorize -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -falign-loops=16 -shared-libgcc -mdynamic-no-pic   -I/usr/X11R6/include -DZLIB_CONST -c -o libvo/osx_objc_common.o libvo/osx_objc_common.m
libvo/osx_objc_common.m: In function '-[MPCommonOpenGLView preinit]':
libvo/osx_objc_common.m:135: error: 'GLint' undeclared (first use in this function)
libvo/osx_objc_common.m:135: error: (Each undeclared identifier is reported only once
libvo/osx_objc_common.m:135: error: for each function it appears in.)
libvo/osx_objc_common.m:135: error: expected ';' before 'swapInterval'
libvo/osx_objc_common.m:174: error: 'swapInterval' undeclared (first use in this function)
Makefile:735: recipe for target 'libvo/osx_objc_common.o' failed
gmake: **\* [libvo/osx_objc_common.o] Error 1
Error: No such file or directory - /usr/sbin/pkgutil

**Comment by e-inquirer** [comment]
Ditto here on a g4; verbatim error output more or less.

**Comment by mistydemeo** [comment]
Should be fixed now.
