### ISSUE TITLE
please update the url of libevent in libevent.rb

### ISSUE THREAD

**Issue by soonsimple** [mistydemeo/tigerbrew#411]
please update the url of libevent in libevent.rb

the wrong url "https://downloads.sourceforge.net/project/levent/libevent/libevent-2.0/libevent-2.0.22-stable.tar.gz", 

the correct one maybe

"http://downloads.sourceforge.net/project/levent/release-2.0.22-stable/libevent-2.0.22-stable.tar.gz"

or

"https://github.com/libevent/libevent/releases/download/release-2.0.22-stable/libevent-2.0.22-stable.tar.gz".

soonsimple
2016-3-13

**Comment by sevan** [comment]
v2.1.12-stable is now in Tigerbrew.
