### ISSUE TITLE
htop fails to build on Tiger 10.4.11

### ISSUE THREAD

**Issue by Flare183** [mistydemeo/tigerbrew#421]
After fixing my issue with git not cloning htop correctly, I get this error:
http://imgur.com/LYctldw

**Comment by mistydemeo** [comment]
Can you try installing `apple-gcc42`, then try installing htop again, and see if it works?

**Comment by Flare183** [comment]
I get this now: http://imgur.com/RHxdHVI

**Comment by Flare183** [comment]
If its any help, I do have XCode 2.5 installed, because I think that's the last XCode that you can install on Mac OSX Tiger
