### ISSUE TITLE
Error: undefined method `captures' for nil:NilClass

### ISSUE THREAD

**Issue by cneira** [mistydemeo/tigerbrew#427]
I'm not able to install packages using brew, brew install fails with the following message

feist:~ cnb$ brew install git
==> Installing dependencies for git: xz, gnu-tar, cctools-headers, dyld-h
==> Installing git dependency: xz
==> Downloading https://fossies.org/linux/misc/xz-5.2.1.tar.gz
Already downloaded: /Library/Caches/Homebrew/xz-5.2.1.tar.gz
Error: undefined method `captures' for nil:NilClass
Please report this bug:
    https://github.com/mistydemeo/tigerbrew/wiki/troubleshooting
/usr/local/Library/Homebrew/extend/pathname.rb:293:in`sha256_vendored_sha2'
/usr/local/Library/Homebrew/extend/pathname.rb:284:in `sha256'
/usr/local/Library/Homebrew/extend/pathname.rb:298:in`send'
/usr/local/Library/Homebrew/extend/pathname.rb:298:in `verify_checksum'
/usr/local/Library/Homebrew/resource.rb:120:in`verify_download_integrity'
/usr/local/Library/Homebrew/resource.rb:80:in `stage'
/usr/local/Library/Homebrew/formula.rb:1405:in`stage'
/usr/local/Library/Homebrew/formula.rb:859:in `brew'
/usr/local/Library/Homebrew/build.rb:106:in`install'
/usr/local/Library/Homebrew/build.rb:175
feist:~ cnb$ brew doc
Error: Unknown command: doc
feist:~ cnb$ brew doctor
Please note that these warnings are just used to help the Tigerbrew maintainers
with debugging if you file an issue. If everything you use Tigerbrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: The system curl on 10.6 and below is often incapable of supporting
modern secure connections & will fail on fetching formulae.
We recommend you:
  brew install curl

Warning: Git could not be found in your PATH.
Tigerbrew uses Git for several internal functions, and some formulae use Git
checkouts instead of stable tarballs. You may want to install Git:
  brew install git

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Tigerbrew formulae, and may need to be deleted.

Unexpected dylibs:
    /usr/local/lib/libfuse.0.dylib
    /usr/local/lib/libulockmgr.1.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Tigerbrew formulae, and may need to be deleted.

Unexpected header files:
    /usr/local/include/ulockmgr.h

Warning: Unbrewed .la files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Tigerbrew formulae, and may need to be deleted.

Unexpected .la files:
    /usr/local/lib/libulockmgr.la

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Tigerbrew formulae, and may need to be deleted.

Unexpected static libraries:
    /usr/local/lib/libfuse.a
    /usr/local/lib/libulockmgr.a

**Comment by dcwar** [comment]
Can you post the output of `brew config`?
