### ISSUE TITLE
qemu install fails: shallow over http or ftp not supported

### ISSUE THREAD

**Issue by programmingkidx** [mistydemeo/tigerbrew#428]
When trying to install qemu, I see this error message: shallow over http or ftp not supported. Here is the full output:

$ brew install qemu
==> Tapping homebrew/dupes
Initialized empty Git repository in /usr/local/Library/Taps/homebrew/homebrew-dupes/.git/
shallow over http or ftp not supported
Error: Failure while executing: git clone https://github.com/Homebrew/homebrew-dupes /usr/local/Library/Taps/homebrew/homebrew-dupes --depth=1

I then tried this:
$ brew update
Initialized empty Git repository in .git/
error: SSL certificate problem, verify that the CA cert is OK. Details:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
error: SSL certificate problem, verify that the CA cert is OK. Details:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
fatal: Failed to resolve 'origin/master' as a valid ref.
Error: Failure while executing: git reset --hard origin/master

**Comment by mistydemeo** [comment]
What version of git do you have installed?

**Comment by programmingkidx** [comment]
I am using version 1.5.4.3.

**Comment by mistydemeo** [comment]
That version's very old - it doesn't support some of the features Tigerbrew is using. Can you `brew install git` and use that version instead?

**Comment by programmingkidx** [comment]
Will try newest version of git. Could a requirement be added to the qemu formula so it checks for the right version of git?

**Comment by programmingkidx** [comment]
Updating git did get me to making QEMU. QEMU failed to build. Here is the error message:

--cc=/usr/bin/gcc-4.0
--host-cc=/usr/bin/gcc-4.0
--enable-cocoa
--disable-bsd-user
--disable-guest-agent
--disable-sdl
--disable-vde
--disable-gtk
--disable-libssh2

second level name optional in hw.optional.x86_64 is invalid

ERROR: Your compiler does not support the __thread specifier for 
       Thread-Local Storage (TLS). Please upgrade to a version that does.

I did update GCC to 5.2, but the qemu formula is set to use gcc 4.0.

**Comment by awesomebing1** [comment]
@programmingkidx Just so you know, there's an issue regarding that: #400.

**Comment by mistydemeo** [comment]
This should be fixed now, if you use gcc-5.
