### ISSUE TITLE
tcl-tk 8.6.6 breaks existing Tiger patch

### ISSUE THREAD

**Issue by dcwar** [mistydemeo/tigerbrew#430]
Hi! Looks like they're now including a new version of sqlite (3.13.0), which breaks the existing Tiger patch for tcl-tk. Build fails as a result.

**Comment by programmingkidx** [comment]
The patched file is now located here: tcl8.6.6/pkgs/sqlite3.13.0/compat/sqlite3/sqlite3.c
Changing the file that is patched shouldn't be difficult.

**Comment by programmingkidx** [comment]
Please replace the old patch in the rb file with this one:

diff --git a/pkgs/sqlite3.13.0/compat/sqlite3/sqlite3.c b/pkgs/sqlite3.13.0/compat/sqlite3/sqlite3.c
index 3e20b56..95035d4 100644
--- a/pkgs/sqlite3.13.0/compat/sqlite3/sqlite3.c
+++ b/pkgs/sqlite3.13.0/compat/sqlite3/sqlite3.c
@@ -20140,6 +20140,7 @@ SQLITE_PRIVATE void sqlite3MemSetDefault(void){
 #include <sys/sysctl.h>
 #include <malloc/malloc.h>
 #include <libkern/OSAtomic.h>
+
 static malloc_zone_t* _sqliteZone_;
 #define SQLITE_MALLOC(x) malloc_zone_malloc(_sqliteZone_, (x))
 #define SQLITE_FREE(x) malloc_zone_free(_sqliteZone_, (x));
@@ -20147,6 +20148,29 @@ static malloc_zone_t* _sqliteZone_;
 #define SQLITE_MALLOCSIZE(x) \
         (_sqliteZone_ ? _sqliteZone_->size(_sqliteZone_,x) : malloc_size(x))
 
+/*
+** If compiling for Mac OS X 10.4, the OSAtomicCompareAndSwapPtrBarrier
+** function will not be available, but individual 32-bit and 64-bit
+** versions will.
+*/
+
+#ifdef __MAC_OS_X_MIN_REQUIRED
+# include <AvailabilityMacros.h>
+#elif defined(__IPHONE_OS_MIN_REQUIRED)
+# include <Availability.h>
+#endif
+
+typedef int fc_atomic_int_t;
+#if (MAC_OS_X_VERSION_MIN_REQUIRED > MAC_OS_X_VERSION_10_4 || __IPHONE_VERSION_MIN_REQUIRED >= 20100)
+# define fc_atomic_ptr_cmpexch(O,N,P) OSAtomicCompareAndSwapPtrBarrier ((void *) (O), (void *) (N), (void **) (P))
+#else
+# if __ppc64__ || __x86_64__
+#  define fc_atomic_ptr_cmpexch(O,N,P) OSAtomicCompareAndSwap64Barrier ((int64_t) (O), (int64_t) (N), (int64_t*) (P))
+# else
+#  define fc_atomic_ptr_cmpexch(O,N,P) OSAtomicCompareAndSwap32Barrier ((int32_t) (O), (int32_t) (N), (int32_t*) (P))
+# endif
+#endif
+
 #else /* if not __APPLE__ */
 
 /*
@@ -20334,7 +20358,7 @@ static int sqlite3MemInit(void *NotUsed){
     malloc_zone_t* newzone = malloc_create_zone(4096, 0);
     malloc_set_zone_name(newzone, "Sqlite_Heap");
     do{
-      success = OSAtomicCompareAndSwapPtrBarrier(NULL, newzone, 
+      success = fc_atomic_ptr_cmpexch(NULL, newzone,
                                  (void * volatile *)&_sqliteZone_);
     }while(!_sqliteZone_);
     if( !success ){
-- 
2.6.0

**Comment by programmingkidx** [comment]
It doesn't look like I can place my patch here. Try this. Open terminal. Then run these commands:

export EDITOR=/Applications/TextEdit.app/Contents/MacOS/TextEdit

brew edit homebrew/dupes/tcl-tk

http://www.mediafire.com/file/g6phuehuq3kjx5w/replacement_tcl-tk.txt
Then replace all of the text in the window with the text in the above file.

Save and close Textedit. 

You should be able to 'brew install homebrew/dupes/tcl-tk' successfully.

**Comment by programmingkidx** [comment]
Notes: 
This is the exact command I used to install: brew -v install homebrew/dupes/tcl-tk --cc=gcc-5 --with-threads

With the --cc=gcc-5 option, I would see libtool errors. 

When I try to run a simple python-tk application, it fails and prints this error message:
>>> from Tkinter import *
>>> root = Tk()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python/2.7.12_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk/Tkinter.py", line 1815, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

**Comment by programmingkidx** [comment]
Correction, I should say *without* the --cc=gcc-5 option, I would see libtool errors.

**Comment by programmingkidx** [comment]
I found out how this version of tcl-tk can work on Mac OS 10.4. Open x11 (/Applications/Utilities/x11). Then run python in the command prompt. If you see a window appear with the simple program below, then Tk is working. The drawback is no aqua look and feel. The widgets look like these widgets: http://wiki.tcl.tk/490

One good point to this version of Tk is the Themed Tk (ttk) package does appear to be available now.

**Comment by programmingkidx** [comment]
Simple program to try out Python-Tk with. Note: open Python from the x11 program first.

from Tkinter import *

def doSomething():
	my_label.config(text="OUCH")

root = Tk()
my_label = Label(root, text="    ", padx=50, pady=40)
my_label.pack(side=LEFT)
my_button = Button(root, text="Push", command=doSomething)
my_button.pack(side=RIGHT)
mainloop()

**Comment by programmingkidx** [comment]
I did finally figure out how to make Tcl and Tk 8.5.12 work on Mac OS 10.4. It is better than the Apple-supplied 8.4.7.

Just download these two files: 
ftp://ftp.tcl.tk/pub/tcl/tcl8_5/tcl8.5.12-src.tar.gz
ftp://ftp.tcl.tk/pub/tcl/tcl8_5/tk8.5.12-src.tar.gz

Extract both files into the same folder
Open Terminal
Cd to the extraction folder
type this in terminal:
make -C tcl8.5.12/macosx
then this:
make -C tk8.5.12/macosx
then this:
sudo make -C tcl8.5.12/macosx install
then this:
sudo make -C tk8.5.12/macosx install

Tcl and Tk should be updated to version 8.5.12. The old version will still be available on your system.

Any version past 8.5.12 will need Mac OS 10.5 or higher.

**Comment by mistydemeo** [comment]
Thanks! I'll take a look into this. I'm going to have a PowerMac G5 up and running within the next few months to provide me with an easier way to iterate on this stuff.

**Comment by miniupnp** [comment]
tcl-tk 8.6.6 doesnt even compile on my 10.5.8 (G4) : 
```
gcc-4.2 -c -Os -pipe    -Wall -fno-common -DBUILD_tk -I/private/tmp/tcl-tk--tk20170606-382-1z1gz4/tk8.6.6/unix/../unix -I/private/tmp/tcl-tk--tk20170606-382-1z1gz4/tk8.6.6/unix/../generic -I/private/tmp/tcl-tk--tk20170606-382-1z1gz4/tk8.6.6/unix/../bitmaps -I/private/tmp/tcl-tk20170606-382-p8k3jz/tcl8.6.6/generic -I/private/tmp/tcl-tk20170606-382-p8k3jz/tcl8.6.6/unix -I/private/tmp/tcl-tk--tk20170606-382-1z1gz4/tk8.6.6/unix/../macosx -I/private/tmp/tcl-tk--tk20170606-382-1z1gz4/tk8.6.6/unix/../xlib -DPACKAGE_NAME=\"tk\" -DPACKAGE_TARNAME=\"tk\" -DPACKAGE_VERSION=\"8.6\" -DPACKAGE_STRING=\"tk\ 8.6\" -DPACKAGE_BUGREPORT=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DUSE_THREAD_ALLOC=1 -D_REENTRANT=1 -D_THREAD_SAFE=1 -DHAVE_PTHREAD_ATTR_SETSTACKSIZE=1 -DHAVE_PTHREAD_ATFORK=1 -DTCL_THREADS=1 -DMODULE_SCOPE=extern\ __attribute__\(\(__visibility__\(\"hidden\"\)\)\) -DHAVE_HIDDEN=1 -DMAC_OSX_TCL=1 -DHAVE_COREFOUNDATION=1 -DHAVE_CAST_TO_UNION=1 -DTCL_SHLIB_EXT=\".dylib\" -DNDEBUG=1 -DTCL_CFG_OPTIMIZED=1 -DTCL_WIDE_INT_TYPE=long\ long -DHAVE_STRUCT_STAT64=1 -DWORDS_BIGENDIAN=1 -DHAVE_SYS_TIME_H=1 -DTIME_WITH_SYS_TIME=1 -DHAVE_INTPTR_T=1 -DHAVE_UINTPTR_T=1 -DHAVE_PW_GECOS=1 -DHAVE_AVAILABILITYMACROS_H=1 -DHAVE_WEAK_IMPORT=1 -D_DARWIN_C_SOURCE=1 -DMAC_OSX_TK=1      -DTCL_NO_DEPRECATED -std=gnu99 -x objective-c -DUSE_TCL_STUBS -DTK_LIBRARY=\"/usr/local/Cellar/tcl-tk/8.6.6_1/lib\" \
	    /private/tmp/tcl-tk--tk20170606-382-1z1gz4/tk8.6.6/unix/../macosx/tkMacOSXInit.c
/private/tmp/tcl-tk--tk20170606-382-1z1gz4/tk8.6.6/unix/../macosx/tkMacOSXInit.c:60: error: synthesized property ‘poolProtected’ must either be named the same as a compatible ivar or must explicitly name an ivar
make: *** [tkMacOSXInit.o] Error 1

```

**Comment by programmingkidx** [comment]
I vote to change the supplied version of tcl-tk to 8.5.12.

Here is more detailed information on building tcl-tk on Mac OS 10.4: http://wiki.tcl.tk/48516

**Comment by programmingkidx** [comment]
Oops. I meant to say I vote for tcl-tk version 8.5.11.

**Comment by superdave** [comment]
The tcl-tk 8.6.6 build from Tigerbrew is also breaking on 10.6 (looks like a parse error, though I haven't bothered to dig in yet). Just reporting for now, I might try the above patch out and/or revert to 8.5.12 later. Would a PR help once a solution is found?

**Comment by cymraegish** [comment]
Having this problem today as well, in G4 10.5; I'd already built tcl-tk myself from source v 8.5.6, I was worried brew python wouldn't link against it, but it did so I'm OK for now. Is there a chance 8.6.3 might work? I have a starkit (self contained tcltk) app that works here, basedon that version. 
I believe that in order to use python with tkinter one must delete and reinstall python if tcl-tk is updated, isn't that correct? By the way, for me the best way to check python tkinter is to start up idle! (also lets you s ee to make sure you are linking to the version of tcl-tk you wanted).

Is there a reason why no patch or (automated) workaround yet? would it help if I resubmit bug report (have collect all the data to do so).  Seems like people want to work on the bug could be the unstable branch?

**Comment by cymraegish** [comment]
Have an extra powerbook so might / could try build tcltk 8.6.3 from upstream source and then install brew python on top to see what happens...

**Comment by cymraegish** [comment]
i just built 8.6.3 tcl from source on 10.5 -- it won't load basic sqlite3:
% package require sqlite3
dlopen(/Library/Tcl/sqlite3.8.7.1/libsqlite3.8.7.1.dylib, 6): Symbol not found: _access
  Referenced from: /Library/Tcl/sqlite3.8.7.1/libsqlite3.8.7.1.dylib
  Expected in: /Library/Tcl/sqlite3.8.7.1/libsqlite3.8.7.1.dylib

% info patchlevel 
8.6.3

**Comment by POTSandSTOP** [comment]
I've got 10.5.8 (G4) also and am running into the same issues so would like to cast my vote for a Tigerbrew solution.

**Comment by sevan** [comment]
Try with PR #937 #938 installed

In `tclsh` on Tiger, ppc I get
```
% package require sqlite3
3.40.0
```

**Comment by mistydemeo** [comment]
Merged that PR, so I think this is fixed now.
