### ISSUE TITLE
Mp4v2 not found

### ISSUE THREAD

**Issue by mrkapqa** [mistydemeo/tigerbrew#435]
when trying to install CMUS

brew install cmus
==> Installing dependencies for cmus: pkg-config, libao, mad, libogg, lib
==> Installing cmus dependency: pkg-config
==> Downloading https://ia902307.us.archive.org/31/items/tigerbrew/pkg-config-0.
###### ################################################################## 100.0%

==> Pouring pkg-config-0.28.leopard_altivec.bottle.tar.gz
/usr/local/Cellar/pkg-config/0.28: 10 files, 632K

...

==> Downloading https://mp4v2.googlecode.com/files/mp4v2-2.0.0.tar.bz2

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "mp4v2"
Download failed: https://mp4v2.googlecode.com/files/mp4v2-2.0.0.tar.bz2

**Comment by mrkapqa** [comment]
The correnct link seems to be

https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/mp4v2/mp4v2-2.0.0.tar.bz2

How can Homebrew/Tigerbrew be actualized accordingly?

Thanks

**Comment by mistydemeo** [comment]
Fixed; thanks for the report!
