### ISSUE TITLE
ghostscript install fails at jbig2dec  "Error: SHA256 mismatch"

### ISSUE THREAD

**Issue by o2plus** [mistydemeo/tigerbrew#438]
==> Installing ghostscript dependency: jbig2dec
==> Downloading http://downloads.ghostscript.com/public/jbig2dec/jbig2dec-0.12.tar.gz
###### ################################################################## 100.0%

==> Downloading http://git.ghostscript.com/?p=jbig2dec.git;a=commitdiff_plain;h=70c7f1967f43a94f9f0d6808d6ab5700a120d2fc
###### ################################################################## 100.0%

Error: SHA256 mismatch
Expected: 5239e4eb991f198d2ba30d08011c2887599b5cead9db8b1d3eacec4b8912c2d0
Actual: 9cae6f2154b3e6270932a2f995c156cd49aa0e95296a3fbd088dbc448fc210b1
Archive: /Library/Caches/Homebrew/jbig2dec--patch-5239e4eb991f198d2ba30d08011c2887599b5cead9db8b1d3eacec4b8912c2d0.git;a=commitdiff_plain;h=70c7f1967f43a94f9f0d6808d6ab5700a120d2fc
To retry an incomplete download, remove the file above.
NOTE that this error repeats, even after the cache is flushed, on both 10.4.11 and 10.5.8

**Comment by dcwar** [comment]
Looks like the formula needs to be patched - the URL changed

URL is now https://raw.githubusercontent.com/Homebrew/formula-patches/7dc28b82/jbig2dec/bug-695890.patch

**Comment by o2plus** [comment]
The referenced change to the URL for the patch in jbig2dec.rb allowed the installation of jbig2dec and the other dependencies to complete, but the actual install of ghostscript failed (see below) because the URL for ghostscript-9.16.tar.gz has also changed.  I found it at [http://downloads.ghostscript.com/public/old-gs-releases/ghostscript-9.16.tar.gz] .  To fix this, I didn't actually edit the ghostscript.rb formula, but rather copied the downloaded ghostscript-9.16.tar.gz into /Library/Caches/Homebrew and did another "brew install ghostscript", which completed without complaint:
"/usr/local/Cellar/ghostscript/9.16: 710 files, 58M, built in 7.9 minutes"
Thank you!

****** ghostscript error message ***
==> Installing ghostscript
==> Downloading http://downloads.ghostscript.com/public/ghostscript-9.16.tar.gz
curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "ghostscript"
Download failed: http://downloads.ghostscript.com/public/ghostscript-9.16.tar.gz
