### ISSUE TITLE
undefined method `rebuild'

### ISSUE THREAD

**Issue by bryancn** [mistydemeo/tigerbrew#439]
A number of the issues reported here (eg with PHP versions) appear to stem from the [name change of the bottle revision method in Homebrew to rebuild](https://github.com/Homebrew/brew/pull/731). Because this is not implemented in Tigerbrew, anything that uses rebuild throws an error.
Does anyone active here have the capability to fix this?

**Comment by mistydemeo** [comment]
Can you `brew update` and see if that's fixed?

**Comment by bryancn** [comment]
brew update
Already up-to-date.
brew install php56
==> Installing php56 from homebrew/homebrew-php
Error: undefined method `rebuild' for #<BottleSpecification:0x1a9c8>

**Comment by mistydemeo** [comment]
Sorry, I forgot `BottleSpecification` doesn't subclass `SoftwareSpec`. Try again?

**Comment by bryancn** [comment]
That seems to do it. Compiling now…

**Comment by bryancn** [comment]
Success! Thanks so much.

**Comment by mistydemeo** [comment]
You're welcome! Sorry for not fixing this sooner.
