### ISSUE TITLE
Ghostscript failed to build on 10.4.11

### ISSUE THREAD

**Issue by o2plus** [mistydemeo/tigerbrew#443]
"brew install ghostscript" failed with "make: *** [obj/gssprintf_0.o] Error 1" on a G5 running 10.4.11.  The outputs of HOMEBREW_MAKE_JOBS=1 VERBOSE=1 brew install ghostscript, the highest-numbered log file (02.make), and brew doctor are in this gist:
[https://gist.github.com/o2plus/63a3c0908ae85b4f773401839f476d6b.js]

Two additional points regarding the tigerbrew ghostscript install:
1.  The formula  **jbig2dec.rb** needed to be edited to update the url for the patch:
    _patch do
    url "https://raw.githubusercontent.com/Homebrew/formula-patches/7dc28b82/jbig2dec/bug-_695890.patch"
2.  The formula  **ghostscript.rb** needed to be edited to update the url for the tarball:
   _stable do
    url "http://downloads.ghostscript.com/public/old-gs-releases/ghostscript-9.16.tar.gz"_
Is there someway to get these two formulas updated in the repository?

Thank you in advance for any help for getting ghostscript installed.

**Comment by mistydemeo** [comment]
Fixed, thank you for the report!
