### ISSUE TITLE
(cmus) libcue fails to download / / leopard 10.5.8

### ISSUE THREAD

**Issue by mrkapqa** [mistydemeo/tigerbrew#445]
==> Installing cmus dependency: libcue
==> Downloading https://downloads.sourceforge.net/project/libcue/libcue/1.4.0/li

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "libcue"
Download failed: https://downloads.sourceforge.net/project/libcue/libcue/1.4.0/libcue-1.4.0.tar.bz2

Thanks

**Comment by mistydemeo** [comment]
Fixed!
