### ISSUE TITLE
openssl failed to build/install on 10.5.8

### ISSUE THREAD

**Issue by armadsen** [mistydemeo/tigerbrew#448]
openssl fails to build on my iMac G4 running 10.5.8. Here's a gist with the requested info (there was no log for openssl in ~/Library/Logs/Homebrew): https://gist.github.com/armadsen/a27559c2259ef402351dc7b7c871ac22

Note that this is for a plain `brew install openssl`, but I'm actually trying to `brew install git`, which fails due to the failure when installing the openssl dependency.

**Comment by mistydemeo** [comment]
Fixed, sorry about that!

**Comment by armadsen** [comment]
Thanks for the super quick fix!
