### ISSUE TITLE
intltool failed to build on 10.4

### ISSUE THREAD

**Issue by programmingkidx** [mistydemeo/tigerbrew#449]
When trying to install intltool, brew fails with this error message:
checking for XML::Parser... configure: error: XML::Parser perl module is required for intltool

**Comment by programmingkidx** [comment]
This is the solution I found here: http://www.linuxquestions.org/questions/programming-9/can't-locate-xml-parser-pm-577422/
1. change to root 
 sudo su
2. bring up CPAN tool
 perl -e shell -MCPAN
3. install module
 install XML::Parser

**Comment by programmingkidx** [comment]
'brew install intltool' worked after fixing the XML::Parser problem.

**Comment by mistydemeo** [comment]
I'll look at vendoring the module so it "just works".

**Comment by programmingkidx** [comment]
Thank you.

**Comment by evanmiller** [comment]
To get @programmingkidx's instructions to work I had to point Perl at my copy of Expat, and also at a newer GCC (but not too new, or else you'll get `unrecognized command line option '-no-cpp-precomp'`).

These commands starting with a user shell worked for me:

```
user$ brew install expat
user$ sudo -s
root# EXPATLIBPATH=/path/to/TigerBrew/lib EXPATINCPATH=/path/to/TigerBrew/include cpan
cpan> o conf makepl_arg "CC=/path/to/TigerBrew/bin/gcc-4.2"
cpan> o conf commit
cpan> install XML::Parser
cpan> quit
root# exit
user$ brew install intltool
```
