### ISSUE TITLE
gobject-introspection failed to build on 10.4

### ISSUE THREAD

**Issue by programmingkidx** [mistydemeo/tigerbrew#451]
Saw this error when installing:

checking for python version... 2.7
checking for python platform... darwin
checking for python script directory... ${prefix}/lib/python2.7/site-packages
checking for python extension module directory... ${exec_prefix}/lib/python2.7/site-packages
checking for headers required to compile python extensions... ./configure: line 1: /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/python-config: No such file or directory
not found
configure: error: Python headers not found

I have both python 2.7 and 3.5.0 installed. Python 2.7 was installed using a install package from Python's web site. This package does not appear to have the development libraries installed. According to the Gobject Introspection web site, it's package is not compatible with Python 3 yet.

**Comment by mistydemeo** [comment]
Looks like it's prioritizing that Python over the Tigerbrew-installed version, which does have the development packages. Mind trying to move the `/Library` version temporarily out of place and see if that fixes it?

**Comment by programmingkidx** [comment]
I completely removed the Python 2.7 by following the directions here: http://stackoverflow.com/questions/3819449/how-to-uninstall-python-2-7-on-a-mac-os-x-10-6-4. This made installation of gobject-introspection actually work. Thanks.

**Comment by miniupnp** [comment]
so this is not really a bug and can be closed ? :)

**Comment by programmingkidx** [comment]
I believe so.
