### ISSUE TITLE
SVN 1.8.13 will not run on Mac OS 10.4 due to missing dylib

### ISSUE THREAD

**Issue by programmingkidx** [mistydemeo/tigerbrew#453]
After running 'brew install svn', I tried to run svn. It failed to run because of a missing dylib. Here is the error message:
dyld: Library not loaded: /usr/local/opt/apr-util/libexec/lib/libaprutil-1.0.dylib
  Referenced from: /usr/local/Cellar/subversion/1.8.13/bin/./svn
  Reason: image not found
Trace/BPT trap

Host info: Mac OS 10.4.11.

**Comment by mistydemeo** [comment]
Do you have `apr-util` installed?

**Comment by programmingkidx** [comment]
On Jan 12, 2017, at 12:51 AM, Misty De Meo wrote:

> Do you have apr-util installed?
>

I do not.

**Comment by programmingkidx** [comment]
After installing apr-util, Subversion now works. I suggest updating the formula for svn to include apr-util.

**Comment by mistydemeo** [comment]
Fixed, thanks for the report!
