### ISSUE TITLE
OpenSSL 1.0.2j failed to build on 10.5.8 on g5_64

### ISSUE THREAD

**Issue by jsonnenb** [mistydemeo/tigerbrew#462]
OpenSSL failed to compile on a fresh install of 10.5.8 on a dual 2.0 GHz G5.

In short ppccpuid doesn't know what to do with ppc970-64. The last version of Open SSL that I had compiled on this machine was 1.0.2d1.

Full details on here:
https://gist.github.com/jsonnenb/c9d910dbd8cae3430dffed60edc136cf

**Comment by jsonnenb** [comment]
This issue also prevents "brew update" from working on a new install since curl and git are now updated as part of the brew update mechanism.

**Comment by programmingkidx** [comment]
It fails for me on Mac OS 10.4 on a PowerPC G5. Here is the error message:
ln -s ../Cellar/openssl/1.0.2j/lib/libcrypto.dylib libcrypto.dylib
ln -s ../Cellar/openssl/1.0.2j/lib/libcrypto.a libcrypto.a
ln -s ../Cellar/openssl/1.0.2j/lib/libcrypto.1.0.0.dylib libcrypto.1.0.0.dylib
ln -s ../Cellar/openssl/1.0.2j/lib/engines engines
Error: wrong number of arguments (3 for 1)

**Comment by programmingkidx** [comment]
I found out that OpenSSL 1.0.2k actually builds on Tiger. Misty I suggest upgrading the formula to use this version instead.

**Comment by programmingkidx** [comment]
Here is the file: https://www.openssl.org/source/openssl-1.0.2k.tar.gz

**Comment by miniupnp** [comment]
and what about 1.0.2l ?

**Comment by sevan** [comment]
v1.1.1v is now in Tigerbrew.
