### ISSUE TITLE
git failed to build on 10.4 - can't find gtar command

### ISSUE THREAD

**Issue by programmingkidx** [mistydemeo/tigerbrew#464]
When trying to build git I saw this error message: 

install -d -m 755 '/usr/local/Cellar/git/2.10.2/share/git-core/templates'
(cd blt && /usr/local/Cellar/gnu-tar/1.28/bin/gtar cf - .) | \
(cd '/usr/local/Cellar/git/2.10.2/share/git-core/templates' && umask 022 && /usr/local/Cellar/gnu-tar/1.28/bin/gtar xof -)
/bin/sh: line 1: /usr/local/Cellar/gnu-tar/1.28/bin/gtar: No such file or directory

The simple fix to this problem is to look for 'tar' instead. That is the only command in that folder.

**Comment by mistydemeo** [comment]
Did you install gnu-tar with `--with-default-names`?

**Comment by programmingkidx** [comment]
I don't even remember installing the tar command. It might have been installed as a prerequisite for something else.

**Comment by mistydemeo** [comment]
What's the output of `brew info gnu-tar`?

**Comment by programmingkidx** [comment]
gnu-tar: stable 1.28
GNU version of the tar archiving utility
https://www.gnu.org/software/tar/
/usr/local/Cellar/gnu-tar/1.28 (15 files, 1.7M) *
  Built from source with: --with-default-names
From: https://github.com/mistydemeo/tigerbrew/blob/master/Library/Formula/gnu-tar.rb
==> Options
--with-default-names
        Do not prepend 'g' to the binary
==> Caveats
gnu-tar has been installed as "gtar".

If you really need to use it as "tar", you can add a "gnubin" directory
to your PATH from your bashrc like:

    PATH="/usr/local/opt/gnu-tar/libexec/gnubin:$PATH"

**Comment by programmingkidx** [comment]
I fixed this problem by just making a symbolic link to tar and calling it gtar.

**Comment by sevan** [comment]
This should be resolved with the latest version.
