### ISSUE TITLE
Ruby 2.2.3 will not build on i386 Tiger

### ISSUE THREAD

**Issue by mistydemeo** [mistydemeo/tigerbrew#473]
https://gist.github.com/14fa08329609ac8132538c054bec33f7

Relevant part, from signal.c:

```
compiling signal.c
signal.c: In function ‘check_stack_overflow’:
signal.c:778: error: ‘struct mcontext’ has no member named ‘__ss’
make: *** [signal.o] Error 1
```

The code in question:

```c
# elif defined __APPLE__
#   if defined(__LP64__)
    const uintptr_t sp = mctx->__ss.__rsp;
#   else
    const uintptr_t sp = mctx->__ss.__esp;
#   endif
```

**Comment by ranma42** [comment]
On Tiger the members of the `mcontext` struct are not preceded by `__` (i.e. that struct member is named `ss` on Tiger i386): https://github.com/phracker/MacOSX-SDKs/blob/2d31dd8bdd670293b59869335d9f1f80ca2075e0/MacOSX10.5.sdk/usr/include/i386/_structs.h
