### ISSUE TITLE
QEMU build issue - INT64_C() not declared

### ISSUE THREAD

**Issue by programmingkidx** [mistydemeo/tigerbrew#494]
When building QEMU on Mac OS 10.4.11, I saw this error message: 
/private/tmp/qemu20170423-13118-3m9tys/qemu-2.4.0.1/disas/libvixl/utils.h:47:28: error: 'INT64_C' was not declared in this scope
   int64_t limit = INT64_C(1) << (n - 1);

I have gcc 5.2 installed on my system.

**Comment by mistydemeo** [comment]
`INT64_C` is defined in `stdint.h`. That's not explicitly `#include`d; probably the macro is indirectly included by something else on newer versions of OS X, and no one noticed.

**Comment by mistydemeo** [comment]
Hm, actually, libvixl's `globals.h` does `#include <stdint.h>`, and `utils.h` does `#include "globals.h"`

**Comment by programmingkidx** [comment]
I tried out this test program and it worked:

file: globals.h
#include <stdint.h>

file: utils.h
#include "globals.h"

file: main.c
#include <stdio.h>
#include "utils.h"

int main (int argc, const char * argv[]) {
    int64_t value = INT64_C(0);
    printf("Value = %d\n", value);
    return 0;
}

**Comment by programmingkidx** [comment]
Looking at the qemu.rb file, I can see that it is not correct. First problem is there is no "--target-list=ppc-softmmu, i386-softmmu" sent to the configure command. Without this argument all emulators would be built. Definitely not what we want. Another problem is it tries to download a test image for an ARM emulator. Since this formula shouldn't build an ARM emulator, the image file should not be downloaded and used.

**Comment by ranma42** [comment]
Before C++11 it was suggested that the availability of those macros was made conditional on the presence of the `__STDC_CONST_MACROS` (see the notes [here](http://en.cppreference.com/w/cpp/types/integer)).
Adding `-D__STDC_CONST_MACROS` is sufficient to make some progress in the build, but then it fails on `ui/cocoa.m` because it is using some 10.5 APIs.

**Comment by mistydemeo** [comment]
Aha, I see the bug.

```c
/* "C++ implementations should define these macros only when
 *  __STDC_CONSTANT_MACROS is defined before <stdint.h> is included."
 */
#if (! defined(__cplusplus)) || defined(__STDC_CONSTANT_MACROS)

/* 7.18.4 Macros for integer constants */
#define INT8_C(v)    (v)
#define INT16_C(v)   (v)
#define INT32_C(v)   (v)
#define INT64_C(v)   (v ## LL)

#define UINT8_C(v)   (v ## U)
#define UINT16_C(v)  (v ## U)
#define UINT32_C(v)  (v ## U)
#define UINT64_C(v)  (v ## ULL)

#define INTMAX_C(v)  (v ## LL)
#define UINTMAX_C(v) (v ## ULL)

#endif /* if C++, then __STDC_CONSTANT_MACROS enables the above macros */
```

This is not being set on Tiger.

**Comment by mistydemeo** [comment]
Aha, yeah, I see we came to the same conclusion!

**Comment by mistydemeo** [comment]
I'm going to disable the cocoa UI on 10.4. I think we've reached the point it's not tenable to keep that going.
