### ISSUE TITLE
GCC 6 will not work without formula present

### ISSUE THREAD

**Issue by dcwar** [mistydemeo/tigerbrew#499]
Just updated my installation for the first time since December… and it appears that the GCC 6 formula has disappeared? I can't seem to compile using GCC 6 without the formula in Tigerbrew anymore. ( It is otherwise still compiled and installed on my system. ) Any suggestions?

**Comment by mistydemeo** [comment]
I'll import those packages from the former homebrew/versions - sorry for the inconvenience!
