### ISSUE TITLE
brew install curl fails

### ISSUE THREAD

**Issue by oboroc** [mistydemeo/tigerbrew#506]
I mentioned it in <https://github.com/mistydemeo/tigerbrew/issues/500>: after initial `ruby -e "$(curl -fsSkL raw.github.com/mistydemeo/tigerbrew/go/install)"` and `brew doctor`, I try to get new curl: `brew install curl`. This started failing yesterday evening and still not working today. I tested on PPC Tiger Server on Mac Mini G4, PPC Leopard on iMac G5 and on Intel Tiger VM. It seems curl bundled with Mac OS X is unable to download from `https://curl.haxx.se/download/curl-7.50.3.tar.bz2`. I just checked and I can download this file fine from modern browser.

I think it would work fine if you can switch to `http://curl.haxx.se/download/curl-7.50.3.tar.bz2`. You still have sha256 checksum to verify integrity.

Alternatively, please consider creating a simple boilerplate site `http://tigerbrew.github.io` and host mirrors of critical tarballs and may be bottled versions of key packages like curl, git, apple-gcc42, lld64 etc.

**Comment by oboroc** [comment]
Nope, changing https to http didn't work. I think web site redirects all http requests to https:

```
$ brew install curl
==> Downloading http://curl.haxx.se/download/curl-7.50.3.tar.bz2
==> Downloading from https://curl.haxx.se/download/curl-7.50.3.tar.bz2
curl: (35) error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
Error: Failed to download resource "curl"
Download failed: https://curl.haxx.se/download/curl-7.50.3.tar.bz2
```

**Comment by oboroc** [comment]
A lame workaround is to download `curl-7.50.3.tar.bz2` on a modern computer and then upload it over ssh to old Mac with tigerbrew and copy it over to `/Library/Caches/Homebrew`:

```
$ brew install curl
==> Downloading https://curl.haxx.se/download/curl-7.50.3.tar.bz2
Already downloaded: /Library/Caches/Homebrew/curl-7.50.3.tar.bz2
```

**Comment by oboroc** [comment]
I think switching download url to `https://github.com/curl/curl/archive/curl-7_50_3.tar.gz` and updating sha256 is enough to download new curl with the bundled old curl. Somehow github.com is less restrictive about using old SSL crypto then haxx.se

**Comment by mistydemeo** [comment]
> Alternatively, please consider creating a simple boilerplate site http://tigerbrew.github.io and host mirrors of critical tarballs and may be bottled versions of key packages like curl, git, apple-gcc42, lld64 etc.

This actually is the plan! Once my new hardware is up and running, I'll be distributing statically-built curl, openssl, git and ruby, and Tigerbrew will automatically fetch and use them.

Sorry for the inconvenience with this download - I recognize getting bootstrapped here is a real pain.

**Comment by oboroc** [comment]
No need to apologize! You have a normal job, so thank you for spending time during your leisure time on maintaining this awesome project! I'm having a blast messing around with those 12 year old PPC Macs, in part thanks to https://github.com/mistydemeo/tigerbrew

**Comment by wescpy** [comment]
Agreed. I've extended the lifetime of my computer thx to TigerBrew and a bunch of other updates I made in 2015:
* 6GB RAM (undocumented but supported)
* 600GB SSD
* Snow Leopard 10.6.8
* New battery﻿

**Comment by dcwar** [comment]
What tends to be an issue when using https are the outdated certs on vintage systems. I've had to fix this myself on several systems, but keep forgetting to document exactly how I did so. Perhaps this can be one of the first steps in a Tigerbrew install, @mistydemeo ?

**Comment by djdrzzy** [comment]
This is a funky workaround as well! (Using a bunch of the previous comments for inspiration...)

$ brew install wget
$ wget https://curl.haxx.se/download/curl-7.50.3.tar.bz2
$ mv curl-7.50.3.tar.bz2 /Library/Caches/Homebrew/
$ brew install curl

On OS X 10.5.8

**Comment by mistydemeo** [comment]
Added an HTTP mirror, so it should fall back to that when the main download fails.

**Comment by ssb22** [comment]
The above workaround is not currently working on Homebrew/homebrew-core (git revision ba42c; last commit 2018-02-16) on Mac OS 10.7.5 (Intel; don't know about tigerbrew but posting here in case it's useful as this issue tends to turn up in Homebrew searches too): both `brew install curl` and `brew update` tries to fetch curl-7.58.0 even if there is already a `curl-7.58.0.tar.bz2` in `/Library/Caches/Homebrew`.  However, it *did* work when I put the `tar.bz2` file into `$HOME/Library/Caches/Homebrew` as directed by `brew --cache -s curl`.  But then it failed on curl configure's `checking run-time libs availability`.  So I did `brew install curl --debug`, chose option 5 (shell), did `nano configure`, found `macosx-version-min` and changed it from 10.8 to 10.7, did `grep ./configure config.log |head -1` and ran that command, `exit` and chose option 2 (ignore). Homebrew then did the `make install`.

**Comment by AlisterH** [comment]
Hi guys, is this expected?:
````
==> Downloading from https://curl.askapache.com/curl-7.56.0.tar.bz2
curl: (35) error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
Error: Failed to download resource "curl"
Download failed: http://curl.askapache.com/download/curl-7.56.0.tar.bz2
