### ISSUE TITLE
After updating Tigerbrew, all brew commands fail w/ "RUBY_PATCHLEVEL (NameError)" (10.4/G4)

### ISSUE THREAD

**Issue by dcwar** [mistydemeo/tigerbrew#514]
Just performed `brew update --verbose`. Went from 7c33bcb..a460f2d.

Now, brew is essentially broken - every brew command returns the following error:

/usr/local/Library/Homebrew/global.rb:48:` uninitialized constant RUBY_PATCHLEVEL (NameError)
	from /usr/local/Library/brew.rb:16:in `require'
	from /usr/local/Library/brew.rb:16

**Comment by dcwar** [comment]
Console output -
https://gist.github.com/dcwar/dee9866955a3519dc44fea995608920b

Note that I'd forgotten to delete the gcc6 formula I'd temporarily had in place.

**Comment by mistydemeo** [comment]
Sorry about that, this was something I missed when backporting some Homebrew features. I just pushed a hotfix; can you do a manual `git pull` then try again?

**Comment by dcwar** [comment]
That's it! Thanks so very much!!!

**Comment by mistydemeo** [comment]
Great, glad to hear it! Sorry for the inconvenience.

**Comment by dcwar** [comment]
No worries!
