### ISSUE TITLE
QEMU SHA256 mismatch

### ISSUE THREAD

**Issue by LarBob** [mistydemeo/tigerbrew#521]
I'm trying to install Qemu on Leopard to no avail.
Here's what I get:
$ brew install qemu
==> Downloading http://wiki.qemu-project.org/download/qemu-2.4.0.1.tar.bz2
Already downloaded: /Library/Caches/Homebrew/qemu-2.4.0.1.tar.bz2
==> Downloading https://github.com/qemu/qemu/commit/365d7f3c7aacc789ead96b8eeb5b
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 0b32b6af97d7079302ee4a76699ffe232b4121f5488079b8e757161170cea0d9
Actual: c65c75b8921a116b0829cb5bbdf6727942e34cf3038e910b4df6fb9c53bdae2f
Archive: /Library/Caches/Homebrew/qemu--patch-0b32b6af97d7079302ee4a76699ffe232b4121f5488079b8e757161170cea0d9.patch
To retry an incomplete download, remove the file above.

I have tried removing the file to no avail. I've also brew update-d.

**Comment by mistydemeo** [comment]
Should be fixed - thanks for the report!
