### ISSUE TITLE
QEMU not working/freezing

### ISSUE THREAD

**Issue by LarBob** [mistydemeo/tigerbrew#523]
Hi, I've installed QEMU on my 2x2.0 GHz G5 machine and it almost always freezes at the SeaBIOS (version rel-1.8.2-0-g33fbe13 by qemu-project.org screen). I'm wondering if this is due to some saying that versions past 2.2.0 don't work on pre-10.6 systems due to this:
"Okay, okay, this is the PowerPC equivalent of a stupid pet trick, but this is qemu 2.2.1 (the last version that did not require thread-local storage, which won't work with OS X 10.6 and earlier)"
(Taken from a page written by the developer of TenFourFox: http://tenfourfox.blogspot.com/2017/02/4580b1-available-with-user-agent.html)

So most people install 2.2.0 through MacPorts 2.3.4, should that be what's happening here or is there just something wrong with my install? Does 2.4.0.1 work on other machines that installed it using tigerbrew?

I've tried a lot of different launch options, but no matter what variation I use the same issue happens.

**Comment by LarBob** [comment]
Sure enough, I followed this and it works perfectly:
https://forums.macrumors.com/threads/inaugural-summer-powerpc-challenge-july-1-8-2017.2040025/page-14#post-24769448
I think 2.2.0 is necessary.

**Comment by mistydemeo** [comment]
It may be possible to backport these features by compiling the entire dependency tree with a newer compiler, but there's a lot of pain down that path. Going back to 2.2.1 is probably the easiest solution.
