### ISSUE TITLE
Installing an Old Version of XCode With TigerBrew

### ISSUE THREAD

**Issue by davidpgil** [mistydemeo/tigerbrew#534]
I just reinstalled my old Macbook Pro with OSX Snow Leopard. I thought I would be able to use TigerBrew to still install some old software via CLI. I want to install Git but I get a message that I don't have XCode, but the latest XCode does not work with Snow Leopard.

Have any idea how I can solve this?

**Comment by mistydemeo** [comment]
Apple still makes older versions of Xcode available! If you go to https://developer.apple.com/download/more/, you can search for Xcode 3.2.6 - the last release for Snow Leopard. Doesn't require a paid developer account.

**Comment by mistydemeo** [comment]
Great! Closing this unless you have any other trouble with Xcode then.
