### ISSUE TITLE
curl failed to build on 10.6.8

### ISSUE THREAD

**Issue by Isabella233** [mistydemeo/tigerbrew#537]
When I try "brew install anything" I get the error: 

curl: (77) error setting certificate verify locations:
  CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none

I pasted the output of 
1) HOMEBREW_MAKE_JOBS=1 VERBOSE=1 brew install curl
2) 02.make in ~/Library/Logs/Homebrew/curl
3) brew doctor
https://gist.github.com/Isabella233/53029a07251650ac151d78ce00103680

Thank in advance for the help

I'm not sure I post this issue in the right section

**Comment by mistydemeo** [comment]
Noticed this in your `brew doctor` output:

```
Warning: You have a curlrc file
If you have trouble downloading packages with Tigerbrew, then maybe this
is the problem?
```

It looks like you probably have a `.curlrc` in your home directory. It looks like that's interfering with curl's `CAfile` paths.

**Comment by Isabella233** [comment]
Thank you and sorry for the silly question, I'm very new to all this.

**Comment by mistydemeo** [comment]
Not a silly question at all! Did that fix things for you?

**Comment by Isabella233** [comment]
Yes, completely! :)

**Comment by mistydemeo** [comment]
Great, glad to hear it! Let me know if you have any other problems.
