### ISSUE TITLE
timedog no longer available on Google Code

### ISSUE THREAD

**Issue by mmolinac** [mistydemeo/tigerbrew#540]
The following command no longer works:

    brew install timedog

and is because of this:

https://code.google.com/archive/p/timedog/issues/11

Now it's available from here:

https://github.com/nlfiedler/timedog

And the file pointed by current tigerbrew recipe should be this:

https://github.com/nlfiedler/timedog/archive/v1.3.zip

However, current version is 1.4.

**Comment by mistydemeo** [comment]
Thanks for the heads up! Fixed in #541.
