### ISSUE TITLE
timedog no longer available on Google Code

### ISSUE THREAD

**Issue by mmolinac** [mistydemeo/tigerbrew#542]
The following command no longer works:

    brew install unar

It is because Google Code is no longer running, so the following URI cannot be found:

https://theunarchiver.googlecode.com/files/unar1.8.1_src.zip

Instead, the sources can be downloaded from:

https://wakaba.c3.cx/releases/TheUnarchiver/unar1.8.1_src.zip

However, a newer version can be found at:

https://wakaba.c3.cx/releases/TheUnarchiver/unar1.10.1_src.zip

**Comment by mistydemeo** [comment]
Thanks for the report! Fixed.
