### ISSUE TITLE
I cannot install MySQL through tigerbrew

### ISSUE THREAD

**Issue by KudoLayton** [mistydemeo/tigerbrew#546]
I want to install MySQL but when I try to do it, I get only '404 not found error' like this.
```
curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "mysql"
Download failed: https://cdn.mysql.com/Downloads/MySQL-5.6/mysql-5.6.35.tar.gz
```
My brew version is __0.9.5__ and git revision is __'9a9e5'__ (commit date is 2017-12-14)

**Comment by mistydemeo** [comment]
Fixed - thanks for the report, and sorry for the delay in responding!
