### ISSUE TITLE
gcc not compiling on 10.5.8

### ISSUE THREAD

**Issue by mmolinac** [mistydemeo/tigerbrew#551]
I tried to install gcc on my PowerMac G4 / Mac OS X 10.5.8 and got an error.

    HOMEBREW_MAKE_JOBS=1 VERBOSE=1 brew install gcc

Submitted the corresponding gist:

    brew gist-logs gcc

And this is it: https://gist.github.com/2d428c1a32bcb40f433f340eba858c59

**Comment by mistydemeo** [comment]
This should be fixed by #552!
