### ISSUE TITLE
libpcap does not build on 10.4 with system flex/bison

### ISSUE THREAD

**Issue by nekonoir** [mistydemeo/tigerbrew#574]
Temporarily linking keg-only versions allowed for successful build.

Can we 
a) put flex/bison as dependencies on Tiger
b) modify the libpcap formula to use the brew versions without having to do the link/unlink dance?

**Comment by mistydemeo** [comment]
Should be fixed now - thanks for the report!

> modify the libpcap formula to use the brew versions without having to do the link/unlink dance?

This is automatically set up when formulas are marked as dependencies!
