### ISSUE TITLE
GCC make, still running after an all nighter

### ISSUE THREAD

**Issue by LostAccount** [mistydemeo/tigerbrew#578]
Hello

New Install GCC takes a VERY long time to 'make', it appears to just sit there, it's been running all night. Is there a way to install a precompiled GCC?

`brew install gcc
Powerbook-G4-17:/usr/local/Library **alex$** brew install gcc
==> Downloading https://ftp.gnu.org/gnu/gcc/gcc-7.2.0/gcc-7.2.0.tar.xz
Already downloaded: /Users/alex/Library/Caches/Homebrew/gcc-7.2.0.tar.xz
==> Downloading https://gist.githubusercontent.com/mistydemeo/9c5b8dadd892ba3197a9cb431295cc83/raw/582d1ba135511272f726
Already downloaded: /Users/alex/Library/Caches/Homebrew/gcc--patch-17afaf7daec1dd207cb8d06a7e026332637b11e83c3ad552b4cd32827f16c1d8.patch
==> Downloading https://raw.githubusercontent.com/macports/macports-ports/master/lang/gcc7/files/patch-darwin-ppc-2017-
Already downloaded: /Users/alex/Library/Caches/Homebrew/gcc--patch-98dfb57c9d08430c9656b2afa8967937c3f146b9bb21ac79129ac1cb2c9a4642.diff
==> Patching
patching file gcc/jit/Make-lang.in
patching file gcc/jit/jit-playback.c
Hunk #1 succeeded at 2473 with fuzz 2 (offset 57 lines).
==> Applying sysdep-unix-tiger-intel.patch
patching file libcilkrts/runtime/sysdep-unix.c
==> Applying patch-darwin-ppc-2017-01-msg02971.diff
patching file gcc/config/rs6000/darwin.h
patching file gcc/config/rs6000/altivec.md
patching file gcc/config/rs6000/predicates.md
patching file fixincludes/fixincl.x
patching file fixincludes/inclhack.def
patching file gcc/ada/adaint.c
==> ../configure --build=powerpc-apple-darwin8.11.0 --prefix=/usr/local/Cellar/gcc/7.2.0 --libdir=/usr/local/Cellar/gcc
==> make`

**Specs**
**Powerbook G4 15GHz PPC7450, Mac OS X 10.4.11 No updates pending. Xcode 2.5**

After installing Tigerbrew, I went ahead to install fish.

`Powerbook-G4-17:/usr/local/Library **alex$** brew install fish
Error: fish cannot be built with any available compilers.
To install this formula, you may need to either:
  brew install apple-gcc42
or:
  brew install gcc
Powerbook-G4-17:/usr/local/Library **alex$**`

I ran brew update and brew doctor in an effort to help

`Powerbook-G4-17:/usr/local/Library **alex$** brew doctor
Please note that these warnings are just used to help the Tigerbrew maintainers
with debugging if you file an issue. If everything you use Tigerbrew for is
working fine: please don't worry and just ignore them. Thanks!`

`Warning: You have uncommitted modifications to Tigerbrew
If this a surprise to you, then you should stash these modifications.
Stashing returns Tigerbrew to a pristine state but can be undone
should you later need to do so for some reason.
    cd /usr/local/Library && git stash && git clean -d -f
Powerbook-G4-17:/usr/local/Library **alex$** cd /usr/local/Library && git stash && git clean -d -f
No local changes to save
Removing Homebrew/vendor/portable-curl/
Removing Homebrew/vendor/portable-ruby/
Powerbook-G4-17:/usr/local/Library **alex$** cd /usr/local/Library && git stash && git clean -d -f
No local changes to save
Powerbook-G4-17:/usr/local/Library Alex$`

Would appreciate some advice. My apologies if my report is incomplete. If it is please let me know what else you need and I will respond asap.

NOTE: I am not using the computer as it runs make but I did run top to see what is going on, a command named cc1 intermittently appears at about 80% CPU. It doesn't appear take up any CPU for about 2-3 seconds and then returns with a consumption of about 80% CPU.

Kind regards
—Alex Santos

**Comment by LostAccount** [comment]
Quick update, it looks like this time it did finish. It took 578.6 minutes. I had no idea that it could be so intensive.

**Comment by LostAccount** [comment]
Ran gcc -v
gcc version 4.0.1 (Apple Computer, Inc. build 5370)

which gcc
/usr/bin/gcc

Ok looks good but I guess fish won't install, maybe it's not compatible with 10.4 or PPC.

Thanks

**Comment by mistydemeo** [comment]
> Is there a way to install a precompiled GCC?

I'm planning on adding this at some point - like you noted, the build time is obscenely long. :| Sorry about that!

> Ok looks good but I guess fish won't install, maybe it's not compatible with 10.4 or PPC.

It should be - that's an environment I often use it in myself. Would you mind opening an issue with the debugging output? I'd be happy to help fix that!
