### ISSUE TITLE
[Hack] Fix for SHA256 mismatch on G3 hardware

### ISSUE THREAD

**Issue by VKoskiv** [mistydemeo/tigerbrew#593]
First of all @mistydemeo et al, huge thanks for maintaining this fork! This project makes playing around with old PowerPC Macs a blast!

My setup:
G3 PowerBook3,1 (Firewire) 400MHz
Mac OS X 10.4.11

I've been having this weird issue where on every package/dependency/resource, the install fails due to a SHA256 mismatch.
I wasn't able to find the root cause for this, so I was forced to edit every formula and replace the hashes by hand.

Just today I hacked together a (probably terrible) and temporary solution to this problem: Disabling the SHA256 checks entirely.

I've never written a line of Ruby, so apologies for the crudeness of the implementation.

### To disable SHA256 checks, comment out the following lines with a `#` character at the beginning of the line.

`/usr/local/Library/Homebrew/resource.rb` line **80**
`/usr/local/Library/Homebrew/patch.rb` line **165**
`/usr/local/Library/Homebrew/formula_installer.rb` line **712**

I just put this together in case someone else out there is having the same problem. Please close this issue if there is a better solution I missed!

**Comment by VKoskiv** [comment]
It seems this method no longer works after running `brew update` (Quite predictable!)

@mistydemeo Would it be possible to add a config/flag to disable the SHA256 check since it doesn't work at all on my config?

**Comment by VKoskiv** [comment]
Also, since running `brew update`, I now also get:

`Error: No such file or directory @ rb_sysopen - /Users/vkoskiv/Library/Caches/Homebrew/<package>`

This happens on every package. Works fine if I manage to find the file and manually place it there.

**Comment by mistydemeo** [comment]
Would you be willing to give me shell access? I'd like to diagnose this and fix the problem for real.

**Comment by VKoskiv** [comment]
@mistydemeo Absolutely! I could open up the old G3 with SSH. Any place I could DM you the credentials + IP?

**Comment by VKoskiv** [comment]
@mistydemeo I emailed you the creds.

**Comment by mistydemeo** [comment]
Should be fixed now. I was able to confirm that `brew vendor-install ruby` now works, whereas it failed before, and downloads like `brew fetch -f wget` works as well.
