### ISSUE TITLE
404 error when trying to install Qt4

### ISSUE THREAD

**Issue by ironsniper1** [mistydemeo/tigerbrew#601]
i am trying to install qt4 and when i try to download and install with tigerbrew it gets a 404 error here is the download link for 4.8.6 instead of 4.8.7 can this updated so it will download and install?

**https://download.qt.io/archive/qt/4.8/4.8.6/qt-everywhere-opensource-src-4.8.6.tar.gz**

**Comment by mistydemeo** [comment]
Should be fixed now - thanks for the report!
