### ISSUE TITLE
minidlna: libid3tag missing mirror

### ISSUE THREAD

**Issue by saabi-hu** [mistydemeo/tigerbrew#612]
I tried to install minidlna but one of its dependency cannot be installed:
---
macmini:~ saabi$ brew install minidlna
==> Installing dependencies for minidlna: libid3tag, flac, libogg, libvorbis, make, texi2html, yasm, x264, lame, libvo-aacenc, xvid, ffmpeg
==> Installing minidlna dependency: libid3tag
==> Downloading https://downloads.sourceforge.net/project/mad/libid3tag/0.15.1b/libid3tag-0.15.1b.tar.gz
Already downloaded: /Users/saabi/Library/Caches/Homebrew/libid3tag-0.15.1b.tar.gz
==> Downloading http://mirror.ovh.net/gentoo-portage/media-libs/libid3tag/files/0.15.1b/libid3tag-0.15.1b-utf16.patchlibid3tag-0.15.1b-utf16.patch

curl: (6) Could not resolve host: mirror.ovh.net
Error: Failed to download resource "libid3tag--patch"
Download failed: http://mirror.ovh.net/gentoo-portage/media-libs/libid3tag/files/0.15.1b/libid3tag-0.15.1b-utf16.patchlibid3tag-0.15.1b-utf16.patch
---
The server mirror.ovh.net is not in the DNS.

**Comment by mistydemeo** [comment]
Should be fixed - can you `brew update` and try again?

**Comment by saabi-hu** [comment]
Yes, it is working now. Thank you!
