### ISSUE TITLE
fish 2.7.1 Symbol not found

### ISSUE THREAD

**Issue by VKoskiv** [mistydemeo/tigerbrew#616]
Running Mac OS X 10.4.11 on a TiBook (A1001, 667MHz)

Running the binary at `/usr/local/bin/fish` yields the following error:

```
dyld: Symbol not found: __ZNSt7__cxx1112basic_stringIwSt11char_traitsIwESaIwEED1Ev
    Referenced from: /usr/local/bin/fish
    Expected in: /usr/lib/libstdc++.6.dylib

Trace/BPT trap
```

No errors were shown during installation. Reinstallation + brew upgrade didn't resolve the symptom.

**Comment by christopher-caldwell** [comment]
@VKoskiv  Did you ever fix this? Currently having this issue

**Comment by VKoskiv** [comment]
@cristopher-caldwell I don’t think it was resolved. Just used bash instead.

**Comment by VKoskiv** [comment]
@christopher-caldwell I'm not sure why it didn't tag you in that previous response. I wrote it using the new GitHub mobile app.

**Comment by mistydemeo** [comment]
Let me pull the bottle. It looks like this ended up getting compiled against the Tigerbrew-installed GCC 7's libstdc++, so it breaks if that's not installed. I need to find a real fix for this later, but in the meantime I'll remove the binary packages so it can be built from source.
