### ISSUE TITLE
Installing Apache & PHP

### ISSUE THREAD

**Issue by Seshpenguin** [mistydemeo/tigerbrew#635]
Does tigerbrew has formulae for httpd and PHP? I can't seem to find it, if it does. (Using Leopard Server on a G5)

**Comment by tree-s** [comment]
For php you need to tap the [https://github.com/mistydemeo/homebrew-php](url).

**Comment by Seshpenguin** [comment]
Ah, ok. I tried and I still didn't seem to have any PHP packages. I ended up using MacPorts instead which worked. Thanks for the help though!
