### ISSUE TITLE
mariadb fails to build - source not found

### ISSUE THREAD

**Issue by typonaut** [mistydemeo/tigerbrew#644]
mariadb fails to build on 10.4.11 (intel) with tigerbrew 2.60 with the following error:

Download failed: http://ftp.osuosl.org/pub/mariadb/mariadb-10.0.21/source/mariadb-10.0.21.tar.gz

I have checked the ftp server in question and confirm there is no .../mariadb-10.0.21/... directory. However, the source does exist here:

archive.mariadb.org/mariadb-10.0.21/source/mariadb-10.0.21.tar.gz

This is a fairly old version, it would be nice to have a build that featured the Galera engine - ie at least 10.1.

Is there a way to fix this source problem myself?

**Comment by typonaut** [comment]
Sorry, tigerbrew 0.9.5.

**Comment by tree-s** [comment]
You can try to find a mirror and replace the link in the .rb file.

http://ftp.oregonstate.edu/.1/blfs/conglomeration/mariadb/mariadb-10.1.21.tar.gz

Just make sure that the checksums match.

**Comment by typonaut** [comment]
I found the .rb file here:

~/Downloads/tigerbrew-master/Library/Formula/mariadb.rb

I edited it to include a reliable known source (it turns out there are two different urls in the file, pointing to different versions of the source). However, when I run the install, it gives the same error with the old url.

Is it going to some online repository to get the mariadb.rb file, or is the file hidden somewhere else? Do I have to run my edited file directly somehow?

**Comment by typonaut** [comment]
I found a tip online for missing downloads - find the file elsewhere and copy it to the caches:

~/Library/Caches/Homebrew/

When running the install the brew process believes the file has already been downloaded, and continues as expected. In this case it successfully built mariadb 10.0.21.

I would like to know how to run a local .rb file, so I can attempt to build later versions of mariadb. So if anyone can tell me how I would appreciate it.

**Comment by mistydemeo** [comment]
Fixed by #645; sorry about the inconvenience!

> I would like to know how to run a local .rb file, so I can attempt to build later versions of mariadb.

You can pass the path to the file on disk to `brew install`; for example, `brew upgrade /Users/yourname/myrepo/mariadb.rb`. As long as the file is still named `mariadb.rb`, it should work.

**Comment by tree-s** [comment]
This sort of thing happens a lot with Tigerbrew and other legacy software when people stop hosting files.

**Comment by typonaut** [comment]
Well at least the URLs have been updated to archive.mariadb.org, so hopefully should be more persistant.
