### ISSUE TITLE
Searching brew results in many 'Failed to search tap' errors

### ISSUE THREAD

**Issue by stevenptimms** [mistydemeo/tigerbrew#659]
Hi there,

I have a clean install of Leopard 10.5.8 fully updated with a fresh install of brew. Computer is Powerbook 1.5ghz 1.25gb ram.

When using the search function I get this (brew search app):
Warning: Failed to search tap: Homebrew/binary. Please run `brew update`
Warning: Failed to search tap: Homebrew/games. Please run `brew update`
Warning: Failed to search tap: Homebrew/x11. Please run `brew update`
Warning: Failed to search tap: Homebrew/devel-only. Please run `brew update`
Warning: Failed to search tap: Homebrew/dupes. Please run `brew update`
Warning: Failed to search tap: Homebrew/completions. Please run `brew update`
Warning: Failed to search tap: Homebrew/tex. Please run `brew update`
Warning: Failed to search tap: Homebrew/head-only. Please run `brew update`
Warning: Failed to search tap: Homebrew/fuse. Please run `brew update`

Upon doing 'brew update' I get:
Already up-to-date.

Upon doing 'brew doctor' I get:
Warning: Your XQuartz (2.1.6) is outdated
Please install XQuartz 2.6.3:
  https://xquartz.macosforge.org

Warning: You have uncommitted modifications to Tigerbrew
If this a surprise to you, then you should stash these modifications.
Stashing returns Tigerbrew to a pristine state but can be undone
should you later need to do so for some reason.
    cd /usr/local/Library && git stash && git clean -d -f

NOTE: 1. I have updated to the latest XQuartz as advised, but this error does not go away. 2. I have run the git clean and stash command but this error does not go away. The stashed files always seem to be ruby and perl.

**Comment by tree-s** [comment]
I have the same issues I think the failed tap search is that because the Homebrew/* taps are archived or were moved? Not sure...

The xQuartz needs to be installed manually I think and you also need to have searchlight enabled because that's the way the script parses the version.

The uncommitted changes are fine I think that's just the portable versions of ruby/perl or something.

**Comment by mzryz** [comment]
Out of interest, mistydemeo does this effect functionality of tigerbrew and/or will you be fixing this? Thank you :)

**Comment by tree-s** [comment]
For the core Formulas everything works fine for my use case, but the most common problem is using taps that have outdated download or archive links. Usually you can find mirrors or links on the internetarchive.org.
