### ISSUE TITLE
openssl source url is dead

### ISSUE THREAD

**Issue by drhax9908** [mistydemeo/tigerbrew#670]
I attempted to install curl on my powermac g5, and it failed because the openssl source url was dead. It couldn't find it as it has been removed. Please update tigerbrew to have a working openssl source url

EDIT: This is sort of a catch-22, I tried brew update, and it tried to install git, and that needed openssl. So the only way to fix that is by finding a copy of git for my OS, lets hope this fixes that issue

**Comment by pk2061** [comment]
Hi,
I think I already created a pull request for that issue, because I ran into a similar problem recently. 
I will check and maybe recreate it later this evening. 
Best regards 
pk2061

**Comment by drhax9908** [comment]
Wish I'd known THAT sooner lol. I wound up attempting to MANUALLY compile git. Lets hope that works

**Comment by sevan** [comment]
New version of curl/openssl/git are available in Tigerbrew.
