### ISSUE TITLE
gegl fails to build under 10.5.8

### ISSUE THREAD

**Issue by onlytruethomas** [mistydemeo/tigerbrew#695]
I have a suspicion it's because the OpenGL framework set isn't referred to in the formula. Looking online it seems that's how OpenGL is accessed on Macs.

Unfortunately TenFourFox didn't seem to want to allow me to add more than one file to the same gist, so here it is in three parts:
`brew install gegl` output: https://gist.github.com/lecast0r/ef5b1ab45eaaa86f35f4cb7db6761736
`02.make`: https://gist.github.com/lecast0r/b9f129fb02516c815bfdb1a554d1a63e
`brew doctor` and `brew config` output: https://gist.github.com/lecast0r/0a88368cf0c49cdf5b3c65c1812a8ee2

Now let's just hope I didn't mess up somewhere

**Comment by kencu** [comment]
Try this patch <https://github.com/kencu/LeopardPorts/blob/master/graphics/gegl/files/patch-gegl-opencl-fix-Leopard-and-less-only.diff>
