### ISSUE TITLE
Submit bug code message

### ISSUE THREAD

**Issue by littlepasha** [mistydemeo/tigerbrew#698]
Please report this bug:
    https://github.com/mistydemeo/tigerbrew/wiki/troubleshooting
/usr/local/Library/Homebrew/formulary.rb:23:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:23:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:36:in `load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:86:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:77:in `klass'
/usr/local/Library/Homebrew/formulary.rb:73:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:208:in `factory'
/usr/local/Library/Homebrew/cmd/doctor.rb:1102:in `check_for_non_prefixed_coreutils'
/usr/local/Library/Homebrew/cmd/doctor.rb:1277:in `block in doctor'
/usr/local/Library/Homebrew/cmd/doctor.rb:1275:in `each'
/usr/local/Library/Homebrew/cmd/doctor.rb:1275:in `doctor'
/usr/local/Library/brew.rb:143:in `<main>'

**Comment by mistydemeo** [comment]
Hmmm. What does `brew tap` say?

**Comment by sevan** [comment]
Timeout?

**Comment by mistydemeo** [comment]
If you're still experiencing issues, please let me know! I'm closing for now.
