### ISSUE TITLE
Brew Update Errors and other package downloading errors

### ISSUE THREAD

**Issue by DolphinFlopFish** [mistydemeo/tigerbrew#705]
When I run 'brew update' I get a error message that says:
Initialized empty Git repository in /usr/local/.git/
fatal: unable to access 'https://github.com/mistydemeo/tigerbrew.git/': error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
Error: Failure while executing: git fetch origin

When I try to get the MAS package from GitHub I get this (Also I'm running OS X 10.8.5 on a MacBook7,1):
==> Searching formulae...
dnsmasq					masscan
gsettings-desktop-schemas		whatmask
l-smash
==> Searching taps...
Warning: Failed to search tap: Homebrew/binary. Please run `brew update`
Warning: Failed to search tap: Homebrew/versions. Please run `brew update`
Warning: Failed to search tap: Homebrew/fuse. Please run `brew update`
Warning: Failed to search tap: Homebrew/completions. Please run `brew update`
Warning: Failed to search tap: Homebrew/tex. Please run `brew update`
Warning: Failed to search tap: Homebrew/python. Please run `brew update`
Warning: Failed to search tap: Homebrew/devel-only. Please run `brew update`
Warning: Failed to search tap: Homebrew/games. Please run `brew update`
Warning: Failed to search tap: Homebrew/x11. Please run `brew update`
Warning: Failed to search tap: Homebrew/head-only. Please run `brew update`
Warning: Failed to search tap: Homebrew/dupes. Please run `brew update`
Warning: Failed to search tap: Homebrew/php. Please run `brew update`
Warning: Failed to search tap: Homebrew/x11. Please run `brew update`
Warning: Failed to search tap: Homebrew/science. Please run `brew update`
homebrew/emacs/mastodon-mode		Caskroom/cask/master-password
Caskroom/cask/gas-mask			Caskroom/cask/master-pdf-editor
Caskroom/cask/lyrics-master		Caskroom/cask/masterway-note
Caskroom/cask/mailmaster		Caskroom/cask/mindmaster
Caskroom/cask/masscode			Caskroom/cask/pdf-converter-master
Caskroom/cask/massreplaceit		Caskroom/cask/subtitle-master

When I try 'brew install git' it installs fine, when I run the 'git' command, everything works properly (with git)

**Comment by gsteemso** [comment]
If you're trying to run it on a version of OS X that's that much newer than 10.4 or 10.5, you can safely expect it not to work. This fork of the Homebrew package manager is a backport to the last PowerPC versions of the OS, and can’t work on an Intel-based machine like you’ve got.

**Comment by mistydemeo** [comment]
I do try to support newer Intel-based OSs, though I don't test on them so I can't guarantee success as well as on 10.4/10.5.

There isn't a `mas` formula in Tigerbrew right now. It looks like the builtin formula search is broken because some of the default taps it looks in are gone. I'll try to fix that error message.

**Comment by Carpintonto** [comment]
Hi misty - 

I'm helping a friend who's running Snow Leopard 10.6.8 on an iMac7,1 Intel Core 2 Duo which would put us right in between Homebrew and Tigerbrew target and support.  

I am seeing exactly the same error for 'brew update' and so much else works - I was able to install shell_cmds, I'm getting the sense that what's needed is to set up an ssh key on github.  Is that something you already have?

prompt$ ls -l `which git`
lrwxr-xr-x  1 user  staff  28 Jan 10 17:26 /usr/local/bin/git -> ../Cellar/git/2.10.2/bin/git

**Comment by pk2061** [comment]
In general I would try to run the iMac with something newer than Snow Leopard. And then you should be safe to use Homebrew for most of your needs.

**Comment by Carpintonto** [comment]
Thanks misty.  

So you know, 10.6.8 is the highest revision supported by iMac7,1, so in the instant case, back porting the OS just to support  tigerbrew is not an option.  Some of what I was able to get will be useful.

bash		curl		makedepend	pkg-config	shell_cmds	xz
bash-completion	git		openssl		readline	wget

Without a functional uninstall available, just creating a dummy ~/.git-completion.bash  suppresses the "not found" error preceding the terminal prompt.

You might think about saving yourself and everyone else some time by stating clearly in the README.md that tigerbrew will not work on 10.6.*

**Comment by mistydemeo** [comment]
> You might think about saving yourself and everyone else some time by stating clearly in the README.md that tigerbrew will not work on 10.6.*

I *intend* to support newer releases, but keep in mind I'm only one person with only so much hardware in my house, so issues will slip through the cracks.

It does look like using the system git on Intel Mac OS revisions that include it won't work anymore, so I may need to write some new code to blacklist that and insist on using Tigerbrew's install.

**Comment by mistydemeo** [comment]
Fixed the "failed to search tap" error!
