### ISSUE TITLE
Git not available

### ISSUE THREAD

**Issue by smnbldwn** [mistydemeo/tigerbrew#706]
I can't get Tigerbrew to update. I keep getting the message "git not available". There are a few messages when I run brew doctor but I don't understand if they are the problem. I have uninstalled then reinstalled Tigerbrew to try and fix this. I am running it on a Powerbook G4 with Mac OSX 10.5.8.

`brew update
==> Installing git
==> Installing dependencies for git: xz, pkg-config, makedepend, curl-ca-
==> Installing git dependency: xz
==> Downloading https://ia902307.us.archive.org/31/items/tigerbrew/xz-5.2.1.leop
######################################################################### 100.0%
==> Pouring xz-5.2.1.leopard_altivec.bottle.tar.gz
/usr/local/Cellar/xz/5.2.1: 59 files, 1.7M
==> Installing git dependency: pkg-config
==> Downloading https://pkgconfig.freedesktop.org/releases/pkg-config-0.29.1.tar
######################################################################### 100.0%
==> ./configure --prefix=/usr/local/Cellar/pkg-config/0.29.1_2 --disable-host-to
==> make
==> make check
==> make install
Error: Git is unavailable
`

Output from `brew doctor`
`Warning: The system curl on 10.6 and below is often incapable of supporting
modern secure connections & will fail on fetching formulae.
We recommend you:
  brew install curl

Warning: "config" scripts exist outside your system or Tigerbrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Tigerbrew if the config script overrides a system or Tigerbrew provided
script of the same name. We found the following "config" scripts:
    /Library/Frameworks/Python.framework/Versions/3.5/bin/python3-config
    /Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5-config
    /Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5m-config

Warning: Git could not be found in your PATH.
Tigerbrew uses Git for several internal functions, and some formulae use Git
checkouts instead of stable tarballs. You may want to install Git:
  brew install git

Warning: Python is installed at /Library/Frameworks/Python.framework

Tigerbrew only supports building against the System-provided Python or a
brewed Python. In particular, Pythons installed to /Library can interfere
with other software installs.

Warning: You have leftover files from an older version of Xcode.
You should delete them using:
  /Developer/Library/uninstall-developer-folder

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Tigerbrew formulae, and may need to be deleted.

Unexpected dylibs:
    /usr/local/lib/libfuse.0.dylib
    /usr/local/lib/libulockmgr.1.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Tigerbrew formulae, and may need to be deleted.

Unexpected header files:
    /usr/local/include/ulockmgr.h

Warning: Unbrewed .la files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Tigerbrew formulae, and may need to be deleted.

Unexpected .la files:
    /usr/local/lib/libulockmgr.la

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Tigerbrew formulae, and may need to be deleted.

Unexpected static libraries:
    /usr/local/lib/libfuse.a
    /usr/local/lib/libulockmgr.a
`

**Comment by smnbldwn** [comment]
I followed the advice to install Curl.

This is the output I got:

`brew install curl
==> Installing dependencies for curl: pkg-config, makedepend, curl-ca-bun
==> Installing curl dependency: pkg-config
==> Downloading https://pkgconfig.freedesktop.org/releases/pkg-config-0.29.1.tar
Already downloaded: /Users/xxxxxx/Library/Caches/Homebrew/pkg-config-0.29.1.tar.gz
==> ./configure --prefix=/usr/local/Cellar/pkg-config/0.29.1_2 --disable-host-to
==> make
==> make check
==> make install
Error: Permission denied - /usr/bin/xcrun`

**Comment by smnbldwn** [comment]
Then I tried to install git:
`brew install git
==> Installing dependencies for git: pkg-config, makedepend, curl-ca-bund
==> Installing git dependency: pkg-config
==> Downloading https://pkgconfig.freedesktop.org/releases/pkg-config-0.29.1.tar
Already downloaded: /Users/xxxxxxxxx/Library/Caches/Homebrew/pkg-config-0.29.1.tar.gz
==> ./configure --prefix=/usr/local/Cellar/pkg-config/0.29.1_2 --disable-host-to
==> make
==> make check
==> make install
Error: Permission denied - /usr/bin/xcrun
`

**Comment by smnbldwn** [comment]
Here is the output from `brew config`:

```
brew config
HOMEBREW_VERSION: 0.9.5
ORIGIN: (none)
HEAD: (none)
Last commit: never
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://ia902307.us.archive.org/31/items/tigerbrew
CPU: single-core 32-bit g4e
OS X: 10.5.8-Power Macintosh
Curl: /usr/local/Library/Homebrew/vendor/portable-curl/current/bin/curl
Xcode: dunno => /Developer
CLT: 1.0.0.9000000000.1.1192168948
GCC-4.0: build 5465
Clang: N/A
X11: 2.1.6 => /usr/X11
System Ruby: 2.3.3-222 => /usr/local/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Perl: /usr/bin/perl
Python: /usr/bin/python => /System/Library/Frameworks/Python.framework/Versions/2.5/Resources/Python.app/Contents/MacOS/Python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/bin/ruby
Java: 1.5.0_30-b03

```

**Comment by smnbldwn** [comment]
I installed Python 3.5 so that I can run pip and the python utility catt to cast things to a Chromecast.
Could this be what is interfering with Tigerbrew?

**Comment by Ricotan-naboon** [comment]
If the answer is Incorrect, Please ignore.
So I think Doing that command that will resolve. ```sudo chmod 777 /usr/bin/xcrun && brew install git```

**Comment by Ricotan-naboon** [comment]
Warning: chmod is too dangerous. 
Please be careful and I not responsible for this commmand.

**Comment by smnbldwn** [comment]
Thank you for your reply. Logically, this should work, alas it didn't and I got the same error.

`Error: Permission denied - /usr/bin/xcrun`

No harm done though. Thank you again...

**Comment by RandomInsano** [comment]
Silly question, do you have the command line tools installed? You can grab them by *running* `xcrun` then installing the command line tools with `xcode-select --install`.

Apple ships its own build of Git with xcode and the command line tools so that should at least get you a little further.

**Comment by smnbldwn** [comment]
Thank you, I found that my version of Xcode was too old. I installed the newest on and that fixed it.
