### ISSUE TITLE
Unable to install - MacOSX 10.5.8

### ISSUE THREAD

**Issue by Minutemanqvs** [mistydemeo/tigerbrew#728]
Hello,

I don't know if this recently broke due to SSL/TLS certificate changes and libs on the 10.5.8 OS, but it looks like it's not possible to install tigerbrew following the documentation:

Power-Mac-G5:~ steven$ ruby -e "$(curl -fsSkL raw.github.com/mistydemeo/tigerbrew/go/install)"
curl: (28) SSL connection timeout

If I open https://raw.github.com/mistydemeo/tigerbrew/go/install with TenFourFox it works, but opening the same URL with Safari 5.0.6 fails, which leads me to this conclusion.

**Comment by mistydemeo** [comment]
Hm, that's annoying. Looks like I'll need to change the install instructions!

**Comment by jspringe-stu** [comment]
@Minutemanqvs https://github.com/mistydemeo/tigerbrew/issues/726#issuecomment-789992137

**Comment by ltpitt** [comment]
I confirm same behaviour for Mac OS 10.4.11

**Comment by ltpitt** [comment]
I opened the script at https://raw.githubusercontent.com/mistydemeo/tigerbrew/go/install with TenFourFox (I already suffer thinking to the day when this will not be possible given the fact that its development stopped), saved it locally, made sure that my Xcode was installed and PATH updated as suggested in the README.md and installed it using ruby -e "$(cat saved_file_name.ruby)"

Thanks for the workaround and for this great software :)

**Comment by Minutemanqvs** [comment]
I confirm that it works perfectly this way :)

**Comment by alollini** [comment]
Caution : when trying to download https://raw.githubusercontent.com/mistydemeo/tigerbrew/go/install with Tenfourfox I ended up with a strange corrupt file, I still can not pinpoint exactly what is wrong with the file.
Same issue when viewing the text in Tenfourfox then copy/pasting in an new bbedit file (probably same corruption)

Only the file made with new Safari  + new bbedit on Mojave mac enabled me to execute.
