### ISSUE TITLE
Bintray shutting down May 1st

### ISSUE THREAD

**Issue by vkoskiv** [mistydemeo/tigerbrew#729]
Discussion on upstream:
https://github.com/Homebrew/discussions/discussions/691

Will this affect tigerbrew bottles?

**Comment by mistydemeo** [comment]
Nope! Tigerbrew bottles are hosted at archive.org.

**Comment by vkoskiv** [comment]
Great to hear! I got really worried for all my vintage machines here.
Thanks for answering so quick!
