### ISSUE TITLE
SHA256 mismatch on Cairo patch

### ISSUE THREAD

**Issue by evanmiller** [mistydemeo/tigerbrew#736]
Following up on #452, I am seeing SHA256 mismatch errors when attempting to install Cairo:

```
==> Downloading https://cgit.freedesktop.org/~ranma42/cairo/patch/?id=5a8a9c97ed268004cbac510d39739
Already downloaded: /Users/XXX/Library/Caches/Homebrew/cairo--patch-8d119eca6c35ac8645d13d656b5a721cfeeec1ebcf5793f9d5182c604782de15
Error: SHA256 mismatch
Expected: 8d119eca6c35ac8645d13d656b5a721cfeeec1ebcf5793f9d5182c604782de15
Actual: e4d5cea0f00108bab020e669659e8c20dfcbf29f43b15aeeebd2936e45ededd0
```

The patch applies just fine if I change the SHA256 value in the cairo.rb formula.

**Comment by ticky** [comment]
Can confirm the sha sum is currently `e4d5cea0f00108bab020e669659e8c20dfcbf29f43b15aeeebd2936e45ededd0` - it looks like changing `cgit` versions will change the content of patch files generated by it 🙃

**Comment by mistydemeo** [comment]
Yep, you're right. That's annoying!
