### ISSUE TITLE
brew install libpng fails

### ISSUE THREAD

**Issue by Berrybarb** [mistydemeo/tigerbrew#750]
brew install libpng
==> Downloading ftp://ftp.simplesystems.org/pub/libpng/png/src/libpng16/libpng-1
-=O=-          #    #    #     #                                               
curl: (78) RETR response: 550
Trying a mirror...
==> Downloading https://dl.bintray.com/homebrew/mirror/libpng-1.6.24.tar.xz
#=#=-#  #                                                                      
curl: (22) The requested URL returned error: 403 Forbidden
Error: Failed to download resource "libpng"
Download failed: https://dl.bintray.com/homebrew/mirror/libpng-1.6.24.tar.xz
administrators-Mac-mini-2:Cellar admin$ brew install libpng
==> Downloading ftp://ftp.simplesystems.org/pub/libpng/png/src/libpng16/libpng-1
-=O=-          #    #    #     #                                               
curl: (78) RETR response: 550
Trying a mirror...
==> Downloading https://dl.bintray.com/homebrew/mirror/libpng-1.6.24.tar.xz
#=#=-#  #                                                                      
curl: (22) The requested URL returned error: 403 Forbidden
Error: Failed to download resource "libpng"
Download failed: https://dl.bintray.com/homebrew/mirror/libpng-1.6.24.tar.xz

**Comment by mistydemeo** [comment]
Should be fixed now. Can you `brew update` and retry?

**Comment by Berrybarb** [comment]
Thank you, that worked.

It did take this which was found in some other post here:

brew reinstall curl
brew link --force curl
brew reinstall --build-from-source git
brew update

**Comment by Berrybarb** [comment]
Libpng although included with 10.6.8 was a requirement for Imagemagick, so that is good. Is it possible to install imagemagick 7 via tigerbrew on 10.6.8 x86_64? I'll generally have to dig up a backup disk but I think when homebrew still worked on 10.6.8 I installed stuff I now can't.
