### ISSUE TITLE
ExifTool 10.01 – download fails

### ISSUE THREAD

**Issue by wotantitan** [mistydemeo/tigerbrew#751]
`brew install exiftool` fails on Mac OS X 10.4.11 PPC because *Image-ExifTool-10.01.tar.gz* is not available under the given url anymore. The archive [can be obtained through archive.org](https://web.archive.org/web/20151024082135/http://www.sno.phy.queensu.ca/~phil/exiftool/Image-ExifTool-10.01.tar.gz) still.

Tigerbrew is amazing. Keep up the good work.

**Comment by mistydemeo** [comment]
Thank you! I've switched to the archive. Sometime in the future I might look at upgrading to a newer version.
