### ISSUE TITLE
SHA1 error for glib

### ISSUE THREAD

**Issue by mijk84** [mistydemeo/tigerbrew#752]
Seems to be for the patch mentioned in the glib.rb formula (the file was reuploaded maybe?):

https://bug728123.bugzilla-attachments.gnome.org/attachment.cgi?id=275596

Error: SHA1 mismatch
Expected: 5637d98e1c7bbfa8824e60612976a8c13d0c0fb6
Actual: a8a6eadbbb967e07cbe2f54031410c85c2f41ce4

**Comment by mistydemeo** [comment]
Looks like the attachment is being compressed now. I'll rehost it.
