### ISSUE TITLE
Vendored cURL's bundled cacert.pem is outdated and results in certificate validation failures with some SSL certificates (notably Let's Encrypt) used on some URLs

### ISSUE THREAD

**Issue by akemin-dayo** [mistydemeo/tigerbrew#757]
The current `cacert.pem` is roughly **3 years out of date** at this point, with the result being that many SSL certificates (notably Let's Encrypt) now fail to validate using it.

Here is an example of such a case — I'm using `makedepend` as an example here as I ran into SSL connection issues installing it as a dependency of `curl` and `git`, much like what happened in issue #756:
```console
karen002ppc-osx105:~ karen$ brew reinstall makedepend
==> Reinstalling makedepend
==> Downloading http://xorg.freedesktop.org/releases/individual/util/makedepend-1.0.5.tar.bz2
Already downloaded: /Users/karen/Library/Caches/Homebrew/makedepend-1.0.5.tar.bz2
==> Downloading http://xorg.freedesktop.org/releases/individual/proto/xproto-7.0.25.tar.bz2
==> Downloading from https://www.x.org/releases/individual/proto/xproto-7.0.25.tar.bz2
#=O#-   #      #                                                                                                                                                                                         
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
Error: Failed to download resource "makedepend--xproto"
Download failed: https://www.x.org/releases/individual/proto/xproto-7.0.25.tar.bz2
```

**To fix this issue, we can update the `cacert.pem` file to the latest one:**
```shell
cp -pv /usr/local/Library/Homebrew/vendor/portable-curl/current/share/cacert.pem /usr/local/Library/Homebrew/vendor/portable-curl/current/share/cacert.pem.old
/usr/local/Library/Homebrew/vendor/portable-curl/current/bin/curl --insecure https://curl.se/ca/cacert.pem -o /usr/local/Library/Homebrew/vendor/portable-curl/current/share/cacert.pem
```
**※ Note:** As an alternative to using `curl --insecure` (which is, as the flag suggests, insecure), you can download `cacert.pem` on a trusted modern machine and `scp` (or otherwise somehow transfer) the file to your legacy machine instead.

After updating the `cacert.pem` file, SSL connections that were previously failing now work correctly!
```console
karen002ppc-osx105:~ karen$ brew reinstall makedepend
==> Reinstalling makedepend
==> Downloading http://xorg.freedesktop.org/releases/individual/util/makedepend-1.0.5.tar.bz2
Already downloaded: /Users/karen/Library/Caches/Homebrew/makedepend-1.0.5.tar.bz2
==> Downloading http://xorg.freedesktop.org/releases/individual/proto/xproto-7.0.25.tar.bz2
==> Downloading from https://www.x.org/releases/individual/proto/xproto-7.0.25.tar.bz2
################################################################################################################################################################################################### 100.0%
==> ./configure --disable-silent-rules --prefix=/private/tmp/makedepend20211011-15121-l3bpyq/makedepend-1.0.5/xproto
^C
```

This issue occurs for me me on PowerPC versions of OS X 10.5.8 and 10.4.11, but should also apply to any other platform that uses the vendored cURL binary.

In the interest of full disclosure, the hardware that this is running on is actually QEMU-screamer (with bridged TAP networking) on an x86_64 host, using [my own guide that I wrote/actively maintain on how to do so](https://gist.github.com/akemin-dayo/0e9bdcd74b2ad7f0bcf56e0680256103). This emulates a single-CPU PowerPC G4 7400 on a PowerMac3,1 ("AGP Graphics").

I do not actually own any PowerPC hardware to reproduce this issue on, but as far as I'm aware, this being on QEMU _should not_ have any impact on this issue.

**Comment by mistydemeo** [comment]
This should be working now! On my 10.4 Mac, I'm able to fetch from the previously-broken domains. If you still have problems, please let me know.
