### ISSUE TITLE
should git be installing with NO_OPENSSL=1 ?

### ISSUE THREAD

**Issue by dillera** [mistydemeo/tigerbrew#760]
installing git on 10.6.8:

```
whiteball:~ dillera$ brew install git
==> Downloading https://www.kernel.org/pub/software/scm/git/git-2.10.2.tar.xz
######## 
100.0%
### 100.0%
==> make install prefix=/usr/local/Cellar/git/2.10.2 sysconfdir=/usr/local/etc CC=llvm-gcc CFLAGS= LDFLAGS= NO_OPENSSL=1 APPLE_COMMO
```

should git be installed with no ssl support?

After installing I can't update TB!

```
whiteball:~ dillera$ which git
/usr/local/bin/git
whiteball:~ dillera$ git --version
git version 2.10.2
whiteball:~ dillera$ brew update
Initialized empty Git repository in /usr/local/.git/
fatal: unable to access 'https://github.com/mistydemeo/tigerbrew.git/': error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
Error: Failure while executing: git fetch origin

```

how best to change the formula for git to use open-ssl?

**Comment by mistydemeo** [comment]
Can you tell me what version of Mac OS you're using? It's currently set to use OpenSSL on the oldest supported OSs, but maybe I need to make it use it on newer OSs too.

**Comment by dillera** [comment]
Sure, with the recent changes I'm thinking of removing all brew and just re-doing from scratch. Thanks for the updates.

**Comment by mistydemeo** [comment]
You're welcome! I'm so sorry for the inconvenience.
