### ISSUE TITLE
socat failed to download

### ISSUE THREAD

**Issue by 996refuse** [mistydemeo/tigerbrew#779]
it looks this link won't work anymore.
http://www.dest-unreach.org/socat/download/socat-1.7.3.0.tar.gz

**Comment by Ricotan-naboon** [comment]
Did you did edit socat.rb?
I think fix URL it will work.

http://www.dest-unreach.org/socat/download/Archive/socat-1.7.3.0.tar.gz

**Comment by sevan** [comment]
Updated url was committed to Tigerbrew.
