### ISSUE TITLE
Error running neofetch

### ISSUE THREAD

**Issue by pk2061** [mistydemeo/tigerbrew#792]
Hi,

I wanted to try neofetch. 
I installed with "brew install neofetch"

After that i tried to run it, but I got an error message:
iMac-G3:~ jan$ neofetch
/usr/local/bin/neofetch: line 42: shopt: nocasematch: invalid shell option name
/usr/local/bin/neofetch: line 1233: conditional binary operator expected
/usr/local/bin/neofetch: line 1233: syntax error near `=~'
/usr/local/bin/neofetch: line 1233: `		if [[ $osx_version =~ "10.4" || $osx_version =~ "10.5" ]]; then'
iMac-G3:~ jan$ 

I am using an iMac G3 running 10.4.11.

Do you have any suggestion what to do?

Thanks for the help!
Best regard.

**Comment by RealPortalPlayer** [comment]
The version of bash that comes with Mac OS X Tiger is too old. Run "brew install bash", and use that instead for neofetch to work.

**Comment by pk2061** [comment]
Thanks alot! That was the solution! :) 

Thanks for your help!
