### ISSUE TITLE
Apple appears to have removed the "tarballs/" directory from their open source page

### ISSUE THREAD

**Issue by nhubbard** [mistydemeo/tigerbrew#795]
Hello, I'm trying to use Tigerbrew on my Power Mac G3, but I keep running into a missing file error. Sure enough, I go to investigate, and it looks like Apple has eliminated the tarballs directory from their open source site.

I can't download the https://opensource.apple.com/tarballs/cctools/cctools-855.tar.gz archive for cctools-headers, nor can I download the https://opensource.apple.com/tarballs/xnu/xnu-2422.90.20.tar.gz archive required by cctools-headers. I found refuge for the cctools in the form of making my own archive from the GitHub mirror that Apple has provided, but they didn't provide a commit for the XNU 2422.90.20 release; only for XNU 2422.1.72. I had to manually edit the formula files and remove the hash checks to get past the cctools warning, but I'm not sure what to do since we have a missing version of XNU on Apple's GitHub with no patchfiles showing the difference between 2422.1.72 and 2422.90.20.

**Comment by mistydemeo** [comment]
Ugh, darn. Okay, I'll try to dig up proper URLs.

**Comment by EricFromCanada** [comment]
They've [moved to GitHub](https://github.com/Homebrew/homebrew-core/pull/115084), it seems.

**Comment by nhubbard** [comment]
I'm working on making a patch to fix all of the missing tarballs, since that patch doesn't cover all of the changes we made to our formulas.
