### ISSUE TITLE
brew linkapps not working

### ISSUE THREAD

**Issue by breakeven** [mistydemeo/tigerbrew#80]
brew linkapps                                                                                    1 ↵
Error: undefined method `max_by' for [#<Keg:/usr/local/Cellar/autoconf/2.69>]:Array
Please report this bug:
    https://github.com/mistydemeo/tigerbrew/wiki/troubleshooting
/usr/local/Library/Contributions/cmd/brew-linkapps.rb:16
/usr/local/Library/Contributions/cmd/brew-linkapps.rb:12:in `each'
/usr/local/Library/Contributions/cmd/brew-linkapps.rb:12
/usr/local/Library/brew.rb:45:in `require'
/usr/local/Library/brew.rb:45:in `require?'
/usr/local/Library/brew.rb:87

**Comment by antelopeb** [comment]
This issue is still present. I'm using v0.9.5 and getting this error when I run brew linkapps: "wrong number of arguments (3 for 1)"

**Comment by mistydemeo** [comment]
Can you run `brew linkapps --debug`, and provide the output? Thanks!

**Comment by mistydemeo** [comment]
And just to make sure, have you run `brew update` recently?

**Comment by antelopeb** [comment]
Okay, ran brew update, still erroring out. Here's the debug output:

Error: wrong number of arguments (3 for 1)
Please report this bug:
    https://github.com/mistydemeo/tigerbrew/wiki/troubleshooting
/usr/local/Library/Homebrew/cmd/linkapps.rb:27:in `[]'
/usr/local/Library/Homebrew/cmd/linkapps.rb:27:in `linkapps'
/usr/local/Library/Homebrew/cmd/linkapps.rb:25:in `each'
/usr/local/Library/Homebrew/cmd/linkapps.rb:25:in `linkapps'
/usr/local/Library/brew.rb:135:in `send'
/usr/local/Library/brew.rb:135

**Comment by mistydemeo** [comment]
Fixed, thanks for the report!

**Comment by antelopeb** [comment]
Thanks @mistydemeo!!
