### ISSUE TITLE
Cannot install Perl

### ISSUE THREAD

**Issue by Amatarou-SUN** [mistydemeo/tigerbrew#927]
I am getting an error when trying to install perl.
How do I install it?
![Picture 1](https://github.com/mistydemeo/tigerbrew/assets/85050558/1943a0a7-a017-4a87-bcd3-a87fd32657a6)

**Comment by mistydemeo** [comment]
Can you please post the output of running `brew --config`?

**Comment by Amatarou-SUN** [comment]
Sure!
![Picture 2](https://github.com/mistydemeo/tigerbrew/assets/85050558/09f78c48-5218-4b86-9bec-5c5bf2cc14e7)

**Comment by mistydemeo** [comment]
Thank you! Can you also provide me the logs located in `~/Library/Logs/Homebrew/perl`? You can upload them to gist.github.org

**Comment by Amatarou-SUN** [comment]
https://gist.github.com/Amatarou-SUN/542f785ed617db6e1369d9df6b21c9a2

**Comment by mistydemeo** [comment]
I'm surprised it's setting `MACOSX_DEPLOYMENT_TARGET`. Do you have that set in your environment?

**Comment by Amatarou-SUN** [comment]
How to check it?

**Comment by Amatarou-SUN** [comment]
how do i check? I've googled but can't find a way

**Comment by Amatarou-SUN** [comment]
I found how, but MACOSX_DEPLOYMENT_TARGET is empty.
