### ISSUE TITLE
rhash and utf8proc failed to build because of missing libcrypto.1.0.0.dylib

### ISSUE THREAD

**Issue by pk2061** [mistydemeo/tigerbrew#943]
Hi!

first of all: Thanks for the great work and the many updates you did over the last few weeks! :-)

Unfortunately I ran into a problem while upgrading my installed stuff:

When I tried to upgrade **cmake** it needs to install **rash** as a dependency.
This fails because of the following eror:

Library not loaded: /usr/local/lib/libcrypto.1.0.0.dylib
  Referenced from: /usr/local/opt/ld64/bin/ld
  Reason: image not found  

It is the same with **utf8proc** which is a dependency to **tmux**

I am running a iMac G3 with 10.4.11 Tiger.

Do you have an Idea what my be the problem here?
Below I postet the terminal outputs of both builds.

 Thanks for your help!

**Trying to build rhash:** 

imac-g3:~ jan$ brew install rhash
==> Downloading https://downloads.sourceforge.net/project/rhash/rhash/1.3.3/rhash-1.3.3-src.tar.gz
Already downloaded: /Users/jan/Library/Caches/Homebrew/rhash-1.3.3.tar.gz
==> Patching
patching file librhash/Makefile
Hunk #1 succeeded at 28 (offset 2 lines).
Hunk #2 succeeded at 182 (offset 6 lines).
==> make lib-static lib-shared all CC=/usr/local/bin/gcc-4.2
Last 15 lines from /Users/jan/Library/Logs/Homebrew/rhash/01.make:
/usr/local/bin/gcc-4.2 -c  -pipe -DIN_RHASH  -O2 -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections -Wall -W -Wstrict-prototypes -Wnested-externs -Winline -Wpointer-arith -Wbad-function-cast -Wmissing-prototypes -Wmissing-declarations tth.c -o tth.o
/usr/local/bin/gcc-4.2 -c  -pipe -DIN_RHASH  -O2 -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections -Wall -W -Wstrict-prototypes -Wnested-externs -Winline -Wpointer-arith -Wbad-function-cast -Wmissing-prototypes -Wmissing-declarations torrent.c -o torrent.o
/usr/local/bin/gcc-4.2 -c  -pipe -DIN_RHASH  -O2 -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections -Wall -W -Wstrict-prototypes -Wnested-externs -Winline -Wpointer-arith -Wbad-function-cast -Wmissing-prototypes -Wmissing-declarations whirlpool.c -o whirlpool.o
/usr/local/bin/gcc-4.2 -c  -pipe -DIN_RHASH  -O2 -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections -Wall -W -Wstrict-prototypes -Wnested-externs -Winline -Wpointer-arith -Wbad-function-cast -Wmissing-prototypes -Wmissing-declarations whirlpool_sbox.c -o whirlpool_sbox.o
ar cqs librhash.a algorithms.o byte_order.o plug_openssl.o rhash.o rhash_timing.o rhash_torrent.o util.o aich.o crc32.o ed2k.o edonr.o hex.o md4.o md5.o sha1.o sha256.o sha512.o sha3.o ripemd-160.o gost.o has160.o snefru.o tiger.o tiger_sbox.o tth.o torrent.o whirlpool.o whirlpool_sbox.o
ranlib: file: librhash.a(plug_openssl.o) has no symbols
ranlib: file: librhash.a(util.o) has no symbols
make -C librhash lib-shared
/usr/local/bin/gcc-4.2 -fpic  -pipe -DIN_RHASH  -O2 -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections -Wall -W -Wstrict-prototypes -Wnested-externs -Winline -Wpointer-arith -Wbad-function-cast -Wmissing-prototypes -Wmissing-declarations -dynamiclib algorithms.c byte_order.c plug_openssl.c rhash.c rhash_timing.c rhash_torrent.c util.c aich.c crc32.c ed2k.c edonr.c hex.c md4.c md5.c sha1.c sha256.c sha512.c sha3.c ripemd-160.c gost.c has160.c snefru.c tiger.c tiger_sbox.c tth.c torrent.c whirlpool.c whirlpool_sbox.c   -Wl,-install_name,/usr/local/lib/librhash.0.dylib -o librhash.0.dylib
collect2: ld terminated with signal 5 [Trace/BPT trap]
**dyld: Library not loaded: /usr/local/lib/libcrypto.1.0.0.dylib
  Referenced from: /usr/local/opt/ld64/bin/ld
  Reason: image not found**
make[1]: *** [librhash.0.dylib] Error 1
make: *** [librhash/librhash.so.0] Error 2

READ THIS: https://github.com/mistydemeo/tigerbrew/wiki/troubleshooting

---------------------------------------------------------------------------------------------------------------------------------

**Trying to build utf8proc:**

imac-g3:~ jan$ brew install utf8proc
==> Downloading https://github.com/JuliaStrings/utf8proc/archive/v2.8.0.tar.gz
Already downloaded: /Users/jan/Library/Caches/Homebrew/utf8proc-2.8.0.tar.gz
==> Patching
patching file Makefile
==> make install prefix=/usr/local/Cellar/utf8proc/2.8.0
Last 15 lines from /Users/jan/Library/Logs/Homebrew/utf8proc/01.make:
2023-08-24 07:45:43 +0200

make
install
prefix=/usr/local/Cellar/utf8proc/2.8.0

/usr/local/bin/gcc-4.2 -I/usr/local/opt/ld64/include -F/usr/local/Frameworks -Os -w -pipe -mcpu=750 -faltivec -mmacosx-version-min=10.4 -fPIC -std=c99 -Wall -Wextra -pedantic -DUTF8PROC_EXPORTS  -c -o utf8proc.o utf8proc.c
rm -f libutf8proc.a
ar crs libutf8proc.a utf8proc.o
/usr/local/bin/gcc-4.2 -L/usr/local/opt/ld64/lib -L/usr/local/lib -F/usr/local/Frameworks -Wl,-headerpad_max_install_names -B/usr/local/Cellar/ld64/97.17/bin/ -dynamiclib -o libutf8proc.2.dylib utf8proc.o -install_name /usr/local/Cellar/utf8proc/2.8.0/lib/libutf8proc.2.dylib -Wl,-compatibility_version -Wl,2 -Wl,-current_version -Wl,2.6.0
collect2: ld terminated with signal 5 [Trace/BPT trap]
**dyld: Library not loaded: /usr/local/lib/libcrypto.1.0.0.dylib
  Referenced from: /usr/local/Cellar/ld64/97.17/bin/ld
  Reason: image not found**
make: *** [libutf8proc.2.dylib] Error 1

READ THIS: https://github.com/mistydemeo/tigerbrew/wiki/troubleshooting

imac-g3:~ jan$

**Comment by sevan** [comment]
> Library not loaded: /usr/local/lib/libcrypto.1.0.0.dylib
> Referenced from: /usr/local/opt/ld64/bin/ld
> Reason: image not found

hmm, ld64 package is linked against the old OpenSSL package which has now been upgraded to v1.1.1?
What does the output of `otool -L /usr/local/opt/ld64/bin/ld` say?

**Comment by pk2061** [comment]
This is the requested output:
`imac-g3:~ jan$ otool -L /usr/local/opt/ld64/bin/ld
/usr/local/opt/ld64/bin/ld:
	/usr/local/lib/libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 7.4.0)
	/usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 88.1.12)
imac-g3:~ jan$ 
`

**Comment by pk2061** [comment]
Also I have updated OpenSSL to v. 1.1.1.
Here ist the output of brew info:

```
imac-g3:~ jan$ brew info openssl
openssl: stable 1.1.1v
SSL/TLS cryptography library
https://openssl.org/

This formula is keg-only.
OS X already provides this software and installing another version in
parallel can cause all kinds of trouble.

/usr/local/Cellar/openssl/1.0.2j (469 files, 18M)
  Built from source
/usr/local/Cellar/openssl/1.1.1v (1195 files, 46M)
  Built from source
From: /usr/local/Library/Formula/openssl.rb
==> Dependencies
Build: perl ✔, makedepend ✔
Required: curl-ca-bundle ✔
==> Options
--universal
	Build a universal binary
--without-test
	Skip build-time tests (not recommended)
==> Caveats
A CA file has been bootstrapped using certificates from the SystemRoots
keychain. To add additional certificates (e.g. the certificates added in
the System keychain), place .pem files in
  /usr/local/etc/openssl/certs

and run
  /usr/local/opt/openssl/bin/c_rehash

This formula is keg-only, which means it was not symlinked into /usr/local.

OS X already provides this software and installing another version in
parallel can cause all kinds of trouble.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/openssl/lib
    CPPFLAGS: -I/usr/local/opt/openssl/include

```

**Comment by sevan** [comment]
There is indeed an [openssl dependency](https://github.com/mistydemeo/tigerbrew/blob/master/Library/Formula/ld64.rb#L79)
I guess with the openssl upgrade, `/usr/local/lib/libcrypto.1.0.0.dylib` no longer exists?

**Comment by pk2061** [comment]
I took a look:
libcrypto.1.0.0.dylib does not exist under /usr/local/lib/ anymore

but I was able to find it under: ` /usr/local/Cellar/openssl/1.0.2j/lib/libcrypto.1.0.0.dylib`

On the same note - and maybe related to that issue:

When I tried to start mc (Midnight Commander) I received a similar error message:
```
imac-g3:~ jan$ mc
dyld: Library not loaded: /usr/local/lib/libssl.1.0.0.dylib
  Referenced from: /usr/local/lib/libssh2.1.dylib
  Reason: image not found
```

I was able to locate the libssl.1.0.0.dylib also under `usr/local/Cellar/openssl/1.0.2j/lib/libssl.1.0.0.dylib`

Is it possible that my symlinks under /usr/local/lib/ are gone for the OpenSSL library files?

**Comment by sevan** [comment]
OpenSSL became keg only for the v1.1.1 upgrade so aside from the filename change (1.0.0 suffix instead of 1.1.1), there are no symlinks made into lib directory. That shouldn't be a user's concern though since dependencies if not upgraded should be revision bumped so a rebuild will take the change into account.

Regarding midnight commander, [there's a formula update which brings in the very latest version to tigerbrew](https://github.com/mistydemeo/tigerbrew/pull/851), but hasn't been merged yet. You can make the changes locally in the meantime (note the Requires line on that PR which links to slang & libssh2 upgrades which are also pending).

**Comment by pk2061** [comment]
Okay, sorry for the question. 
I was just wondering, because I saw that in `/usr/local/lib/ ` there where quite a few files that where symlinked from / to files in  `usr/local/Cellar/...`.
(e.g. "lrwxr-xr-x    1 jan  admin    38 Aug 24 04:09 libpcreposix.a -> ../Cellar/pcre/8.45/lib/libpcreposix.a")
So I just assumed, that it would be the same with the libs from openssl.

But in the meantime I wait for your commit and then reinstall ld64 for your change to take affect, right?

Thanks for the help!

**Comment by sevan** [comment]
Yes, when the commit lands, the issue with `ld` will be resolved.

**Comment by pk2061** [comment]
Okay, thanks a lot for your help!
I will wait for that and report back, how it worked out for me! :-)

**Comment by mistydemeo** [comment]
I think what might have happened here is that you had to build ld64 from source, so it didn't use the binary package. Your from-source build must have noticed your local copy of openssl and used it, even though it wasn't marked as a dependency. The binary package is built against the system's version, so it didn't run into this problem the way you did.

That said, I think sevan's patch will help make the build more reliable going forward, so I'm still planning to use it.
