### ISSUE TITLE
Package “glib” has dependencies that it doesn’t tell you about before just blindly installing them 

### ISSUE THREAD

**Issue by gsteemso** [mistydemeo/tigerbrew#949]
I just now did `install glib`, after manually installing each of its declared prerequisites (I'm a bit picky about making sure I don't miss any install options that I might want — it's not like the brew command can read my mind when it installs stuff automatically to satisfy a dependency).  Imagine my surprise when it then up and installed `sqlite`, `gdbm`, and version-2 `python` as dependencies!  That's the kind of thing you'd expect it to have mentioned ahead of time.

**Comment by sevan** [comment]
If you run `brew install -v glib` does it tell you then?

**Comment by gsteemso** [comment]
no, it just says it's installing them as it does so, same as `install` without the `-v`.  What good is `brew info` if it only tells you about SOME of the prerequisites it will forcibly install?

**Comment by mistydemeo** [comment]
`brew info` only shows direct dependencies; what you're seeing are recursive dependencies, that is something else deeper in the tree. You can visualize the full tree if you want by running `brew deps --tree`.

**Comment by gsteemso** [comment]
That's the thing, though – I had gone through each of the immediately-reported dependencies's dependencies, and so on, essentially following the tree “by hand” in order to set the various dependencies’ compile options as I preferred.  (It wasn’t very complicated, as few packages expose very many of their subjects’ actual options and most of them had nothing I wanted to change... not all, though, which was why I bother.)  Nowhere in the entire tree of dependencies did these packages appear.  I’m currently AFK and can’t check it personally, but if the `--tree` option reveals something you can't find manually, I’d be fascinated to work out _why_.  :¬)On Sep 2, 2023, at 6:03 PM, Misty De Méo ***@***.***> wrote:﻿
brew info only shows direct dependencies; what you're seeing are recursive dependencies, that is something else deeper in the tree. You can visualize the full tree if you want by running brew deps --tree.

**Comment by gsteemso** [comment]
Put simply, at the time I instructed it to `install glib`, all of the declared dependencies were already installed.  As I understand it, other packages suddenly being installed should not have been possible.On Sep 2, 2023, at 6:03 PM, Misty De Méo ***@***.***> wrote:﻿
brew info only shows direct dependencies; what you're seeing are recursive dependencies, that is something else deeper in the tree. You can visualize the full tree if you want by running brew deps --tree.

**Comment by mistydemeo** [comment]
If I check `brew deps --tree glib`, here's what I get:

```
glib (required dependencies)
└── :python
├── xz
├── pkg-config
├── gettext
|   └── xz
├── libffi
├── pcre
└── zlib
```

Python is a "special" dependency for technical reasons, which is why it's got a colon on the front. That's a concept that upstream Homebrew has gotten rid of, but it still exists in Tigerbrew. Unfortunately, that's why `brew info` didn't show it, and `brew deps` stops at Python without showing its own dependencies.

I recognize this isn't the ideal user experience right now! Sorry about that. Right now my focus is on integrating Sevan's work to update more packages and get more things building, rather than making too many more changes to Tigerbrew's own code.

**Comment by gsteemso** [comment]
Fascinating!  Hopefully, when you do have a chance to get to it -- and I agree, the other stuff sounds more urgent -- the work done on the upstream project can be adapted, rather than you having to start over by hand.  Thanks for working that out; it had been nagging at me.On Sep 3, 2023, at 3:51 PM, Misty De Méo ***@***.***> wrote:﻿
If I check brew deps --tree glib, here's what I get:
glib (required dependencies)
└── :python
├── xz
├── pkg-config
├── gettext
|   └── xz
├── libffi
├── pcre
└── zlib

Python is a "special" dependency for technical reasons, which is why it's got a colon on the front. That's a concept that upstream Homebrew has gotten rid of, but it still exists in Tigerbrew. Unfortunately, that's why brew info didn't show it, and brew deps stops at Python without showing its own dependencies.
I recognize this isn't the ideal user experience right now! Sorry about that. Right now my focus is on integrating Sevan's work to update more packages and get more things building, rather than making too many more changes to Tigerbrew's own code.
