### ISSUE TITLE
Support for bottles

### ISSUE THREAD

**Issue by rbrito** [mistydemeo/tigerbrew#95]
While we all love our PowerPCs, they can take a looong time to compile some programs (think GCC, Qt or many others).

It would be nice if we had a way to contribute back our precompiled binaries so that fellow users saved the trouble of compiling those big programs (or those that have lengthy test suites).

Sorry if this was already filed, but I could not find it here.

**Comment by EricFromCanada** [comment]
I doubt you need to generate G3 bottles for Leopard, since that version officially requires at least an 867MHz G4.
