### ISSUE TITLE
Insurmountable build failure when my repository is not `/usr/local`

### ISSUE THREAD

**Issue by gsteemso** [mistydemeo/tigerbrew#959]
Three different formulæ (Git, OpenSSH, and Subversion) all die from the same error:  When some program or another run during the build – in two cases ld64, in the other a test program compiled by the `configure` script – wants to load `${HOMEBREW_PREFIX}/opt/openssl/lib/libcrypto.1.1.dylib`, it fails utterly because the path is wrongly constructed relative to `$HOMEBREW_REPOSITORY` instead.  In my installation, the two are not identical – I keep my repository in its own self‐contained directory, out of the way.

(Why would I have done that, you may well ask?  I simply got tired of all the repository‐specific flerb cluttering up my `/usr/local` directory – Tigerbrew is not the only software that uses it, and to mentally filter out all the stuff that doesn’t actually need to be in there whenever I wanted to do anything involving it was getting a bit tedious.  I will also observe that, in light of the upstream Homebrew project’s recommendation for multi-user sites to keep an internal user‐level account specifically to own the Homebrew files, it might sometimes make the most sense for such a site to keep its repository in a directory specific to that account.)

**Comment by mistydemeo** [comment]
Hmmm, interesting issue here. Can you double check what `otool -L $(which ld64)` says?

**Comment by gsteemso** [comment]
It says,
        /usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 7.4.0)
        /usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 88.3.4)
in both the regular shell and under `brew sh`.

**Comment by gsteemso** [comment]
wouldn't those be different under Tigerbrew's ld64?  It is keg-only, and I have yet to work out how to see what those see.

**Comment by gsteemso** [comment]
oh, now that is interesting.  running `otool -L /usr/local/opt/ld64/bin/ld` netted me that same output, BUT with an extra line at the beginning containing that weird mis-constructed OpenSSL library path.

**Comment by mistydemeo** [comment]
Mind pasting exactly the command you ran and the output from the terminal?

**Comment by mistydemeo** [comment]
Oh, and can you show me your `brew --config`?

**Comment by gsteemso** [comment]
Apologies, the mail system did not deliver this until after I had gone to sleep.  The command I ran was only and exactly the one quoted above, and the output of it is

`/Users/gsteemso/Brewery/opt/openssl/lib/libcrypto.1.1.dylib (compatibility version 1.1.0, current version 1.1.0)
/usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 7.4.0)
/usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 88.1.10)`

and the output of `brew --config` is

`HOMEBREW_VERSION: 0.9.5
ORIGIN: (none)
HEAD: (none)
Last commit: never
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /Users/gsteemso/Brewery
HOMEBREW_CELLAR: /Users/gsteemso/Brewery/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://ia904500.us.archive.org/24/items/tigerbrew
CPU: dual-core 32-bit g5
OS X: 10.4.11-Power Macintosh
Curl: /Users/gsteemso/Brewery/Library/Homebrew/vendor/portable-curl/current/bin/curl
Xcode: 2.5
CLT: N/A
GCC-4.0: build 5370
GCC-4.2: build 5553
Clang: N/A
X11: 1.1.3 => /usr/X11R6
System Ruby: 2.3.3-222 => /Users/gsteemso/Brewery/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /Users/gsteemso/Brewery/Cellar/python/2.7.18_1/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /Users/gsteemso
Java: N/A`

(I don’t understand why it’s still using Homebrew’s internal cURL, as the dratted formula for that finally built properly a couple of days ago, and cURL 8.2.1 is working just fine in my `Cellar`.  For that matter, why it is still using the ancient release of Perl that came with Tiger is also a mystery, as Perl 5.38 was one of the few formulæ that built properly right out of the gate.)

**Comment by gsteemso** [comment]
While I still can't work out what is causing the build process to misconstruct the path to the SSL library, the bottled version of ld64 is working properly.  Marking this closed on account of "meh, close enough."
