### ISSUE TITLE
cURL error when installing on OSX 10.5.8

### ISSUE THREAD

**Issue by thonkinator** [mistydemeo/tigerbrew#975]
When installing on MacOS X Leopard 10.5.8, I get this error when trying to download `curl`:
```
curl: (35) error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
Failed during: /usr/bin/curl -Lk https://archive.org/downloads/tigerbrew/portable-curl-7.58.0.tiger_g3.bottle.tar.gz -o /tmp/curl.tar.gz
```
If it helps, here's the output of `curl -V`:
```
curl 7.16.3 (powerpc-apple-darwin9.0) libcurl/7.16.3 OpenSSL/0.9.7l zlib/1.2.3
Protocols: tftp ftp telnet dict ldap http file https ftps
Features: GSS-Negotiate IPv6 Largefile NTLM SSL libz
```
And `openssl version`:
```
OpenSSL 0.9.7l 28 Sep 2006
```
I'm aware these are pretty old versions but I'm not sure how to update them.

**Comment by thonkinator** [comment]
I temporarily got around this by manually downloading the file and copying it to /tmp/curl.tar.gz, and then commenting out the line that downloads the file

**Comment by sevan** [comment]
Issue is that it is no longer possible to use the facilities available on these legacy systems to fetch files from the internet via HTTPS nor verify what you have downloaded via SHA256.
To sidestep the issue, you can fetch a copy of the [tigerbrew tarball of the repository](https://github.com/mistydemeo/tigerbrew/tarball/master) and uncompress it into the destination e.g `/usr/local` using `/usr/bin/tar xzf somefilename.tar.gz -m --strip 1`

**Comment by mistydemeo** [comment]
Thanks for flagging this. Sorry for the issues. I've updated the installer to no longer use the HTTPS links, and to fall back to plain HTTP instead.
