### ISSUE TITLE
Several packages' tarballs are no longer where their formulæ expect them to be

### ISSUE THREAD

**Issue by gsteemso** [mistydemeo/tigerbrew#985]
In the course of chiseling away at the packages that will or will not build (so I can build a specific one that depends on several others), I have discovered that the following packages' source tarballs no longer exist:

libpgm (https://openpgm.googlecode.com/files/libpgm-5.2.122~dfsg.tar.gz) -- entire site is gone
norm (https://downloads.pf.itd.nrl.navy.mil/norm/archive/src-norm-1.5r6.tgz) -- site has an invalid certificate and the server seems to have been reorganized away with a change in management (related, maybe)
zeromq (http://download.zeromq.org/zeromq-4.1.3.tar.gz) -- they've moved their files to Github and the one Tigerbrew wanted to download is so far behind current they don't keep a copy
czmq (http://download.zeromq.org/czmq-3.0.2.tar.gz) -- this one actually is present in its new home on github (https://github.com/zeromq/czmq/archive/refs/tags/v3.0.2.tar.gz), but the Tigerbrew formula requires the aforementioned antiquated zeromq build that can't be had, so not quite as helpful as might be desired.
libgpg-error (which actually is there, but the bottled versions are out of date and show up as being missing; that confused the heck out of the build system until I forced it to brew from source)

**Comment by mistydemeo** [comment]
Thanks for flagging this! Eventually I'll want to update these old versions, but in the meantime I've opened a PR to fix the links and remove those stale bottles.
